### ISSUE TITLE
[discuss] API Design: Extent

### ISSUE THREAD

**Issue by missinglink** [pelias/pelias#119]
Following on from our discussion about the v1 API spec.

I'd like to open up a conversation about how we can simplify the naming and functionality of input parameters which specifically affect the geographic bounds and geographic bias of queries.

### current proposal
```
extent.lat
extent.lon
extent.radius
extent.min_lat
extent.max_lat
extent.min_lon
extent.max_lon
extent.strict
```

The feedback I have received for this proposal can be summarised as:
- `extent` is a term which implies a *hard* boundary
- it is not clear which parameters should be 'grouped' eg. `radius` mandates `lat,lon`
- it is not clear how `lat,lon,radius` and `min_lat,max_lat` etc. work when combined
- it is not clear how `strict` mode would work
- it is not clear which situations call for which parameters

### user agent info

There are 4x different inputs we can ask from the user agent which can be used for a geo bias:
- user agent `actual` location, ie. `navigator.geolocation` (lat/lon)
- user agent `viewport` bounds, ie. the lat/long co-ords of the map corners (rectangle)
- user agent `geo ip` location, ie. based on their connection; inaccurate (lat/lon)
- the `reverse geocode` of a fully specified query, ie. "foo, new york" (lat/lon)

It's important to note that the `viewport` indicates an area of focus for the user while the `actual` represents their physical location. Eg. I am in Berlin but looking at a map of New York.

There is an outstanding question here that; when given *both* `actual` and `viewport`, which is used to bias the query? It seems that the `viewport` should be used as per the example above, my results should be biased towards New York rather than Berlin.

There have been some discussions in the past about using the `reverse geocode` as a replacement for `viewport` when available.

### strict filters (developer options)

There are a few different ways of applying filtering to the results, in order to remove unwanted data from being returned and to speed up the query execution:

- filter by `bounding rectangle`, in the literal sense of the term, results **must** be inside the box or they are not returned. 
- filter by `bounding circle`, in lieu of a box a lat/lon/radius triple can be supplied to create a circle
- filter by `country code` or another field

The only thing worth mentioning about filters is that; given a `lat/lon/radius` it is trivial to create either a rectangle or a circle and so the question remains, "in which situations is a rectangle insufficient?"

## back to basics

An extremely simple API could look something like this:

```
focus.lat
focus.lon
bbox
```

With this simple API the user can easily accomplish a *soft* bias towards any lat/lon and also a *hard* filter to inside a bounding box. Neither param would be required.

Thoughts?

**Comment by dianashk** [comment]
Clients will need the `radius` any time there is a need to return only results that are no further than X meters away, e.g.: pizza places within 10 miles. If you use a `bbox` you have to make it either bigger or smaller than the true desired area. 

I really like the idea of specifying `circle` as a triple. I totally agree that allowing centroid and bbox at the same time opens a whole can of worms.

To piggy-back off the extremely simple API proposal, how about the following compromise?

**`focus.point`** achieves a *soft* bias *(question: we'd still need to decide on an appropriate hardcoded radius?)*
**`extent.circle` /  `extent.rect`** achieve *hard* filter, as the name `extent` apparently implies

Feels?

**Comment by missinglink** [comment]
I'm really not against supporting the `bounding circle`, I just wanted to point out that it adds some complexity in that 2x `lat/lon` pairs must be supplied, eg. the image below:

If you imagine that black represents the 'boost' applied to results which are nearer/farther away from the `focus`. A user would need to specify a `lat/lon` for the `focus` point and also a (potentially) different `lat/lon/radius` triple to draw the outer circle. 

![gradient](http://pe-images.s3.amazonaws.com/photo-effects/bubble-brush/move-gradient.jpg)

**Comment by dianashk** [comment]
The way I understand it, the bounding outer circle isn't a boost, it's a strict filter that has no impact on the scores of individual results. The point provided as `focus` is the only thing that should impact the scores, so results are sorted by closest first. If both are provided, `focus` and `extent` (either `circle` or `rect`) the results are filtered to be ONLY within the `extent`, and sorted by proximity to `focus` + some magic `query mixing` behavior.

**Comment by missinglink** [comment]
@dianashk that is my understanding also, ditto what you said.

**Comment by riordan** [comment]
@dianashk + I did a bit of user testing this afternoon with some of this terminology and came to some pretty strong findings about how we should present these ideas through the API.

# The Study
We presented folks with possible API parameters on notecards, trying out the different terminologies we've proposed over these past few weeks, and asked them to construct different types of queries. And results seemed to zero in on a few specific arrangements of parameters as most self-apparent. 

We tried this exercise with:
- Hanbuyl
- Ekta
- Meghan
- Chuck

They were presented with several cards representing parameters to construct an API query with.
From our earlier conversations in this thread, we'd determined that the notion of packing everything into the `extent.` namespace and using the `strict` flag was already confusing (we later had this sentiment echoed this in two of the sessions). Instead we started by separating the different types of geometry queries into those that affect the bias of the results from those that affected the geographic limits. People seemed to get this separation intuitively.

## Local Bias (aka magic)
We used the namespace `focus` to refer to the sorting & local prioritization elements, and all four testers gravitated to it immediately, nor could they suggest a more descriptive alternative.

Within the `focus` namespace we tried several names to represent two key ideas:
- The point where the user is `focus`.[`point`, `user_point`]
- The area of interest on the user's screen `focus`.[`rect`, `viewport`, `bbox`]

The primary test was to construct a search while the map displayed on the end-user's screen did not match the current location of the end-user.

For the location of where the user is, testers gravitated to `point`, recognizing the general context. Three believed it to be the device or user's current location if known, but one thought it to be the focal point of the area of intent. They believed it to center the search, but to not exclude global results.

In practice, all four testers preferred to use the region of the map displayed on the user's screen to represent the end-user's current area of intent. When presented with the options of `rect` and `viewport`, testers selected `viewport` over `rect` without hesitation. They believed this to be a non-exclusionary parameter, selecting the region for equal prioritized evaluation, but to also include high-matching global results. One tester noted that `bbox` and `viewport` are often used in web development to represent this concept, but that `bbox` felt more arbitrary ("drawable") but exclusionary, while `viewport` felt more clear,
but open-ended to include useful places beyond.

## Constraining Search Regions
Here there was some contention over the terminology for the namespace as well as some of the parameters.

We would present the testers with several cards with the same parameter names, but different namespaces and asked how they would construct a search where only matches in the area would be found. Initially we offered them only `extent`, but after confusion with the first tester, we added `limit` into the mix of options, and it was selected. Following this test, we compared `limit` and `boundary` and the final two testers selected `boundary` (for purposes of clarity (limit's overloaded, can be used for the number of results) and translation).

Within the `boundary` namespace, we tested two geometries:
- `circle`, a point with a radius. All testers got this one and most specified the necessary inputs without prompting.
- "bounding boxes": a rectangle. Between `bbox` and `rect`, testers gravitated to `rect`. Two noted `bbox` was too "Jargon-y".

## Other Notes
One tester used `focus.point` in conjunction with `boundary.circle` to construct a search within a specific radius. While not the ideal way of performing this query, it would still, given our implied logic, return a similar result.

# The Proposal
Geometry operations are grouped into `focus` and `boundary` namespaces:
* `focus` provides context about the user's current location / location of interest and impacts scoring and sorting. It is intended to prioritize local results, but search globally, enabling users to principally see matching places nearby, high matches further away, and use the query string to change the search's area of focus.
* `boundary` provides explicit geographic limits to the area of the search, enabling search only within a particular, defined region.

They are not mutually exclusive (you can use `boundary` and `focus` together), but their interactions are discussed further below.

## Short(ish) Version
`focus.`:
- `focus.point` = lat/lon pair of the user's area of interest. We prefer this to be the device lat/lon, but could be used otherwise. Does not exclude results outside the the hard coded bias area around the point, but puts best local matches before global matches.
 - `focus.point.lat` + `focus.point.lon` = explicit declaration of the lat/lon points above
- `focus.viewport` = bbox of the user's viewport. Assumed to be active focal area of the user's intent. Overrides `focus.point` if both are present.
 - `focus.viewport.minLon` + `focus.viewport.minLat` + `focus.viewport.maxLon` + `focus.viewport.maxLat` = explicit declaration of the viewport bbox points above.

`boundary.`:
- `boundary.rect` = Explicit region bounding box. Nothing outside these coordinates is returned. All linguistic matches within the boundary are equal.
 - `boundary.rect.minLon` + `boundary.rect.minLat` + `boundary.rect.maxLon` + `boundary.rect.maxLat` = explicit declaration of the boundary bbox points above.
- `boundary.circle` = lat,lon,radius triple defining a circle to bound the search region. Nothing outside of this circle is returned. All linguistic matches within this boundary are equal. Radius unit defaults to meters, but can be overridden
 - `boundary.circle.lat` + `boundary.circle.lon` + `boundary.circle.radius` = explicit declaration of the circle boundary above.
- `boundary.country` = alpha-2 country codes

`boundary.rect` is mutually exclusive with `boundary.circle`; only one may be present in a given query. `boundary.country` may be used in conjunction with either `boundary.rect` or `boundary.circle`, but if the region does not fall within the matching country, no results will be found. 

**NOTE: For the purposes of completeness, it should be noted that `boundary.country` was not workshopped with today's test group. However in a similar workshop this past weekend with several non-geo developers, the `country` parameter was immediately understood. Given the context, it feels acceptable to combine `country` with the `boundary` namespace.**

If a `focus.point` is used in conjunction with a `boundary`, and the point is within the `boundary`, then the distance from the point is used as a sorting mechanism for the points. It would get more confusing with a `focus.viewport` and a `boundary`, so let's say those are incompatible.

These parameters are applied to the general-purpose `/autocomplete` and `/search` endpoints. Their application for coarse endpoints should be discussed (upon resolution of how we handle coarse geocoding. See: pelias/api#176).

# Next Steps

I believe this is a pretty effective distillation and testing of all of the ideas that have been put forward around API terminology and usability. And they've been workshopped against users beyond the team with overwhelmingly positive results.

If there are no major disagreements with the above, these will be the names and functions of the scoping parameters going forward.

**Comment by missinglink** [comment]
amazing work, this is much more clearly specified now!

we are totally on the same page regarding the `terminology`, I still have a couple of minor points about the `functionality` which I'd like to bring up while we are on the topic.

### focus width

there is still a little confusion about something we could call `focus.width` (working title), meaning that given a `focus.point` there is certainly a radius around that point which also gains soft focus.

the question I'm asking is "can the user control the extent of the effects of soft focus?", or if you want to get all mathsy: "can the user control the shape and length of the decay arc?"

@dianashk summaried the problem in a previous comment:
"focus.point achieves a soft bias (question: we'd still need to decide on an appropriate hardcoded radius?)"

this is particularly relevant when talking about `focus.viewport` as you can imagine the viewport zoomed out to encompass the whole world, in this case, would the focus only apply within x miles of the centroid, or would a boost be applied across the entire visible map area?

a `focus.point` can always be computed from a `focus.viewport` but it is a lossy operation, in that the information about `focus.width` is lost in the process, something @riordan and I discussed in the past.

this is the reason I decided to remove `viewport` from my simple proposal as it necessitates this new variable `focus.width`, a variable I think is unnecessarily complex and would be better handled by a decay function rather than a single integer.

if we decide to hard-code a `focus.width` value in to the codebase then we may as well remove the `focus.viewport` parameter completely as it is equivalent to using `focus.point` with the viewport centroid, plus the API is much cleaner and easier to use.

### mutually exclusive boundary params

it's a little confusing to a 3rd party developer to say that `rect` and `circle` are mutually exclusive while using `country` and *either* `rect` *or* `circle` is not.

I also think that specifying a `boundary` that lies outside the `country` and then getting 0 results back is potentially confusing, especially for 3rd parties where these variables may be provided by an untrusted/unknown agent.

so if we can figure out a way to make this more intuitive then we should, the obvious solution would be to say that they are **all** mutually exclusive and be done with it.

### bounding circle

in order to avoid flogging a dead horse here, I will make one last attempt at convincing you that `boundary.circle` is not required before dropping the topic ;)

for clarity, what we are discussing here is the dark area in the image below:

![image](http://www.platinumgmat.com/global/images/study_guide/circles6.gif)

#### /reverse

for reverse search there is *no difference* between `rect` and `circle` in the vast majority of cases, this is because the results are *sorted* by their distance from the centroid, so you will get the same results in the same order regardless of the geometry used to bound it.

the difference comes when there are less than `max_results` of the 'thing' you asked for in the `circle` but there are some present in the `rect` corners.

example: with the image above, imagine you wanted the nearest Lithuanian restaurants and there were 4 inside the white circle and one in the dark area, in this case the `rect` query would return one additional result to the equivalent `circle` query.

it's worth quickly mentioning that a traditional reverse search would only return one result and so bounding would not apply, it's only relevant for faced reverse search.

#### /search & /suggest

doing a `circle` query on the backend takes more CPU cycles and results in slower responses than a `rect` query (although this is negligible at smaller radius's), this is due to elasticsearch internally doing a `rect` filter first and then doing the distance calculations only on the remaining results.

I cannot come up with a use-case for `bounding circle` for /search, maybe I'm missing something?

I think that `country` will be super useful but bounding by radius for search doesn't really make sense?

#### summary

you can see that the behaviour is only slightly different between `bounding rect` and `bounding circle` and only seems to impact queries in certain situations, and that impact is not 'bad'.

the `bounding` parameters are not intended for end users such as mobile phone users and so the API need not be designed with novices in mind.

the `circle` triple introduces a new measurement (meters, km, miles) which is not present elsewhere in the API, we would either need to support both metric *and* imperial, *or* make a call on which one is 'correct' for our system.

I am still not clear on which use cases would require the param to be present in /search or /suggest.

pros:
- can give user a hard guarantee that results are within x units
- provides an easy to use API which is 'human friendly'

cons:
- introduces a `bounding` API which is functionally not much different from `rect`
- introduces a new unit of measurement which is not standardized between locales
- adds complexity in that 2 sets of lat/lon pairs may need to be provided

**Comment by riordan** [comment]
One point of clarification from my mega-comment above; I had to update all the `lat/lon` language to be `lon/lat`, as per GeoJSON specifications. Which makes sense. We like `x,y` coordinate pairs. Lets let our locations be `x,y` pairs.

**Comment by missinglink** [comment]
right, as per the elasticsearch docs:

> Everybody gets caught at least once: string geo-points are "latitude,longitude", while array geo-points are [longitude,latitude]—the opposite order!

> Originally, both strings and arrays in Elasticsearch used latitude followed by longitude. However, it was decided early on to switch the order for arrays in order to conform with GeoJSON.

> The result is a bear trap that captures all unsuspecting users on their journey to full geolocation nirvana.

in terms of our specifications, I would say something like this:

> when describing Cartesian coordinates we strongly recommend the use of key/value pairs, where the name of the keys are 'lat' and 'lon' (not 'lng')

> the ordering of the keys is not important, so ```{ "lat": 1, "lon": 2 }``` is equal to:
 ```{ "lon": 2, "lat": 1 }```

> using keys avoids much of the potential confusion around using an array syntax (described above)

> we accept the array syntax is more succinct but prefer to sacrifice that succinctness in favour of an intuitive API which does not necessitate prior knowledge of domain specific protocols/standards

> there are some cases where another standard elects to use an array syntax `eg. GeoJSON`, in that case we will conform to their specification.

> as we have already adopted the GeoJSON spec, we will never change the way we notate array syntax, we will not adopt another specification which does not conform to the [ longitude, latitude ] ordering defined in GeoJSON

**Comment by riordan** [comment]
Well put.

On Thu, Aug 27, 2015 at 8:41 AM, Peter Johnson a.k.a. insertcoffee <
notifications@github.com> wrote:

> right, as per the elasticsearch docs:
>
> Everybody gets caught at least once: string geo-points are
> "latitude,longitude", while array geo-points are [longitude,latitude]—the
> opposite order!
>
> Originally, both strings and arrays in Elasticsearch used latitude
> followed by longitude. However, it was decided early on to switch the order
> for arrays in order to conform with GeoJSON.
>
> The result is a bear trap that captures all unsuspecting users on their
> journey to full geolocation nirvana.
>
> in terms of our specifications, I would say something like this:
>
> when describing Cartesian coordinates we strongly recommend the use of
> key/value pairs, where the name of the keys are 'lat' and 'lon' (not 'lng')
>
> the ordering of the keys is not important, so { "lat": 1, "lon": 2 } is
> equal to:
> { "lon": 2, "lat": 1 }
>
> using keys avoids much of the potential confusion around using an array
> syntax (described above)
>
> we accept the array syntax is more succinct but prefer to sacrifice that
> succinctness in favour of an intuitive API which does not necessitate prior
> knowledge of domain specific protocols/standards
>
> there are some cases where another standard elects to use an array syntax eg.
> GeoJSON, in that case we will conform to their specification.
>
> as we have already adopted the GeoJSON spec, we will never change the way
> we notate array syntax, we will not adopt another specification which does
> not conform to the [ longitude, latitude ] ordering defined in GeoJSON
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pelias/pelias/issues/119#issuecomment-135409661>.
>



-- 
David Riordan | Product Manager - Search | dave.riordan@mapzen.com |
@riordan <https://twitter.com/riordan> | gpg 235D9DC95EF6277C
<https://keybase.io/riordan>
Mapzen | https://mapzen.com | @mapzen <https://twitter.com/search>

**Comment by dianashk** [comment]
I'm good with `focus.point` + `decay function` for v1. We can introduce `focus.viewport` later, if we see people wanting to use that sort of thing. Chuck mentioned that he would always prefer `focus.point` for mobile, because the viewport size could change based on the screen size, but the center of the screen is always the center of the screen. 

I think the pros for `boundary.circle` outweight the cons. Caching is a big concern, but we can document this feature in the future (when caching is a reality) to let users know that this particular feature will be slower than those that can be cached. It's also not a given that it would be slower. We could still approximate the circle with geohash blocks if we really wanted to.

So let's finalize the new proposal:

### `focus`
Allows user to specify a soft focus, so that results closest to the specified point will be listed first. This will be implemented using a `decay function`. Results with high importance or high match outside of the decay function should still be returned as part of the result set.
> `focus.point.lat` {number}
>  `focus.point.lon` {number}
> `focus.point` {array} where [lon, lat]

### `boundary`
Allows the user to specify a hard limit, so that results must all fall within the specified boundary geometry. This can coincide with `focus`, where `focus` may or may not be within the `boundary`, in which case the results are simply sorted by distance from the point of focus, but still only reside within the `boundary`.
> `boundary.rect.min_lon` {number}
> `boundary.rect.min_lat` {number}
> `boundary.rect.max_lon` {number}
> `boundary.rect.max_lat` {number}
> `boundary.rect` {array} where [`min_lon`, `min_lat`, `max_lon`, `max_lat`]
> 
> `boundary.circle.lat` {number}
> `boundary.circle.lon` {number}
> `boundary.circle.radius` {number} in meters (because international)
> `boundary.circle` {array} where [`lon`,`lat`,`radius`]
