### ISSUE TITLE
Bad data found when searching for `undefined` and `null`

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#127]
Searching for `undefined` and `null` surfaces invalid data. Investigate if data is bad at the source or got corrupted during import process.

**Comment by missinglink** [comment]
Some may be errors in our import pipelines caused by javascript being javascript:

```javascript
''+undefined
"undefined"

''+null
"null"
```

while others are errors in the source data such as:
- http://nominatim.openstreetmap.org/details.php?place_id=111274049
- http://nominatim.openstreetmap.org/details.php?place_id=2571778702
... and the quattroshapes entries with the name of `"(null)"`

keep in mind that `null` is actually a valid place name! :)

**Comment by orangejulius** [comment]
I've looked through and many of these are in fact bad data in OSM. At Maptime the other night I went through and corrected some:

http://www.openstreetmap.org/changeset/34217000
http://www.openstreetmap.org/changeset/34216918
http://www.openstreetmap.org/changeset/34216892
http://www.openstreetmap.org/changeset/34216872
http://www.openstreetmap.org/changeset/34216862
http://www.openstreetmap.org/changeset/34216851
http://www.openstreetmap.org/changeset/34216842
http://www.openstreetmap.org/changeset/34216785
http://www.openstreetmap.org/changeset/34216782
http://www.openstreetmap.org/changeset/34216776
http://www.openstreetmap.org/changeset/34325708

There may be a few left, but already on production most of them are gone since last weekends import.

**Comment by missinglink** [comment]
nice!

**Comment by orangejulius** [comment]
After the latest import with those OSM changes, there is only one result left that exactly matches undefined: http://pelias.compare.s3-website-eu-west-1.amazonaws.com/#/v1/search%3Ftext=undefined

There are quite a few nulls, however. Looks like they come from all sorts of different data sources: http://pelias.compare.s3-website-eu-west-1.amazonaws.com/#/v1/search%3Ftext=null

**Comment by mtmail** [comment]
"Nüll, Lippe, Germany" exists. I've been there. Lippe as county is correct. The left side says "Regierungsbezirk Detmold" was a county, but it's a administrative level between states (16 in Germany) and counties and has relevance for bureaucracy (school system, courts) but not in addresses.

**Comment by missinglink** [comment]
> "Nüll, Lippe, Germany" exists. I've been there

```
Mr. Null approves of this message
 _ _
[0,0]
 \-/
```

**Comment by orangejulius** [comment]
There's also "Die Null" http://www.openstreetmap.org/node/1860887706#map=17/51.32660/11.33987, which since it translates as "the zero" and looks a lot like a zero, appears real too

**Comment by dianashk** [comment]
Evaluate if this has been fixed.

**Comment by trescube** [comment]
There are a number of records in OA that contain `null` or `undefined`:

```
admins-MBP-4% egrep -i "\bnull\b" *.csv | wc -l
 1337342
```
