### ISSUE TITLE
search in leaflet plugin cannot find San Francisco, CA

### ISSUE THREAD

**Issue by burritojustice** [pelias/pelias#128]
sometimes San Francisco County comes up, but that gets centered halfway to the Farallon Islands, i.e nothing but water...

**Comment by missinglink** [comment]
related: https://github.com/pelias/api/pull/309

**Comment by bdon** [comment]
Just to chip in on a few other search results:

* Buenos Aires --> far to the southwest
* Sao Paulo --> far to the northeast
* Tokyo --> in the water in Tokyo Bay, but Nominatim also has this issue
* Vancouver --> is not in top 5 search results
* New York, NY --> "New York, NY" result is actually upstate, "New York County, NY" is the 2nd result, but correct

**Comment by missinglink** [comment]
update on this. there is a new PR https://github.com/pelias/api/pull/338 in review

The reason the lat/lon values are off is because they are computed 'centroids' of polygon data. [more info](https://github.com/pelias/pbf2json/issues/22#issuecomment-115235262)

When we move to https://github.com/whosonfirst in ~december we will have different centroids to work with, one will be the computed centroid and another one will be the 'label' centroid, which should also be better for routing purposes.

here's some test data from the staging server for the PR above, first result only:
````
/v1/search?size=1&text=san francisco
1) San Francisco, San Francisco County, CA
[ -122.41942, 37.77493 ] <-- looks better to me

/v1/search?size=1&text=Buenos Aires
1) Buenos Aires, Ciudad de Buenos Aires, Buenos Aires F.D.
[  -58.37723, -34.61315 ] <-- looks better to me

/v1/search?size=1&text=Sao Paulo
1) São Paulo, Brazil
[  -49, -22 ] <-- still not good, poor float precision from geonames!?
2) São Paulo, Brazil
[  -46.63503, -23.62703 ] <-- second result looks better to me

/v1/search?size=1&text=Tokyo
1) Tokyo, 新宿区, Tōkyō
[ 139.69171, 35.6895 ] <-- looks better to me, using the geonames record no longer in the ocean

/v1/search?size=1&text=New York, NY
1) New York, NY
[ -75.4999, 43.00035 ] <-- somewhere near the center of new york **state**?

/v1/search?size=1&text=New York City, NY
1) New York City, Manhattan, NY
[ -74.00597, 40.71427 ] <-- looks better to me, just off broadway
```
