### ISSUE TITLE
Local naming convention

### ISSUE THREAD

**Issue by gkamp** [pelias/pelias#141]
Just started looking at Pelias, so maybe this question is answered somewhere. But i couldnt't find it in the API documentation.

We germans like our house numbers after the street names, not before. Unfortunately the name returned by the API doesn't Looking at the OSM import scheme it looks like that quite a number ao names are imported including a local name.

Hence i hoped to be able to find the local label exposed somehow via the API. As said above, i couldn't find it. Is there a way to get a Full record. Or is the local name missing right now from the index.

Ideally one would be able not only get the local and other names but to include the desired locale of the result names as a request parameter

**Comment by missinglink** [comment]
hey @gkamp, the `{housenumber} {streetname}` syntax is more common around the word so that is what we use as a default, although as a Berliner I do commiserate with you!

in an ideal world we would generate the labels based on the locale of the record and then re-order the label parts based on the user locale, but this is quite complex and we likely wont get to it until we do a sprint focussed specifically on internationalization.

for now you'll have to generate your own labels, so for the record:

```
"/v1/search?api_key=search-xxxxxx&size=1&text=7 Kurfürstenstrasse"

{
  "geocoding": {
    "version": "0.1",
    "attribution": "http://pelias.bigdev.mapzen.com/v1/attribution",
    "query": {
      "text": "7 Kurfürstenstrasse",
      "size": 1,
      "private": false
    },
    "engine": {
      "name": "Pelias",
      "author": "Mapzen",
      "version": "1.0"
    },
    "timestamp": 1444318635380
  },
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "id": "address-osmnode-2880556282",
        "gid": "osm:address:address-osmnode-2880556282",
        "layer": "address",
        "source": "osm",
        "name": "7 Kurfürstenstrasse",
        "housenumber": "7",
        "street": "Kurfürstenstrasse",
        "postalcode": "13467",
        "country_a": "DEU",
        "country": "Germany",
        "region": "Berlin",
        "county": "Berlin",
        "locality": "Berlin",
        "neighbourhood": "Borsigwalde",
        "confidence": 0.54,
        "label": "7 Kurfürstenstrasse, Berlin, Germany"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          13.304927,
          52.608986
        ]
      }
    }
  ],
  "bbox": [
    13.304927,
    52.608986,
    13.304927,
    52.608986
  ]
}
```

you can see that you have enough granularity to build you own labels as you wish, we will only ever provide a single label property, at some point we will change the default label to be more locale aware.

hope that helps!
