### ISSUE TITLE
Reverse geocoding uses neighbourhood when not in city bounds

### ISSUE THREAD

**Issue by erjiang** [pelias/pelias#167]
Try reverse geocoding (38.540403461, -121.7714524269). The label comes out as "110A Sage Street, Westwood, CA". It's definitely not in the census-designated place of Westwood, in Lassen County. The expected label would be "110A Sage Street, Davis, CA".

Problem seems to be that the point is slightly outside the city of Davis, and whatever places DB (quattroshapes?) contains data for a neighborhood named "Westwood" that is nearby.

Edit: fix expected label "Westwood" -> "Davis"

**Comment by nvkelso** [comment]
@erjiang Can you clarify the expected behavior for the label in this case? Would you expect to see:

1. `110A Sage Street, Westwood, Davis, CA`
2. `110A Sage Street, Davis, CA`
3.  `110A Sage Street, Yolo County, CA`
4.  `110A Sage Street, Westwood, Yolo County, CA`

Or something else?

NOTE: the neighbourhood shapes (from Quattroshapes in this case) do include Westwood as almost wholly outside of Davis city limit (maybe correct, maybe not).

**Comment by nvkelso** [comment]
(It is valid for a "neighbourhood" to be parented by a county, just a little odd for city dwellers to think about that.)

**Comment by erjiang** [comment]
I would expect to see "110A Sage Street, Davis, CA". Maybe "110A Sage Street, Westwood, Davis, CA" but I think in general neighborhood names are not as well known to people.

I agree that neighborhoods can be parented by cities, but addresses outside of city boundaries are still paired with the city for mailing addresses, etc.

**Comment by nvkelso** [comment]
Thanks for the feedback, very helpful! 

@riordan we should pursue "postal cities" in Who's On First to enable this (basically a pre-composited postal address label), but still preserve the option of getting the neighbourhood back in the structured response.

**Comment by orangejulius** [comment]
Howdy,
We improved our label handling a few months ago, but in this case it has made things arguably worse.
The [reverse query](http://pelias.github.io/compare/#/v1/reverse%3Fpoint.lat=38.540403461&point.lon=-121.7714524269) from above now results in labels like `110A Sage Street, CA, USA`, because we now generally disregard neighbourhoods for creating labels.
![screenshot_2016-07-01_17-52-30](https://cloud.githubusercontent.com/assets/111716/16535395/f3024426-3fb4-11e6-9827-e9900e67a427.png)

Since this particular point falls outside the polygon for the city of Davis, we can't currently put Davis in the label. But if the geometry is wrong I'm sure that can be easily fixed, and this "postal cities", which is also helpful in other cases, looks promising and we could support that. One fix we _could_ make very quickly would be to fall back to the county name in labels if there's no city, leading to labels like `110A Sage Street, Yolo County, CA, USA`. Would that help?

**Comment by nvkelso** [comment]
I vote for pushing "country fallback" to prod for a few months of in the wild testing while the "postal cities" data work progresses.

**Comment by erjiang** [comment]
Falling back to county name would make sense - mail addressed to "110A Sage Street, Yolo County, CA, USA" would be more likely to get there than "110A Sage Street, CA, USA" which can be very ambiguous.

**Comment by orangejulius** [comment]
Sounds good. I just created https://github.com/pelias/api/issues/575 to track the actual work for this. @trescube any feedback on this issue or the proposed solution in the API ticket?

**Comment by trescube** [comment]
I'm good with the county fallback when neither locality nor localadmin are available.

**Comment by dianashk** [comment]
Looks like this is fixed. Other linked issues are tracking tangential work.
