### ISSUE TITLE
Add popularity scores to landmarks

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#171]
Many landmarks or locations have common names, _Union Square_, _Statue of Liberty_, _Main Street_, etc. It is impossible to predict their sort order in results at the moment. Elasticsearch will often assign them identical scores. Therefore the order is arbitrary.

When searching for `Statue of Liberty`, however, you expect that the one in Manhattan will be at the very top (if no focus point was specified).

**Comment by mtmail** [comment]
There's even multiple Eiffel Towers around the world http://www.openstreetmap.org/node/2407752390, never mind the ones misspelled as Eifel Tower http://www.openstreetmap.org/way/337741972
I gave a conference talk about that once. Oh the joy of geocoding :)

**Comment by riordan** [comment]
Can we approximate this popularity metric via Wikipedia access logs? Cc @nvkelso @orangejulius

**Comment by riordan** [comment]
Hard to figure what a methodology for this will be (after we remove Geonames). Lets tackle this one as a "Glorious Future".

**Comment by tomtom92** [comment]
Approximating population is usually one of the largest factors in geoparsers, such as the [Edinburgh Geoparser](https://www.ltg.ed.ac.uk/software/geoparser/). But other factors, including ranking (I guess popularity?) within a gazetteer, and geographical boundary can help disambiguate.

**Comment by bboure** [comment]
Hi all, any news on this? I am facing similar issues, not only with places having the same name being returned in random order, or the most popular one not being first. This also (and especially) happens when places have several names or a different "popular name" vs the official name. 

A good example of this would be searching for "Sagrada Familia" in Barcelona.

The are **many** places with that name in Barcelona: Hotels, schools, metro stop, bus stop, a neighboorhood, shops, etc. and of course, there is [this](https://en.wikipedia.org/wiki/Sagrada_Fam%C3%ADlia).
The thing is that its official name is "Temple Expiatori de la Sagrada Família", or sometimes "Basílica de la Sagrada Familia", but people commonly just call it "La Sagrada Familia".

Searching for "Sagrada Familia" will give you many results .... except for Gaudi's work... (or it would appear down in the results), when this is in fact probably what you are really looking for.

Example: http://pelias.github.io/compare/#/v1/search%3Fboundary.circle.lat=41.3851&boundary.circle.lon=2.1734&boundary.circle.radius=5&text=Sagrada%20Familia


How can we deal with that?


Maybe we could approxicame somehow the popularity based on some factors. 
@riordan suggested wikipedia logs.. is that possible?
- OSM logs would be a clue too (number of total edits, contributors).
- the presence, or not, of some tags like the `wikitada`/`wikipedia` tags. They are usually a sign that there is some interest in the place, IMHO
- number of total OSM tags

... or maybe with less automatic way:
- have an API endpoint used as a callback that counts a place's number "hits" (number of times a place was actually clicked after a search/autocomplete).
The system would then learn with time what is "important".


Anyone knows how OSM (nominatim) handles this? Bacause they seem to handle this [very well](https://nominatim.openstreetmap.org/search.php?q=Sagrada+Familia&polygon_geojson=1&viewbox=)
Apparently, the `importance` field handles that. [see here](https://nominatim.openstreetmap.org/details.php?place_id=249824154)

Thanks

**Comment by NickStallman** [comment]
@bboure I'm working on a few experiments at the moment with the goal of getting some scoring going.

It looks like a two pronged approach will be needed, identifying popular areas, and then a more fine grained per POI 'popularity'.

I don't think using OSM or Wikipedia logs are viable, the amount of data you'd need to download is excessive to access that information. They probably wouldn't be overly useful either.

I'm hoping to have some results to show in a few weeks.

**Comment by bboure** [comment]
Thanks @NickStallman for your quick response. I'll stay tuned.

**Comment by bboure** [comment]
Hi there,

Any news on this?

**Comment by missinglink** [comment]
Hi @bboure

I've opened a PR to add this functionality in Pelias.
https://github.com/pelias/openstreetmap/pull/493

I'd appreciate everyone's input on that PR to decide which tags we support and the weight of each.

**Comment by NickStallman** [comment]
I've been busy unfortunately so I haven't been able to progress as much as I'd like.

@missinglink that PR looks great!
I think the one thing it needs is a debug UI, a map with all the POI's colour coded by score with the ability to click on each one to see how the score was calculated.
That way the scores could be fine tuned more clearly.

**Comment by orangejulius** [comment]
We've added the ability to set popularities of venues over in https://github.com/pelias/openstreetmap/pull/531, but of course we will always be tweaking this functionality over time.

Feel free to open new issues for new ideas or improvements to venue popularity scores :)
