### ISSUE TITLE
Improperly returning township name as city name

### ISSUE THREAD

**Issue by dgearhart** [pelias/pelias#184]
**Search for:** Houlihan's, Hershey, PA
**Pelias returns:** Houlihan's, Derry, PA
This is very confusing to the user
**Screenshot:**
![screenshot from 2015-12-01 15 44 40](https://cloud.githubusercontent.com/assets/7515853/11514145/fb18bca2-9844-11e5-9b08-2b34b112b9f2.png)

**OSM Record:** http://www.openstreetmap.org/node/1588990213#map=19/40.28492/-76.65090

Another example

**Search for:** Turkey Hill Minit Market, Hummelstown, PA
**Pelias returns:** Turkey Hill Minit Market, Derry, PA
This is very confusing to the user
**Screenshot:**
![screenshot from 2015-12-01 15 47 09](https://cloud.githubusercontent.com/assets/7515853/11514231/62133d42-9845-11e5-9bda-16924e0e8d5f.png)

**OSM Record:** https://www.openstreetmap.org/way/358223911#map=19/40.23799/-76.71154

**Comment by riordan** [comment]
Thanks for flagging @dgearhart.

I have a _hunch_ this will be fixed with Who's on First. We'll see soon.

**Comment by trescube** [comment]
Since I'm currently in the label generation (and @dgearhart berated me about when I walked in today), I checked it out.  The `local` field chain is:

`localadmin, locality, neighbourhood, county`

so `localadmin` is favored over `locality` during label generation.  In the case of "Houlihan's, Hershey, PA", `localadmin` is "Derry" while `locality` is "Hershey" so "Derry" is used for the label.  I get the feeling that the reason `localadmin` is favored over `locality` is because of the NYC boroughs, so "Gracie Mansion, New York, NY" has the label "Grace Mansion, Manhattan, NY".  

The solution is to special case NYC or always favor `locality` over `localadmin`.

**Comment by dgearhart** [comment]
**Search for:** 1181 Mae Street, Hummelstown, PA
**Search returns:** 1181 Mae Street, Derry, PA
This is very confusing to the user. 
Also, why do we not use the city name from OSM?

**Search Result Screenshot:**
![screenshot from 2016-02-25 11 15 50](https://cloud.githubusercontent.com/assets/7515853/13325945/f9aeabfa-dbb1-11e5-976b-487fa76a06d1.png)

**OSM Record:** http://www.openstreetmap.org/node/529752435
**OSM Screenshot:** 
![screenshot from 2016-02-25 11 14 24](https://cloud.githubusercontent.com/assets/7515853/13326075/6f3a39a2-dbb2-11e5-8432-681e5438cf47.png)

**Comment by mattwigway** [comment]
I'm also seeing this in Indianapolis, for example 111 Monument Circle, Indianapolis, IN becomes 111 Monument Circle, Center, IN.

**Comment by dianashk** [comment]
Houlihan's comes back correctly now: http://pelias.github.io/compare/#/v1/search%3Ftext=Houlihan's,%20Hershey,%20PA

**Comment by orangejulius** [comment]
This one looks to have been fixed, probably with the transition to Who's on First.
![screenshot_2016-07-01_16-45-27](https://cloud.githubusercontent.com/assets/111716/16534103/50d46552-3fab-11e6-97dd-eef71915de09.png)



Also as mentioned in https://github.com/pelias/pelias/issues/137, all Indianapolis related issues were fixed by our Who's on First transition a few months ago and the valiant efforts of the Who's on First team to make sense of Indianapolis's interesting administrative structure.
![screenshot_2016-07-01_16-36-59](https://cloud.githubusercontent.com/assets/111716/16534149/94235cd2-3fab-11e6-878e-4d20dcc10d24.png)

I'm closing this issue but, of course, feel free to reopen if anything else is wrong. :palm_tree:
