### ISSUE TITLE
Multiple dev environments on demand

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#205]
Right now, we have one develompent environment that can be used to test API code against an existing set of data in Elasticsearch, test changes to our import code, or both. Most of our infrastructure for working with dev is automated, but we should go the final mile and allow new entire dev environments to be spun up on demand when needed. As our rate of new features that require datasets that won't fit on our laptops increases, we'll certainly need this.

**Comment by riordan** [comment]
I'll add one more ornament to this :christmas_tree:

It would be great if we were able to keep various production builds around on S3 for a fixed period of time (e.g. 2 months) (or perhaps put them to cold storage with Glacier), with the ability to restore them for one of these multiple dev environments. It doesn't have to be full hardware (and can probably run mostly from swap disk rather than RAM) since it would be for QA purposes.

**Comment by orangejulius** [comment]
This is an old Mapzen Search issue. Farewell!
