### ISSUE TITLE
OpenAddresses importer should rely on individual files, not collected.zip

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#247]
## The Short Version

Let's stop using OpenAddresses' `collected.zip` file and move onto using individual files from their "sets" to preserve data processing integrity.
## Longer Version

Last week, it was brought to our attention that certain addresses in OpenAddresses were being "expanded" (eg. `la` -> `lane`), irregardless of the language of origin for that place (or language of naming of the streets). (pelias/pelias#232) This led to issues with addresses in France and Mexico (where OA has complete national coverage).

OpenAddresses has since solved the issue of automatically rewriting/expanding everything in its path (openaddresses/machine#32), so now the individual csv files are un-expanded.

However, the code that continues to do the post-processing is still putting those improper expansions into `collected.zip` (which we use).

Instead we should be pulling the individual CSVs to ensure that we do the de-duplication and expansions we believe to be correct.

At the same time, we can help with the ongoing effort to build OA's new "csv enhancer" feature (openaddresses/machine#238), and contribute steps to its enhancement pipeline from our work.
# Bonus Round
## Ambiguous Expansions / Alt Names

Sticking with this original data, and not the "guessed expansions" as our authoritative names for these addresses can be particularly useful, especially when combined with Libpostal.

In the case of an ambiguously named address, it's better to store and return the semi-ambiguous name than auto-correcting to something wrong. Imagine trying to automatically resolve the conflict with [St of Dreams](http://www.openstreetmap.org/way/15502053) or [St Marks St](http://www.openstreetmap.org/way/20226080).

Instead it's better to be a bit ambiguous in the short-term, then later correct the upstream data source, rather than expanding to "Street Marks Street by default.
## Data-stamps

This would also help with being able to surface the particular data that has gone into a build"data build" (e.g. timestamp of an OSM planet, commit hashes of Who's on First, and now the [OpenAddresses set number](http://results.openaddresses.io/sets/).

This can help with the ticket asking for a builds dashboard that points to how to identify the current OSM build (pelias/openstreetmap#78)

**Comment by orangejulius** [comment]
We should wait for https://github.com/openaddresses/machine/issues/293 so that we can link down to the level of individual CSV zip files if we aren't doing a full import

**Comment by migurski** [comment]
You can now link to individual CSV files. I also added a JSON index with [URI templates](https://tools.ietf.org/html/rfc6570) to make it more future-proof: http://results.openaddresses.io/index.json

http://results.openaddresses.io/latest/run/de/berlin.zip is an example.

http://results.openaddresses.io/state.txt is still probably the best place to do this in bulk, though.

**Comment by orangejulius** [comment]
I didn't realize until just now that the big OA download files will continue to do some expansions that we don't want, so this should probably be bumped up a bit in priority.

**Comment by migurski** [comment]
Hopefully we can make the difference between the two downloads more self-evident. It’s probably correct for Pelias to use the files linked from http://results.openaddresses.io/state.txt, since they’re going to be less processed. We’ve been thinking about processing the data in the collected zips in other ways, as described in this thread: https://github.com/openaddresses/openaddresses-ops/issues/10

**Comment by orangejulius** [comment]
Since we've started taking a look at this, some things that what we end up building should do:

- [ ] Use the file at http://results.openaddresses.io/state.txt to learn about all the things that can be downloaded
- [ ] run as a separate downloader script like the [whosonfirst downloader](https://github.com/pelias/whosonfirst/blob/master/download_data.js)

**Comment by orangejulius** [comment]
Okay so, until https://github.com/openaddresses/machine/issues/372 is solved, we don't have to worry about any of the md5 stuff from above. Hopefully we can implement it someday.

**Comment by orangejulius** [comment]
Since we last looked at this issue, the OA `collected.zip` file has been changed to avoid any attempts at abbreviation expansion. We've also added a [downloader](https://github.com/pelias/openaddresses/pull/250) that does the right thing in most situations: it uses individual files for partial builds, and `collected.zip` for full planet builds
