### ISSUE TITLE
Missing Hungarian features around Balaton

### ISSUE THREAD

**Issue by migurski** [pelias/pelias#259]
A comment from our support tickets about Hungarian features in Search service:

> Now that you've mentioned whosonfirst, I had a look at the spelunker and tried it with the following strings: 
> - "moszkva" - Moscow in Hungarian, it works 
> - "becs" - English spelling of Bécs, what is Wien in Hungarian, it works 
> so somehow it's clearly not limited to 7 major languages.
> 
> However there are some problems: 
> - "balaton" - biggest lake in Europe, totally missing 
> - "balatongyorok" - English spelling of a village of about 500 in Hungary, totally missing 
> - "balatongyörök" - unicode spelling of the same village: internal server error
> 
> These are all correct in Geonames, so I'm surprised you are using Geonames.

**Comment by missinglink** [comment]
is this ticket related to pelias or spelunker? the spelunker does not use pelias as it's search service.

**Comment by orangejulius** [comment]
Hello, checking in while doing some ticket pruning.

These queries were very clearly run against the spelunker. We very rarely return 500 errors :P (neither does the spelunker anymore, I suspect).

In any case, Pelias actually can be convinced to work for many of these queries. 

* Pelias does not currently support multiple language search, so we can't find Moscow by searching for [Moszkva](http://pelias.github.io/compare/#/v1/search%3Ftext=moszkva). Tracked by https://github.com/pelias/pelias/issues/194
* Likewise we cannot find [Wein](http://pelias.github.io/compare/#/v1/search%3Ftext=Wien) by searching for [becs](http://pelias.github.io/compare/#/v1/search%3Ftext=Becs) or [Bécs](http://pelias.github.io/compare/#/v1/search%3Ftext=B%C3%A9cs
* We do actually import the [Geonames record for Lake Balaton](http://pelias.github.io/compare/#/v1/place%3Fids=geonames:venue:3055597). However, because we don't currently have any special considerations for lakes or other natural features, it's listed as a venue and as a result doesn't rank as highly as the city of Balaton in [searches](http://pelias.github.io/compare/#/v1/search%3Ftext=balaton,%20hungary)
* [balatongyorok](http://pelias.github.io/compare/#/v1/search%3Ftext=balatongyorok) and [balatongyörök](http://pelias.github.io/compare/#/v1/search%3Ftext=balatongy%C3%B6r%C3%B6k) both work great (and identically). In general, Pelias handles diacriticals nicely as long as there aren't underlying encoding issues in the data, and those have mostly gone away with Who's on First(:tada:)

I'm going to close this ticket, but linking to the issues I've linked here that track the underlying issues might be helpful.
