### ISSUE TITLE
Geonames Unicode bug

### ISSUE THREAD

**Issue by migurski** [pelias/pelias#262]
A user has reported problems with Geonames search results encoding:

> There is some bug in Mapzen search when the returned results from  Geonames contain unicode characters.
> 
> For example: https://search.mapzen.com/v1/search?text=g%C3%B6ny%C5%B1&api_key=search-uOD59t8
>
> While name is correct "Gönyű, locality and label has some unicode encoding bug:
>
> locality: "GÃ¶nyÅ±", and 
> label: "Gönyű, GÃ¶nyÅ±, Hungary".
> 
> On geonames.org the query has it with correct encoding: http://api.geonames.org/searchJSON?username=zsero&name=g%C3%B6ny%C5%B1&maxRows=10

([via support](https://hellomapzen.zendesk.com/agent/tickets/450))

**Comment by dianashk** [comment]
@migurski, thanks for reporting this here.

We need to revisit the Geonames importer soon to determine if we can start doing admin-lookup again to get rid of these encoding issues. Currently we do not perform admin-lookup for Geonames.

**Comment by christophlingg** [comment]
same happens to data coming from OSM, see https://search.mapzen.com/v1/reverse?api_key=search-x&point.lat=47.1358&point.lon=9.8022&size=1&layers=address&sources=osm

> locality": "BÃ¼rs",
should be Bürs

**Comment by missinglink** [comment]
hey @christophlingg this is due to the regional information coming from Quattroshapes, there's a long-standing encoding bug there.

the source data (geonames/osm) is actually fine, in the example above `"Gönyű, GÃ¶nyÅ±, Hungary"` the data is sourced from `{geonames}, {quattroshapes}, {quattroshapes}` and it's the locality layer from quattroshapes which has issues ;(

as @dianashk said we are pretty close to solving this issue permanently once we finish our [current development cycle](https://github.com/pelias/pelias/milestones/Who's%20on%20First), which is mostly done, we are just going through all our acceptance tests, fixing things and ensuring we don't break existing functionality.

on a personal note, I just got back from a month in New Zealand! I'll send you an email to catch up.

**Comment by christophlingg** [comment]
I see @missinglink , looking forward for the next release. We are starting to adopt more and more of your services for our internal tools. Works very well.

Nice to see you soon again!

**Comment by orangejulius** [comment]
Fixed in production by whosonfirst!
