### ISSUE TITLE
Autocomplete not working as expected when only house number is specified in query

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#267]
When on Shelter Island, NY the user begins typing `130` the search results are in Canada. The expected results would be located on Shelter Island or closer, given that focus point is provided. 

http://pelias.github.io/compare/#/v1/autocomplete%3Ffocus.point.lat=41.068529&focus.point.lon=-72.339399&text=130

**Comment by missinglink** [comment]
The way it's currently set up is that `focus.point` "adds value" to the score depending on how close it is to the focus point.

We have another concept called `boundary.circle` which could be used as a strict filter to remove distant venues from the results.

This query is very odd, the production server only returns 2x results and they're both in Canada, it's unusual to find that there are not (at least) 10x matching local venues for a short term such as '130'.

This issue may have been fixed in https://github.com/pelias/api/pull/418 as the results now look to be much better localized.

```bash
/v1/autocomplete?focus.point.lat=41.068529&focus.point.lon=-72.339399&text=130

#prod
1)	Redburn No. 130, Saskatchewan, Canada
2)	Waterhen I.r. 130, Saskatchewan, Canada

#dev
 1)	1306, Wawarsing, New York
 2)	13000, Woburn, Massachusetts
 3)	1300 State Street, Bridgeport, Connecticut
 4)	13-09 130th Street, Queens, New York
 5)	13-11 130th Street, Queens, New York
 6)	13-15 130th Street, Queens, New York
 7)	13-17 130th Street, Queens, New York
 8)	13-19 130th Street, Queens, New York
 9)	13-23 130th Street, Queens, New York
10)	13-25 130th Street, Queens, New York
```

... it's still weird that it isn't finding any street addresses in the NY area which have the number '130', that seems to be a bug, possibly relating to which `layers` are being queried?

**Comment by missinglink** [comment]
This issue seems to be significantly improved by recent work.

I'm moving this to 'in review' as I would like to confirm it is fixed when we do a full dev review of the `Autocomplete Improvements` milestone.

**Comment by dianashk** [comment]
Confirmed to be improved with the Autocomplete Improvement changes.
