### ISSUE TITLE
NPM install offline

### ISSUE THREAD

**Issue by curiousc0w** [pelias/pelias#270]
Hi,

I was wondering if there was an easy method to installing dependencies offline? I see that ```package.json``` lists all of the required dependencies for the repo, but if I don't have an internet connection, how could this be possible? Would I have to get the dependencies before hand then ```npm install``` afterwards?

Thank you.

**Comment by orangejulius** [comment]
Hey @curiousc0w,
I haven't looked into this but I feel your pain: being completely blocked from working because of one or two missing packages is frustrating. I don't expect we'll do anything special beyond what NPM itself gives us to solve this, but it does look like there [are ways](https://addyosmani.com/blog/using-npm-offline/) to at least cache some packages to make things slightly better.

**Comment by curiousc0w** [comment]
@orangejulius 

Offline-NPM seems to do a good job as well. This may be a solution for other users as well.

https://www.npmjs.com/package/offline-npm#install-packages-from-npm-cache-offline

**Comment by curiousc0w** [comment]
Here's a little something I've tested out to install npm packages through a local NPM registry using Sinopia.

Feel free to test it out!

https://gist.github.com/curiousc0w/b44d04efcff3fa3602b0

**Comment by missinglink** [comment]
https://github.com/jfhbrook/hoarders (jokes)
