### ISSUE TITLE
Autocomplete geocoder across multiple fields not working as expected

### ISSUE THREAD

**Issue by amnesia7** [pelias/pelias#272]
If I type `manhattan` in the search box https://mapzen.com/projects/search then the top result is `Manhattan, New York, NY` but if I type `manhattan new york` this is not the top result as I would expect or is even listed. 
The only result then is `Manhattan New York Temple, Manhattan, NY`
Even if I press Enter to do a search rather than an autocomplete it still isn't listed in the displayed results.

I was expecting this to be the top result since it is an exact match.

**Comment by riordan** [comment]
Thanks for flagging this issue.

We've seen something like this in the past and suspect its due to the way we're relying on commas as part of our address parser. It thinks "manhattan new york" is the name of a single venue or administrative region, and when it doesn't find it, it doesn't look elsewhere intelligently.

We're replacing our address parsing system in the next few weeks with [Libpostal](https://github.com/openaddresses/libpostal), which should take care of properly interpreting queries like "manhattan new york".

We've got a [lot coming up](https://waffle.io/pelias/pelias?milestone=Autocomplete%20Improvements) to improve address parsing. Let us know what you think. (It'd also be great to hear how this was handled on Photon).

**Comment by riordan** [comment]
(ps I'm marking this as a duplicate since we're tracking the fix over at: #152)

**Comment by hannesj** [comment]
Would the libpostal really also affect autocomplete searches? I was under assumption that it's more for the search-endpoint and batch queries?

**Comment by dianashk** [comment]
@hannesj, you're right, it's a separate issue in autocomplete. We'll investigate further and update here on the findings. Thanks again for letting us know.

**Comment by missinglink** [comment]
@dianashk It appears the issue here is the address parser and there's not much I can do to fix this under the `Autocomplete Improvements` milestone:

```javascript
/v1/autocomplete?text=manhattan, new york, ny

"query": {
  "text": "manhattan, new york, ny",
  "parsed_text": {
    "name": "manhattan",
    "state": "NY",
    "regions": [
      "manhattan",
      "new york"
    ],
    "admin_parts": "new york, ny"
  },
  "size": 10,
  "private": false
}
```

```javascript
/v1/autocomplete?text=manhattan new york

"query": {
  "text": "manhattan new york",
  "size": 10,
  "private": false
}
```

I'm going to move this ticket to the `Address Parsing` milestone instead.

**Comment by missinglink** [comment]
In the interim I would suggest using a comma to delimit the query sections where possible.

**Comment by amnesia7** [comment]
I take it it's not as simple as just stripping any commas from the incoming query text and not having any commas in the text being queried for the autocomplete.

**Comment by missinglink** [comment]
Unfortunately it's not that simple :(

When you search without commas it only returns records where the *name* contains all the tokens you typed, like this:

```
/v1/autocomplete?text=manhattan new york

1)	Manhattan New York Temple, Manhattan, NY, USA
```

when you use commas it knows that the first part is the 'name' and the rest refers to the region/city/etc:

```
/v1/autocomplete?text=manhattan, new york

 1)	Manhattan, New York, NY, USA
 2)	East Manhattan Beach, Manhattan Beach, CA, USA
 3)	Manhattan, Riley County, KS, USA
 4)	City of Manhattan, Manhattan, KS, USA
 5)	Manhattan Beach, Los Angeles County, CA, USA
 6)	Lower Manhattan, Manhattan, NY, USA
 7)	Manhattan Valley, Manhattan, NY, USA
 8)	Manhattan, Will County, IL, USA
 9)	Village of Manhattan, Manhattan, IL, USA
10)	Manhattan, Gallatin County, MT, USA
```

**Comment by amnesia7** [comment]
I see. Unfortunately, in the many times I've used autocompletes for addresses I don't think I have ever typed a comma; I just expect it to sort it out for me. I wouldn't really expect Joe Public to type a comma in either.

**Comment by missinglink** [comment]
I totally agree @amnesia7 that's why I moved this ticket to the `Address Parsing` milestone (which should actually be called `Input Parsing` :) so it can be addressed there.

We are currently in the process of implementing https://github.com/openvenues/libpostal, have a look over at that repo for more info, until that work is complete we are recommending users enter a delimiter where possible.

**Comment by orangejulius** [comment]
Hello, just checking in.

This bad behaviour is still happening, [with](http://pelias.github.io/compare/#/v1/autocomplete%3Ffocus.point.lat=40.744243&focus.point.lon=-73.990342&text=manhattan%20new%20york) or [without](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=manhattan%20new%20york) a focus point in NYC for autocomplete, as well as [with](http://pelias.github.io/compare/#/v1/search%3Ffocus.point.lat=40.744243&focus.point.lon=-73.990342&text=manhattan%20new%20york) or [without](http://pelias.github.io/compare/#/v1/search%3Ftext=manhattan%20new%20york) focus with search.
![screenshot_2016-07-01_17-44-50](https://cloud.githubusercontent.com/assets/111716/16535201/a43bfbee-3fb3-11e6-83f0-7427e0a93c01.png)

Like @missinglink said, this is the sort of query that libpostal should drastically improve, so please track https://github.com/pelias/pelias/issues/152 for progress. Once we've closed #152 we'll check back in here with hopefully good news.

**Comment by amnesia7** [comment]
Hi, just wondered if a solution to this is on the horizon yet?

**Comment by orangejulius** [comment]
Hey @amnesia7,
We are getting a bit closer. On the search side, we have the [libpostal](https://github.com/openvenues/libpostal) address parser integrated in, but there's still more to do. We only use it for queries that have a housenumber or streetname for now. We're working on adding it for more cases, that should include the kind of query you mentioned here. There's no firm ETA but I suspect we'll have the kinks ironed out within a few weeks.

On the autocomplete side, we have a bunch of improvements we want to make, but unfortunately they didn't make it into our [q4 goals](http://pelias.io/quarterly_goals/q4-2016.html) (because there is lots of other really important and awesome stuff in there). However it feels like autocomplete improvements are a leading contender for Q1 2017 projects, and the kind of improvements we have in mind will definitely fix this case.

**Comment by orangejulius** [comment]
This is (finally) fixed as of https://github.com/pelias/api/pull/1287 and the new Pelias parser!! :tada: 
![Screenshot_2019-10-03_15-47-24](https://user-images.githubusercontent.com/111716/66159025-1dba2f00-e5f5-11e9-9cc4-2a91d95ccfcf.png)


[https://pelias.github.io/compare/#/v1/autocomplete%3Ftext=manhattan%20new%20york](https://pelias.github.io/compare/#/v1/autocomplete%3Ftext=manhattan%20new%20york)
