### ISSUE TITLE
Docs say to compare requested_at values to handle async but no such value

### ISSUE THREAD

**Issue by Jason-Abbott** [pelias/pelias#273]
Setup instructions suggest checking a requested_at value to avoid overwriting a displayed response with something stale. I see no such value in the body or header of the API response for search or autocomplete. There's a geocoding.timestamp but in my testing that's legitimately older for newer responses due to caching. Am I missing something?

https://mapzen.com/documentation/search/autocomplete/

**Comment by missinglink** [comment]
hi @Jason-Abbott I wrote that, sorry if it wasn't clear.

the `requested_at` timestamps should be stored on the client, they represent the time your client library *sent* the request to the server. when the response comes back from our service you can then check which one you sent first; and discard it if a later request has already been rendered to your UI.

our service returns a header with the datestamp showing when the record was *generated*, eg. `Date:Fri, 04 Mar 2016 08:46:10 GMT`.

it's a little confusing, but that server datestamp is not sufficient to ensure your UI is rendered in the correct order, like in this example (I've exaggerated the times for clarity):

```
1. query "a" which takes 5 seconds to generate
2. query "am" which takes 1 second to generate
3. query "ame" which is returned from the edge cache in 0.05s
```

we have 3 different autocomplete queries sent to the server in quick succession, we send 1. then 2. then 3. and they come back in the order 3. then 2. then 1.

if you aren't storing some sort of `requested_at` timestamp on the client your UI would show the results for "ame" for ~1s; "am" for ~4s and finally it would show the results for "a".

if you check the `requested_at` timestamp as the responses for 2. and 3. come back from the server, you can look at them and say "I've already dealt with an older requests and rendered the UI, so I'll just ignore these other 2"

hope that makes sense, let me know if you need more info.

**Comment by Jason-Abbott** [comment]
Thank you for that explanation. The API response does contain the text that was searched. Can you think of a downside to ignoring any response for search text that differs from what's currently in the search box?

**Comment by missinglink** [comment]
I hadn't thought of doing it like that, and now you mention it, it seems kind of obvious and much simpler to implement.

If you waited for the last request to return it would result in a tiny bit more lag, generally the service is so fast I doubt the user would notice a thing, they also wouldn't see any 'flicker' if the responses got rendered quickly in succession, which is nice.

The only reason I can think of for not just comparing `geocoding.query.text` with your UI textbox is if you use `?text=` along with other query parameters such as `?focus.point=`.

If the user drags the map, they would be searching the same input text with a different `focus.point` each request and the UI would render the *last response to return* rather than the *last request that was sent*.

It's more important for `/v1/search` and `/v1/reverse` than `/v1/autocomplete` because autocomplete intentionally has a minimal API and so there's not many query vars you can specify.

We are hoping to expand the functionality of `/v1/autocomplete` soon based on user feedback, so we will likely turn on support for things like `?layers=`, `?source=`, `?categories=` this year, this will make things a little more complicated and *could* effect how your client lib behaves.

You could also consider hashing the `geocoding.query.text` block and then comparing the hashes, it has some internal properties in there like `"private": false` which might make that tricky.

The `requested_at` solution is more complex to implement but I think it's more robust, it really depends on which parts of the API you use and how happy you are to change it when the APIs add new functionality.

I've also asked @louh for some input, he wrote the leaflet client and can probably offer some insights.

**Comment by louh** [comment]
Similar to the situations where input text could be the same, but query parameters differ, is when a user enters an input and then presses Enter, switching from `/autocomplete` to `/search`. The input is the same but the endpoints are different.

Now you have to resolve the ambiguity of two responses from different endpoints in case they come back in a different order. You could presumably assume that all responses from `/search` are newer than responses from `/autocomplete`, but that's one additional check to make. Combined with other checks in query parameters it might just be easier to record a timestamp client side.

There is one edge case in the Leaflet plugin where we do need to check the query text. Imagine that you delete characters from the input box one at a time but very quickly. Each time the input text changes, it makes a request to `/autocomplete`, which are also throttled to avoid exceeding the API rate limits. It is therefore possible to have a completely blank input box (which makes no request) and a response from `/autocomplete` that arrives late enough, but since there's no new request made to override this one, it renders this last response. We fixed this by checking to make sure that the input box is not blank when a response is received.

So what if each response checks both the timestamp _and_ the query text? Would that be even more robust? I'm trying to imagine how this affects the experience with throttling involved. Currently, results are displayed as fast as the rate limits allow even if it doesn't keep up with a very fast typer. If we were throwing away requests that don't match the current input, does this change the experience for fast typers?

**Comment by Jason-Abbott** [comment]
Great feedback, thanks. It makes complete sense that comparing text won't do if other parameters might change. In our case -- a small autocomplete -- text is the only variable and full search is resolved by a different internal endpoint so I think we avoid the caveats. I will annotate our code with these notes. I appreciate your thorough feedback.

**Comment by Jason-Abbott** [comment]
To your last point @louh, most auto-completers delay the lookup call after keyup (and cancel the prior lookup on next keyup) so fast typers don't get a result until they pause anyway. We're testing the UX a bit here.

**Comment by louh** [comment]
That's good to know! What auto-completer(s) have you tested? And please let
us know what you find out about your results.
