### ISSUE TITLE
standardize logging

### ISSUE THREAD

**Issue by sevko** [pelias/pelias#28]
We should discuss a uniform logging solution:

  1. **~~what logger to use~~**: we've basically already settled on using [winston](https://www.npmjs.com/package/winston), so we'll stick with that unless there's a good reason not to.
  2. **default logger configuration**: what default settings do we want to instantiate our logger with? I've been using the following `openaddresses` and `dbclient`:

  ```
  winston.remove( winston.transports.Console );
  winston.add( winston.transports.Console, {
    timestamp: true,
    colorize: true,
    level: 'verbose'
  });
  ```

  Is it worth spinning up a Pelias package containing our logger preferences, so that we can simply `require( 'pelias-logger' )` and not duplicate them everywhere?

  3. **environment-specific logger configuration**: we'll presumably want to be able to tweak the defaults from `pelias-config`.

cc @dianashk , @hkrishna , @missinglink

**Comment by dianashk** [comment]
1. Winston is good

2.1 We should consider writing to a rotating log file (out_timestamp.log, err_timestamp.log) and not rely just on stdout/stderr to be captured at execution. 

2.2 Since we are using logstash, it would also be great to write to that via UDP (there are npm modules that create a new winston transport for that sort of thing). Having a log analysis tool is extremely handy if you do a good job standardizing your log output.

2.3 Which brings us to the question of what should be the standard log statement format. Need to investigate logstash a little further to see how they recommend styling your logs. We should agree on key/value pairs looking like key=value so logstash can easily extract those into meaningful stats.

2.4 We definitely should spin up a pelias-logger module and abstract away the details of dependencies to winston, etc. We want to be able to swap that out if need be in the future. All other pelias modules should be able to just say 

/**
* We can discuss the tradeoffs of making the Logger class a singleton or creating a new instance each time.
*/
var logger = new Logger( <optional config> );
logger.info(...);
logger.debug(...);
...etc...

3. We don't want to couple pelias-logger to pelias-config directly. Other modules that use pelias-config can grab the necessary parameters from the config and pass them to logger. (this is probably what you meant anyway, so just clarifying) But it does make sense to store the logger config in pelias-config.

**Comment by sevko** [comment]
re: 2.*, excellent points, but I'm not sure whether we're planning on storing these logs anywhere yet. At least, that's what I remember @heffergm saying.

re: 3, yep, we'll need to figure out whether injecting loggers is preferable. I'm not on the same page about passing settings from `config` to the logger instead of having it read them directly, though. Can you give an example of where that would be better?

**Comment by dianashk** [comment]
re: 3, I generally lean towards decoupling things as much as possible. You should have the flexibility of using the pelias-logger with whatever config you want to define (dependency injection style). If you want the logger module to need less configuration we can define a few canned options as part of the module, like 'dev'/'prod' and default to one of them if no config is specified upon creation.

**Comment by sevko** [comment]
`pelias-config` itself is configurable, though, so configuring the logger from there seems like functionally the same thing as letting users pass in config objects to the logger constructor, but with the benefit that you keep all your Pelias settings in one place. Might be missing something, though.

**Comment by hkrishna** [comment]
I like the idea of pelias-logger being a separate package and all it does is logging and has no knowledge of pelias-config.

**Comment by dianashk** [comment]
It seems to me that pelias-config is the sort of thing you use for executable modules. Since pelias-logger is a module that will never be executed on its own and will always be instantiated in the client code, we should just provide config options at creation time. This will make testing easier as well, don't want to have to mock out files to test various config options coming through properly. Decouple all the things!!!

**Comment by sevko** [comment]
What if you want to configure the logger from outside the executable (if you're a devops person, or whatever), to set verbosity levels and stat reporting frequency? Wouldn't the logger creator end up reading the config for those values anyway? Not having to mock it for testing is a good point, but since tests won't be crucial for the logger I think I'd rather opt for ease of use. That being said, this one's your call -- I'm probably overthinking it.

We'll need to figure out sensible defaults and drop them into a `pelias-logger` package. Let's chat when @missinglink 's back?

**Comment by dianashk** [comment]
So the client of pelias-logger will still probably use pelias-config to define the logging options. But it's up to the client how to expose those to the outside world, not up to the low-level module with a single job.

**Comment by sevko** [comment]
I'm thinking that instantiating a new logger per package (or file) is the right way to go, since that seems to be the best practice in other langs/libs.

```
var logger = new require('pelias-logger')(__filename);
```

or

```
var logger = new require('pelias-logger')('my-package-name');
```

**Comment by sevko** [comment]
Shipped: [pelias-logger](https://github.com/pelias/logger).
