### ISSUE TITLE
Address geocoding problems in Florida

### ISSUE THREAD

**Issue by b-may** [pelias/pelias#285]
We have recently started using Mapzen search to power address geocoding in our online mapping application and we are finding several issues I'd like to report. Our focus is on Florida. I'd like to help with sending examples of address geocoding problems and help add to OpenAddresses to improve the quality of the data. Note that in the current implementation, we are not using autocomplete, rather sending a request for the top match. Also all results are limited to a box containing Florida. Part of the reason is many people using our system copy/paste addresses in from another source. So here goes a few to start with:

[100 albany ave, stuart, fl](http://pelias.github.io/compare/#/v1/search%3Ftext=100%20albany%20ave,%20stuart,%20fl) -- result is in waycross, ga -- its a real address (a condo)
[100 sw albany ave, stuart, fl](http://pelias.github.io/compare/#/v1/search%3Ftext=100%20sw%20albany%20ave,%20stuart,%20fl) -- result is random 100 house number in stuart
[200 sw albany ave, stuart, fl ](http://pelias.github.io/compare/#/v1/search%3Ftext=200%20sw%20albany%20ave,%20stuart,%20fl)-- OK -- real address next door

[100 n main st gainesville fl ](http://pelias.github.io/compare/#/v1/search%3Ftext=100%20n%20main%20st%20gainesville%20fl)-- result is tampa, fl -- 
[113 n main st gainesville fl](http://pelias.github.io/compare/#/v1/search%3Ftext=113%20n%20main%20st%20gainesville%20fl) -- OK -- 

Note that 100 n main doesn't actually exist. It appears that if you get the house number wrong, the geocoder gets very confused. Have seen that multiple times.

523 cherry oak way stuart -- result is a random address containing 523 in stuart, not on cherry oak way, 523 is not a real house number on cherry oak way
532 cherry oak way stuart -- OK -- its a real house number

Note again issue with using non-existent house number. I would expect the geocoder should drop the street number if it can't find it on the street, and use the mid-point of the street instead.

1046 us highway 92 east, lakeland fl -- result is in georgia
1046 highway 92 east, lakeland fl -- OK -- note that "us" was dropped. But it is a US Highway.

**Comment by dianashk** [comment]
Hey @b-may, thank you for taking the time to write this up. It's **extremely** helpful for us to have these test cases as we do our best to improve result quality.

We'll check these out in more detail. In the meantime, it would be great if you could also share the bounding box you're using for these queries, as well as any other filters you're applying, such as `sources` or `layers`. We're assuming you're directing your requests to the `/search` endpoint, since you said you aren't using `/autocomplete`. Just want to have all the facts so we can effectively reproduce these results locally.

Thanks again! :wave:

**Comment by b-may** [comment]
OK, great. Yes, I'm using /search. Here are the params:

`http://search.mapzen.com/v1/search?api_key=<mykey>&text=<myaddress>&boundary.rect.min_lat=24&boundary.rect.min_lon=-88&boundary.rect.max_lat=31.5&boundary.rect.max_lon=-79&size=1`

No using any params like layers or sources.

Should I open new issues for each batch of issues? Or add on to this thread?

And BTW I think what you guys are doing absolutely rocks!

**Comment by missinglink** [comment]
Investigation notes:

regarding the openaddresses data:
- http://results.openaddresses.io/
- https://github.com/openaddresses/openaddresses/blob/b4b826ee8feb6e9130234ea5d8b45b92dc441461/sources/us/fl/city_of_lakeland.json

I downloaded http://s3.amazonaws.com/data.openaddresses.io/runs/68472/us/fl/city_of_lakeland.zip and tried to `grep -i "albany" city_of_lakeland.csv` but found no results.

I'm not familiar with the geography (i'm a kiwi), I'm sure there are some records in there in a different file, maybe you can help figure out which one? 

**100 albany avenue, florida**

This is not found in our system, it's likely due to the data being missing, see next address:

**200 albany avenue, florida**

This is found in pelias:

```javascript
{
  "type": "Feature",
  "properties": {
    "id": "2d698c8c74484096a80758033b694967",
    "gid": "oa:address:2d698c8c74484096a80758033b694967",
    "layer": "address",
    "source": "oa",
    "name": "200 South Albany Avenue",
    "housenumber": "200",
    "street": "South Albany Avenue",
    "country_a": "USA",
    "country": "United States",
    "region": "Florida",
    "region_a": "FL",
    "county": "Martin County",
    "locality": "Stuart",
    "neighbourhood": "Watermark Marina of Palm City",
    "confidence": 0.848,
    "label": "200 South Albany Avenue, Stuart, FL"
  },
  "geometry": {
    "type": "Point",
    "coordinates": [
      -80.256743,
      27.199085
    ]
  }
}
```

... although the `/v1/autocomplete` endpoint does a much better job of finding it than `/v1/search` so this is certainly a search logic bug which needs to be addressed.

it is most likely to do with how the directional synonyms are handled (eg. 'sw' -> 'southwest'), a bunch of work has been done in this area for autocomplete but it appears search is lagging behind.

---

most other geocoding systems use a process called 'interpolation' to guess the missing address points, eg if we know where number 1 is and number 100 is then we can guess 50 is in the middle.

Pelias currently only returns addresses it is absolutely sure exist, interpolation is difficult for non-linear geometries (think circular and wavy road segments) and in countries like Germany where some streets have 'zigzag' numbering and other streets have 'up-and-down' numbering.

This feature will be coming this year but not until it can be done right.

---

In the interim I would suggest a couple things:
- have a look over the openaddresses data for Florida and see if there's something we can do
- try to 'fully' specify your queries where possible:
 - expand abbreviations: 'n' -> 'northwest', or remove them completely
 - add commas between the query parts: 'main st gainesville fl' -> 'main street, gainesville, florida'

This will generally give better results until we improve the input parser (Q1 2016)

Thanks for the feedback, glad you like it!

**Comment by b-may** [comment]
OK, thanks for all the info. 

The Albany Ave example is in Stuart, FL - https://www.openstreetmap.org/#map=18/27.19907/-80.25606

Interesting about the directionals. Pelias /search returns the correct address for `200 s albany avenue, stuart, fl` or `200 sw albany avenue, stuart, fl` or `200 albany avenue, stuart, fl`. So in this case seems like the directional processing is OK. 

Its when you feed pelias a house number it doesn't know about where things go wrong, sometimes really wrong depending on the directionals you give it. And I am getting different results from autocomplete vs. search. The results I am reporting are coming from /search.

So for a house number pelias doesn't know about: 

`100 south albany avenue, stuart, fl` returns `42 south albany avenue, stuart, fl`, which is fine. 

`100 southwest albany ave, stuart, fl` puts you about 400 ft southeast on a parcel with a site address of `100 SW DIXIE HWY 101-102, stuart, FL`, which seems odd.

`100 albany avenue, stuart, fl` returns `100 Albany Avenue, Waycross, GA`, which is bad. 

If you try typing into autocomplete `100 south albany avenue, stuart, fl`, it doesn't find anything.

---

Being a GIS guy, I understand the interpolation issue. At least in this case, pelias is choosing a an address numerically close on the same street if it matches the directional and other address components.

---
Last night I started to take a look at the openaddress sources and report some possible improvements where I could. I will keep working on that. 

FYI, I have all parcels in Florida and process either raw taxroll data from Property Appraisers or the taxroll data from FDOR for all counties on a regular basis using automated scripts. I'm also collecting point address data like openaddresses does. The point is its easy for me to check address issues in Florida and potentially help with automated data cleanup, etc.

---

I have noticed adding commas helps and in future reporting I will stick to batching reports by county. Thanks!

**Comment by trescube** [comment]
@b-may The OpenAddresses coverage for Florida is only about 20 counties (with some cities) out of the 66.  If the parcel data you have is statewide (or at least some additional counties) and available for sharing, it would go a long way to plugging some of the coverage holes in Florida in OpenAddresses.

**Comment by b-may** [comment]
OK, yes, I can work on that and provide missing data. Florida has very open public records laws, so all data is public domain by default except when limited by statute. I would be happy to contribute public data that I had to paid for as well, usually its a small token amount like $15 to $50. Its just a PITA and slows down data transfer rates. I'll work on that county by county in the OpenAddresses repo starting from big to small by population.

**Comment by trescube** [comment]
Excellent, thanks!  There's nothing special about counties in OpenAddresses, it just seems to be the default for GIS departments. If there's one giant file for the entire state or groups of counties, those are fine as sources, too.

**Comment by b-may** [comment]
@trescube, @missinglink After some testing, I think the OpenAddresses points used with Pelias in Florida are not the county based address points where available, rather they are from a statewide version of addresses based on parcel centroids (the loveland address data). The exception is Miami-Dade. The statewide version does not include Miami-Dade and OpenAddresses has the Miami-Dade address points data. 

Using data that includes zip codes also improves searching. When pelias is using the county address points with zip codes, a full address search in Miami-Dade with zip code works properly, e.g. `7505 W 14TH CT Hialeah FL 33014`. In addition, a search with no city and zip code also works, e.g. `7505 W 14TH CT 33014`. The loveland data does not include zip codes.
![address_example_miami_dade_fl](https://cloud.githubusercontent.com/assets/17534713/14034859/cb987ce8-f1fd-11e5-8fe2-5c5aee66399a.png)

The Orlando example below shows that the loveland data is being used instead of the Orange county address points data. A search for `3759 PERCIVAL RD ORLANDO Fl 32826` resolves to `Montessori School East Orlando at 2514 PERCIVAL RD ORLANDO Fl 32826`. A search for `3759 PERCIVAL RD ORLANDO Fl` resolves to the parcel centroid instead of the Orange county address location.
![address_example_orlando_fl](https://cloud.githubusercontent.com/assets/17534713/14034864/db65577c-f1fd-11e5-91c8-3e8c04c5605b.png)

So, to recap -- the loveland data does not include zip codes, and when zip codes are missing in the address data, searches that include zip codes provide strange results. And the loveland data is overriding county based address points that also include zip codes.

is there a way to prioritize the openaddress data, i.e. not use the loveland data when there is county data address points available?

Another solution is replace the loveland data with a data set that fills in the gaps where county data address point does not exist, but does not overlap counties with address point data. In addition, add zip codes to the "in-fill" data set, because having zip codes dramatically improves the search results when using zip codes in the search. 

So, my plan is to generate an "in-fill" data set that uses county parcel centroids matched to site addresses from the raw county taxroll data where I have that, and otherwise fall back to the FDOR based parcel data (which comes from the counties once a year). Most of the in-fill data set should have zip codes, too. I'll open an issue on the OpenAddresses repo explaining this part as well.

Does what I found and the data proposal sound about right?

**Comment by b-may** [comment]
I opened an issue in OpenAddresses to replace the loveland data with a new version of florida "in-fill" parcel centroid based addresses I created last night called the mapwise version. https://github.com/openaddresses/openaddresses/issues/1633

**Comment by trescube** [comment]
Excellent, thanks for your contributions!

**Comment by orangejulius** [comment]
All the addresses linked in the original issue now return address results that look correct! I suspect a couple things have happened in the 3 years since this issue was created:

- Lots of new address data has become available including a statewide address dataset for Florida
- We have improved our directional handling with https://github.com/pelias/schema/pull/310 and other work
- The new pelias parser introduced in https://github.com/pelias/api/pull/1287 now handles _most_ queries without need for a comma

### [100 albany ave, stuart, fl](http://pelias.github.io/compare/#/v1/search%3Ftext=100%20albany%20ave,%20stuart,%20fl) 
![Screenshot_2019-10-03_16-19-41](https://user-images.githubusercontent.com/111716/66161127-a3d87480-e5f9-11e9-96b4-5866fa436a59.png)

### [100 sw albany ave, stuart, fl](http://pelias.github.io/compare/#/v1/search%3Ftext=100%20sw%20albany%20ave,%20stuart,%20fl) 
![Screenshot_2019-10-03_16-20-13](https://user-images.githubusercontent.com/111716/66161165-b357bd80-e5f9-11e9-8f83-be901586221d.png)

### [200 sw albany ave, stuart, fl ](http://pelias.github.io/compare/#/v1/search%3Ftext=200%20sw%20albany%20ave,%20stuart,%20fl)
![Screenshot_2019-10-03_16-20-44](https://user-images.githubusercontent.com/111716/66161214-c79bba80-e5f9-11e9-80ed-a6249ea073b5.png)


### [100 n main st gainesville fl ](http://pelias.github.io/compare/#/v1/search%3Ftext=100%20n%20main%20st%20gainesville%20fl)
![Screenshot_2019-10-03_16-21-28](https://user-images.githubusercontent.com/111716/66161252-df733e80-e5f9-11e9-9f26-5363be91c3c7.png)


### [113 n main st gainesville fl](http://pelias.github.io/compare/#/v1/search%3Ftext=113%20n%20main%20st%20gainesville%20fl)
![Screenshot_2019-10-03_16-21-47](https://user-images.githubusercontent.com/111716/66161272-ebf79700-e5f9-11e9-90b8-6136c06f7c2b.png)
