### ISSUE TITLE
Geocoding problem in Polk County, FL

### ISSUE THREAD

**Issue by b-may** [pelias/pelias#286]
Input to /search is `440 S Combee Rd, Lakeland, FL 33801`
Result is `Mitchells Coffeehouse, Lakeland, FL` which is on the parcel border of 206 E PINE ST, Lakeland, FL. This is about 3 miles west of the correct location.

Remove the zip code and it locates it properly, e.g. `440 S Combee Rd, Lakeland, FL`. I tried putting a comma before the zip code and that doesn't help.

I've noticed that pelias doesn't seem to like zip codes. Why is that?

I just removed this POI from OSM, which was a duplicate of another Mitchells Coffehouse POI that is more accurately located and addressed. How long does it take for pelias to get an updated copy of OSM? Is pelias using minutely, hourly, daily diffs?

**Comment by dianashk** [comment]
Hey @b-may, thanks for flagging this.

We do indeed have some issues with zipcodes at the moment. Reason being that we don't currently have a data source for the postalcode polygons, and therefore can't do our own point-in-polygon lookup for each record, as we do for all other administrative layers. The only postalcodes you will find in the records are those that were provided by the original data source. Unfortunately the coverage isn't great, so sometimes a record looks like a better linguistic match when it's missing a postalcode. This means we can't discount records for not having them, so they end up higher in the results.
We are actively looking for an open postalcode dataset and as soon as one becomes available we'll start being best of friends :heart: with postalcodes.

As for the build frequency, we do weekly builds. Typically the latest and greatest is rolled out by Monday mornings (EST).

**Comment by b-may** [comment]
Hi @dianashk . I did further research on this here : https://github.com/pelias/pelias/issues/285
See the comment 8 days ago.

I submitted a parcel centroid based address file for FL to OpenAddresses that includes zip codes, but I am waiting for the next step on getting it accepted. This data also removes overlap with counties in FL that already have (mostly) rooftop point addresses with zip codes. https://github.com/openaddresses/openaddresses/issues/1633

I am pretty sure the "loveland" version of Florida addresses without zip codes is over-riding counties with point addresses in your data import process.

Also, what about the US Census Zip Codes? https://www.census.gov/geo/reference/zctas.html

**Comment by orangejulius** [comment]
Hey @b-may,
Thanks to your dataset that has made it's way into OpenAddresses, this query now works basically the same both [with](http://pelias.github.io/compare/#/v1/search%3Ftext=440%20S%20Combee%20Rd,%20Lakeland,%20FL%2033801) or [without](http://pelias.github.io/compare/#/v1/search%3Ftext=440%20S%20Combee%20Rd,%20Lakeland,%20FL) the postal code! :tada: 
![screenshot_2016-07-01_18-00-35](https://cloud.githubusercontent.com/assets/111716/16535501/d2fc31fe-3fb5-11e6-9166-377db5105aaa.png)

However, the city that comes back for the query is Crystal Lake, not Lakeland. Is that right, or is there an issue with our administrative data?

**Comment by orangejulius** [comment]
Here are links to our geometries for [Crystal Lake](https://whosonfirst.mapzen.com/spelunker/id/85935703/#13/28.0331/-81.9080) and [Lakeland](https://whosonfirst.mapzen.com/spelunker/id/85933319/#13/28.0380/-81.9366)

**Comment by b-may** [comment]
Hi @orangejulius,

Awesome! 

The address is outside Lakeland city limits, however the postal city address is Lakeland.

`https://tools.usps.com/go/ZipLookupResultsAction!input.action?resultMode=2&companyName=&address1=&address2=&city=&state=Select&urbanCode=&postalCode=33801&zip=`

You guys are using census places data for city names, right? So if the address is outside the city limits, then you pick the designated places polygon name. Whereas most site addresses will use the USPS city name associated with a zip code. There can also be alternative city names by zip code.

I haven't done a thorough analysis, but I believe the USPS city name is in OA address records in Polk (and most of Florida). If its there, why not use that? I think its a bit confusing when someone has an address with a common city name like Lakeland, but Pelias returns a different city name that only makes sense to census data users.

**Comment by trescube** [comment]
@b-may We discard all admin area info (city, county, state, etc) from the source OA data except for postal code and resolve that those parts instead from our PiP service based on [Who's on First](https://whosonfirst.mapzen.com/).  According to our PiP service, the lat/lon for `440 South Combee Road` is 28.0397303,-81.9073329 which we list the city as Crystal Lake.  We do this mainly because OA data (and OSM) is normally spotty so we normalize on our administrative areas.  Most sources that OA pulls from don't even provide anything other than a lat/lon, house number, and street.  

Interestingly, my research into this has exposed an error in the [city of Lakeland, FL](https://github.com/openaddresses/openaddresses/blob/master/sources/us/fl/city_of_lakeland.json) data in OA.  The conform says that street field is composed of the following fields in order:  `PREFIX`, `STREETNAME`, `TYPE`, `SUFFIX`.  This appears to be incorrect as the `PREFIX` field is never used and `SUFFIX` is overloaded to mean either prefix or suffix with no way to differentiate.  The result of this is that the Loveland, FL source has:

```-81.9073329,28.0397303,440,South Combee Road,,lakeland,polk,fl,,,```

whereas the city of Lakeland, FL source has:

```-81.9076512,28.0397833,440,Combee Road South,,,,,33801,,```

Note the directional switch, google maps has it as `South Combee Road`.  

There are other fields that can be used which I'll update the source to.

**Comment by trescube** [comment]
https://github.com/openaddresses/openaddresses/pull/1799

**Comment by orangejulius** [comment]
This particular query now returns correct results after enabling the US postal cities support added in https://github.com/pelias/wof-admin-lookup/pull/232.

I've added it as an example case in https://github.com/pelias/pelias/issues/396#issuecomment-477736197, so we can now close this issue as a duplicate. :tada:
