### ISSUE TITLE
Agree on a consistent unit testing framework to use in all pelias repos

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#29]
As agreed upon in a recent chat, it is important to agree on a single framework to be used for unit testing across the pelias organization. This will ensure consistency and cohesion.
We are currently predominantly using tape, but there is no strong preference for tape. I prefer mocha. I've compiled a short list of my reasons for liking it, and an even shorter list of my reasons for not liking it. Also, I like using mocha with `should`, which reads a lot like natural language and has extensive assertions built in. 

Pros:

1. `skip`/`only` are great tools during development
    * `skip` makes the tests show up as pending so you don’t forget to come back to them. you can skip entire suites or single tests.
 ```
describe.skip('some test', function () { ... });
describe('another test', function () {
  it.skip('should work', function (done) { ... });
});
```
   * you can write unimplemented tests, which are effective place holders
 ```
describe('another test', function () {
  it('should work in the future');
});
```
    * `only` lets you run a single test while debugging an issue, no need to comment out all other test cases
1. `before`/`beforeEach`/`after`/`afterEach` can be nested at various levels
1. can run tests matching some regex pattern , or inverse of regex match results
1. lots of built-in/plug-in reporters
1. easy hookup to coverage tools (if we decide to go that route)
1. very well supported and embraced by the community. a lot of open source projects use it so contributors would feel comfortable adding tests.  searching github:
  * dependencies mocha extension:.json: 136,726 
  * dependencies tape  extension:.json: 10,808

Cons:
 1. have to add globals to .jshintrc because there is some magic that happens with both mocha and should
 1. need to rewrite existing tests for consistency

@missinglink @hkrishna @sevko opinions please

**Comment by sevko** [comment]
I think mocha's obviously superior to tape (more mature, feature-packed, etc), and it would've probably been a good idea to use it since the beginning. That said, I haven't found myself needing anything beyond the minimalist features that tape offers.. wondering whether that's the case for @hkrishna and @missinglink .

The first downside is a non-issue. The second will definitely result in lost time, but hopefully not too much if we switch individual packages over to the new framework while we work on them, instead of sitting down and migrating *everything* at once.

**Comment by dianashk** [comment]
Using tape going forward. Should change mocha tests to tape for consistency.

**Comment by sevko** [comment]
Is there anything else that needs to be discussed/done for this?
