### ISSUE TITLE
Hillside, Santa Clara

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#294]
http://pelias.github.io/compare/#/v1/search%3Flayers=neighbourhood&text=Hillside,%20Santa%20Clara

**Comment by orangejulius** [comment]
I looked into this, and while I was able to figure out what parts of the score are contributing to the desired result ranking low, I'm not sure how we should fix it.

All the name.default and name.phrase matching is the same, which is good. The top results do have population and/or popularity values, but nothing extreme. The problem is that while "Santa Clara" in the parsed query does match "Santa Clara" the county, it's only a tiny boost, for a total of 0.6, while even small populations and popularities add 6-8 to the score.

Here's the relevant part of the explain output, where it's scoring for matching "santa" in "santa clara county". You can see the start of matching "clara" as well below.
![santa_clara_score](https://cloud.githubusercontent.com/assets/111716/14093246/7abe6aba-f51a-11e5-80d9-a91d11f0857d.png)

The full query and explain output is also attached.

[santaclaraquery.txt](https://github.com/pelias/pelias/files/192612/santaclaraquery.txt)
[santaclaraexplain.txt](https://github.com/pelias/pelias/files/192611/santaclaraexplain.txt)

**Comment by orangejulius** [comment]
One thing to note is that the queryNorm is massively reducing the score from this match (see the queryNorm value, which is very low, and how it's multipled with the inverse document frequency, lowering the score quite a bit.

The [documentation](https://www.elastic.co/guide/en/elasticsearch/guide/current/practical-scoring-function.html#query-norm) does not give a ton of info about the purpose of the queryNorm, but there are several fairly [hostile](https://github.com/elastic/elasticsearch/issues/10037) [responses](https://github.com/elastic/elasticsearch/issues/3058) from Elastic employees whenever people ask about disabling the queryNorm

**Comment by dianashk** [comment]
Let's keep this open until we can verify the fix on prod.

**Comment by orangejulius** [comment]
The expected result now comes up 2nd on prod (Note that Santa Clara is no longer in the labels because it's the county name)

![hillside](https://cloud.githubusercontent.com/assets/111716/15333187/afe2a524-1c36-11e6-9440-9cd35e5bd30a.png)

**Comment by trescube** [comment]
Fixed in pelias/api#850
