### ISSUE TITLE
Points in London have "City and County of the City of London" for region

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#297]
Searching for [v1/reverse?point.lat=51.515049&point.lon=-0.093229](http://pelias.github.io/compare/#/v1/reverse%3Fpoint.lat=51.515049&point.lon=-0.093229) results in items with City and County of the City of London for a region, which before we considered a bad thing. Is it really a bad thing or do we know enough now to consider it ok?

_see related closed issue https://github.com/pelias/quattroshapes/issues/13_

**Comment by orangejulius** [comment]
At least as far as labels go, this query looks great now, which is really helpful.
![screenshot_2016-07-01_17-27-49](https://cloud.githubusercontent.com/assets/111716/16534907/5c5b8de6-3fb1-11e6-9e49-500acf296655.png)

We do return the _actual_ City and County of the City of London record for that query, but that's ok, and easily fixed by [moving the query point a bit](http://pelias.github.io/compare/#/v1/reverse%3Fpoint.lat=51.512049&point.lon=-0.093229). It feels like while some parts of our response may not be technically correct (and I think we've come to the conclusion that no one at Mapzen knows enough about the technicalities of the administrative structure of London to say what _is_ right), we are returning results that are good enough and are what people would actually want.

So we could leave this test until something gets sorted out in WOF, delete it, or change it so it passes. But I don't think there's any changes to be made in Pelias here.

**Comment by dianashk** [comment]
What should we do about this one?

**Comment by dianashk** [comment]
Labels look the same as a year ago and we no longer think that region name is problematic. Closing.
