### ISSUE TITLE
Labels for Paris, France and Madrid, Spain are odd

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#299]
`Madrid, Spain` comes up as `Madrid, Comunidad De Madrid, Spain`
`Paris, France` comes up as `Paris, Paris-4E-Arrondissement, France`

**Comment by trescube** [comment]
The introduction the `macrocounty` and `macroregion` fields in combination with much more info now available from WOF, the fragility of label generation in it's current form is becoming more evident and that's the culprit here.  In the Paris case, WOF just has more info available than QS did, so the county value is slipping in.  In the Madrid case, the macrocounty is included.  Rather than special case everything, I recommend we revisit label generation to conform to standards.  A few weeks ago, @riordan pointed me to a Google guide on how addresses should be formatted in different countries:  https://github.com/googlei18n/libaddressinput/wiki/AddressValidationMetadata

Each ISO has a configuration file containing a `fmt` field that describes how things should be displayed in that country.  For example, FR has:

`%O%n%N%n%A%n%Z %C %X`

The letters correspond to:

N – Name
O – Organisation
A – Street Address Line(s)
C – City or Locality
Z – Zip or postal code
X – Sorting code

We won't always have each field and we'll want to append country to the end.  For example, Strasbourg, FR currently has the label `Strasbourg, Alsace, France`.  The `Alsace` part doesn't mean much, doesn't conform to the Google addressing format, and isn't the label displayed by Google maps (from a random point clicked on the map):  

```60 Rue de la Plaine des Bouchers
67100 Strasbourg, France```

We'll have to take display rules for neighbourhood results as the formats don't reference them.  Additionally, we don't use newlines in our labels (nor is there a place for them) so we'll have to discuss how to deal with that.

**Comment by trescube** [comment]
Replace newlines with commas for now, future plan is to add mailing label which is an array.
