### ISSUE TITLE
Chelsea, NY doesn't show up in search for "chelsea"

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#300]
Searching for [`v1/search?text=chelsea&layers=coarse`](http://pelias.github.io/compare/#/v1/search%3Flayers=coarse&text=chelsea) returns a list of Chelsea places, but no longer included the one in Manhattan. (It shows up 12th, if size=20)

**Comment by trescube** [comment]
Julian and I spent some time looking at this.  Chelsea NYC doesn't have popularity but no population whereas Chelsea, London has both.   In fact, results 1-11 all have population and some have popularity (especially the top results).   Chelsea NYC is the first result that doesn't have population.  It seems that our scoring punishes neighborhoods that don't have a value in `gn:population`.  One thing we could try is, instead of assigning a default of 1 when there is no population, assign population the value of the popularity field.  I poked around in the WOF data, and while the NYC don't seem to have `gn:population` values, they do have `zs:pop10` values that we could use when the former doesn't exist.

**Comment by trescube** [comment]
I talked to the data team about this.   `zs:pop10` is US census data from zetashapes and in some cases may be more accurate than `gn:population`.   Most importantly, it's a valid source of population data.  I'll open a ticket on pelias/whosonfirst to get it into place.
