### ISSUE TITLE
Make admin hierarchy consistent between data sources

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#302]
Geonames currently has a name and the admin property for the place set to the same thing, e.g. 

```
"layer":"region",
"name":"New York",
"parent":{
  "region":"New York",
  ...
}
```

However, WOF records don't do that. We should probably remove the duplicate data from the Geonames records and update the label generation logic to fix it.

**Comment by dianashk** [comment]
Looks like we are consistent across datasets. We duplicate the layer name and record name in all coarse layers. Closing this ticket until someone says they don't like the duplication.

**Comment by larskendall** [comment]
Hey guys, we were hoping that pelias had parent relationships between the various types, but we only found them on localities, and they point to themselves for some reason. Is the parent field supposed to point to the parent type? For example, "Washington DC" would have a parent that's "United States", and similarly a locality would point to a state. Does this parent relationship data exist anywhere in pelias?

**Comment by orangejulius** [comment]
Hey @larskendall,
I think I understand your question, and I believe we do have the information you want. For example, when querying for Washington DC, the first result (from Geonames) has data like this:

```json
"type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -77.03637,
          38.89511
        ]
      },
      "properties": {
        "id": "4140963",
        "gid": "geonames:locality:4140963",
        "layer": "locality",
        "source": "geonames",
        "source_id": "4140963",
        "name": "Washington, D.C.",
        "confidence": 0.5,
        "country": "United States",
        "country_gid": "whosonfirst:country:85633793",
        "country_a": "USA",
        "region": "District of Columbia",
        "region_gid": "whosonfirst:region:85688741",
        "county": "District of Columbia",
        "county_gid": "whosonfirst:county:102084889",
        "locality": "Washington, D.C.",
        "locality_gid": "whosonfirst:locality:4140963",
        "label": "Washington, D.C., District of Columbia, USA"
      }
```

We provide the name, abbreviation, and identifier in [Who's on First](http://whosonfirst.mapzen.com/) for all the parent places. If that's not what you meant or something else is missing, please let us know, preferably in a new issue to keep the discussion in the right place. Thanks!

**Comment by larskendall** [comment]
Here's an example of the data that I'm seeing. If you look at the parent field, it contains its own data for some reason rather than pointing to another object. It could just be a problem on our end with the pipeline pulling int the data, but if you have any ideas what might be causing this and if you can confirm it's not an issue in pelias that would be great. Thanks so much for the help!

`{
"_index": "pelias",
"_type": "locality",
"_id": "2633766",
"_score": 1,
"_source": {
"center_point": {
"lon": -1.74588,
"lat": 52.54864
},
"parent": {
"locality_id": [
"2633766"
],
"locality_a": [
null
],
"locality": [
"Wishaw"
]
},
"name": {
"default": "Wishaw"
},
"alpha3": "GBR",
"source": "geonames",
"source_id": "2633766",
"category": [
"admin:city"
,
"admin"
],
"layer": "locality"
}
}`

And on anything that's not a locality this is what I'm getting back. Notice the parent object is empty.

`{
"_index": "pelias",
"_type": "venue",
"_id": "19122",
"_score": 1,
"_source": {
"center_point": {
"lon": 33.77414,
"lat": 35.00316
},
"parent": { },
"name": {
"default": "Ormídeia"
},
"alpha3": "GBR",
"source": "geonames",
"source_id": "19122",
"category": [
"natural"
],
"layer": "venue"
}
}`

**Comment by orangejulius** [comment]
Ahh, yes this is probably because admin loookup wasn't enabled.

If you're using the Vagrant image, you probably are out of luck, since it takes a lot of memory to do admin lookup and the Vagrant image already takes up enough memory.

You probably want to use the [full installation docs](https://github.com/pelias/pelias-doc/blob/master/installing.md) to set up Pelias if you aren't already. Take a look at the [admin lookup](https://github.com/pelias/pelias-doc/blob/master/installing.md#admin-lookup) and [config customization](https://github.com/pelias/pelias-doc/blob/master/installing.md#customize-pelias-config) sections. it's that `"adminLookup": "true"` setting that does the magic.

We're trying to figure out how to message admin lookup more clearly. Lots of people get confused about this, because it's very important and is generally what people want, but is too time/memory intensive to enable by default in most cases. Let us know if you have any thoughts.

**Comment by larskendall** [comment]
Gotcha! Really appreciate the quick response! I'll report back with this and see if we can get the problem resolved.

**Comment by larskendall** [comment]
In our data from pelias I noticed one other strange thing... it appears that there's only one item with type "country" (United Kingdom). Could that be related to this same issue? I believe the data was extracted using elasticdump.
