### ISSUE TITLE
"S St." interpreted as "South St."

### ISSUE THREAD

**Issue by demory** [pelias/pelias#329]
Our office address in Washington DC is 641 S St. NW -- 'S' as in the letter. (All east-west streets in this part of DC are named for letters -- R St. is one block south, T St. one block north, etc.)

When searching for this address with Pelias, all of the results are various matches of "South St.":

https://mapzen.com/projects/search/?query=641%20S%20St%20NW%2C%20Washington%20DC&endpoint=search&gid=&selectedLat=&selectedLng=&lng=-70.66698&lat=-33.45006&zoom=12

Our location is not among those returned unless a bounding box around DC is specified, and in that case the match is still returned and displayed as "South Street."

I'm guessing this is also an issue with N St., E St., and W St. (all valid DC streets).

Perhaps it would make sense to only assume that S (et al) is an abbreviation for the direction in cases where it is followed by another part of the street name (e.g. "S Main St.")?

**Comment by missinglink** [comment]
Thanks for the bug report, I'll add this to an upcoming dev milestone.

You're correct in saying that we currently assume single letter street names are synonyms for directionals, the same will apply for the 'diagonals' such as `SE`, `NW` etc.

We'll have to do some data diving to confirm your suggestion that directional abbreviations always precede another street name 'part', makes total sense, but the world is a weird and wonderful place so this may not be universally true.

**Comment by missinglink** [comment]
hey @thatdatabaseguy, I'd appreciate your input on this one, how confident would you feel about the strategy proposed by @demory?

**Comment by missinglink** [comment]
@demory in regard to your comment:
> and in that case the match is still returned and displayed as "South Street."

We return labels verbatim as we received them from the source dataset, the synonym analysis only applies to the tokens in the index, we don't rewrite the streets names.

Could you please paste an example of a document from our system which is returned as "South Street" when it should be labelled as "S Street" (one where the lat/lon is correct by the name is wrong)

Thanks!

**Comment by thatdatabaseguy** [comment]
@missinglink I wouldn't recommend that heuristic as it only works for certain street types (counterexample: addresses in the other Washington often use post-directionals as in "117th Ave S", and even in Brooklyn we have "Avenue N", "Avenue S", etc.) and certainly only works for English. Spanish or Italian thoroughfare types are written to the left of the name, not the right e.g. "Calle de S. Panza", "Via S Tomassi". In those cases "S" can stand for "San" or may be a person's first/middle initial. Even within the US, in certain predominantly Spanish-speaking areas of the Southwest, "S" could also mean "San" though it would be less common on official street signs, etc.

In libpostal there's a dictionary called "ambiguous_expansions" that's used to handle this exact case. If an abbreviation is in ambiguous_expansions (any single Latin-ish letter, many two letter abbreviations which could also be a first+middle initial), libpostal will give one form of the string where the abbreviation is left intact, so both "south street" and "s street" would appear. The expansions returned are an unordered set of possible meanings. While some of the strings it produces might not be correct, and may even be grammatically nonsensical (e.g. "main st" becomes ["main saint", "main street"]), the correct expansion will be among them, so it's suitable for SQL JOINs on address columns, hash lookups, Bloom filters, search queries, etc. where we're more interested in matching some pre-existing database entry than in using/displaying the expanded string(s).

I'd suggest one of the following:

1. do the equivalent in Pelias i.e. expand "S St" into both "South Street" and "S Street" and send both queries to Elasticsearch, perhaps boosting by similarity to the original string, that way if "S Street" and "South Street" both exist, "S Street" would be preferred since it's more similar the original query.

2. use libpostal expand_address. It does all of this and more in 60 languages, expands things like matching "Thirty-second" => "32nd", "ottocento" => "800", and is easy to edit. For most abbreviated addresses in English it produces 1-4 permutations, which could be sent over to Elasticsearch as a boolean query, again perhaps boosting by similarity to the original string. If for whatever reason boolean queries are too slow in Elasticsearch (I can't see a reason why they would be, but should definitely benchmark that), there is a Java/JNI wrapper for libpostal that could possibly be used in an Elasticsearch plugin on the server-side. It's also worth considering that you could store libpostal's expansions at import time in a simple no-analysis field and query that, offloading a lot of the work being done in ES to the cheaper, easier-to-scale client machines (and using a fast, optimized C implementation to boot).

**Comment by missinglink** [comment]
:+1: great feedback @thatdatabaseguy appreciate it.

I'm leaving this issue open pending a more in-depth discussion, if anyone has any more comments/suggestion on this issue, please add a comment below.

**Comment by orangejulius** [comment]
Hello everyone,
Just checking in. I can confirm that both the failure to easily find [S Street in DC](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=641%20S%20Street)
![screenshot_2016-07-02_18-14-11](https://cloud.githubusercontent.com/assets/111716/16542693/e0a42462-4080-11e6-94b7-e98fe9f1c329.png)

and the incorrect display of that street as "South Street" if you [do manage to get it to come up in results](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=641%20S%20Street,%20district%20of%20columbia)
![screenshot_2016-07-02_18-15-27](https://cloud.githubusercontent.com/assets/111716/16542698/1188171e-4081-11e6-87b1-f404d498bfc7.png)

are still happening. I think https://github.com/pelias/pelias/issues/247 will help fix this, because the incorrectly expanded records for "S Street" are coming from the OpenAddresses collection files. When we switch to the individual files, which have less processing, this should go away.

**Comment by orangejulius** [comment]
Looks like we fixed this somewhere along the way.

The [original query](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=641%20S%20Street%20nw,%20washington,%20dc) returns good results now, with no incorrect abbreviation expansion. :tada: 

![image](https://user-images.githubusercontent.com/111716/51342074-bd279980-1a47-11e9-8fb4-1ede0ab29a3e.png)
