### ISSUE TITLE
Decrease the /reverse query radius

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#340]
This radius used to be 50km and at one point was increased to 500km. It seems unreasonable to search that wide for an address that should be at the exact point the user specified. This increase of radius has also resulted in a significant performance impact. Throughput for the `/reverse` endpoint has plummeted and we'd like to see it brought back to it's previous awesomeness. :smile:

In the case where the `venue` or `address` layers are in the query, we should simply set the radius to **10km**. In these cases, the user is interested in knowing the address or venue at the specified location and providing either of those types of results from far away seems futile.

In the case where the user is not interested in `venue` or `address` results, and is doing what we call a `coarse` search, we should keep the 500km radius to ensure that we still return closest nearby region centroids. This is a short-term solution and admittedly isn't perfect.

The long-term solution is to implement a true point-in-polygon lookup for coarse queries and fallback cases where no venues or addresses are found at the given location.

**Comment by orangejulius** [comment]
How small do we think the radius should be for `venue`/`address` reverse queries? 10km will lead to more than sufficient performance, but hypothetically, would say, 1km or even 250m lead to better results and even better performance?

For users who are looking to get essentially rooftop level accuracy in their reverse queries, it seems like they might even _prefer_ we return no results outside a few meters rather than try really hard to return results, even if they're relatively far away.

**Comment by trescube** [comment]
How about 50 feet?  From my experience with reverse geocoding at another mapping company and playing around with google maps, there are some rules w/fallbacks:

- if there's an address point within, say, 50 feet of the lat/lon, return that, click any house on [this map](https://www.google.com/maps/place/Socorro,+NM+87801/@34.0738572,-106.9016745,19.14z/data=!4m5!3m4!1s0x87204ec30d7f9401:0xd3eee66aa2cfe6a4!8m2!3d34.0583995!4d-106.8914159)
- otherwise, if the lat/lon is on a streets' line string, return:
  - interpolation along the block or block range, if available, click about 1/3 of the way up [Flor Del Valle](https://www.google.com/maps/place/Socorro,+NM+87801/@34.0738572,-106.9016745,19.14z/data=!4m5!3m4!1s0x87204ec30d7f9401:0xd3eee66aa2cfe6a4!8m2!3d34.0583995!4d-106.8914159)
  - just the street name if no block is available, click any street on [this map](https://www.google.com/maps/place/Socorro,+NM+87801/@33.895473,-106.6685704,13.72z/data=!4m5!3m4!1s0x87204ec30d7f9401:0xd3eee66aa2cfe6a4!8m2!3d34.0583995!4d-106.8914159)
- otherwise, PiP the lat/lon and return the most granular polygon, click any point on [this map](https://www.google.com/maps/place/Socorro,+NM+87801/@33.6018881,-106.4417077,12.39z/data=!4m5!3m4!1s0x87204ec30d7f9401:0xd3eee66aa2cfe6a4!8m2!3d34.0583995!4d-106.8914159)

We'd have to have a reliable PiP service to accomplish the last.  Google's at an advantage since they have polygons for houses.  Until we get street geometries, we'll be limited in our ability to interpolate or return blocks. 

Ideally, we can implement all the rules and only return a single result, otherwise we're reverse searching (which arguably is covered by /search + focus.lat/lon), not reverse geocoding.

**Comment by dianashk** [comment]
I agree with all the comments. 50 feet sounds reasonable. It's best to return nothing if we're not sure. For coarse reverse we still need to support the existing level of quality, so let's keep that at 500km for now. PiP service will be the next step, and will hopefully get prioritized into an upcoming quarter this year.

**Comment by orangejulius** [comment]
One argument against super tiny radii is that we do return the distance from the specified point in the results, so users _could_ filter out results that are outside of a radius they consider acceptable. I'm writing this in passive voice because I myself am not super convinced many people would actually know to do that.

**Comment by orangejulius** [comment]
Update on performance:

Using our [loadtest](https://github.com/pelias/loadtest) framework, our dev instance (4 r3.xlarge AWS boxes for elasticsearch), we were previously only getting 1 request/second throughput when using NYC address points from OpenAddresses to generate reverse queries.

Now we can consistently serve 40 requests/second for NYC, and 70 for a desolate area in new mexico!
