### ISSUE TITLE
510 NW Windflower Ter Jensen Beach Fl 34957

### ISSUE THREAD

**Issue by b-may** [pelias/pelias#359]
This works correctly only with at least one comma before and/or after `Jensen Beach`. With or without zip code doesn't seem to matter.

So the following works: 
`510 NW Windflower Ter, Jensen Beach Fl 34957`
`510 NW Windflower Ter Jensen Beach, Fl 34957`
`510 NW Windflower Ter, Jensen Beach, Fl 34957`
`510 NW Windflower Ter Stuart Fl 34957`
`510 NW Windflower Ter 34957`

But this doesn't:
`510 NW Windflower Ter Jensen Beach Fl 34957`

This address is located within the city of Stuart city limits, but the postal address city is Jensen Beach, and that is what people are searching on.

**Comment by trescube** [comment]
That's a known issue with our current address parser called [AddressIt](https://www.npmjs.com/package/addressit), which is overly-reliant on delimiters.  We're in the process of converting to [libpostal](https://github.com/openvenues/libpostal), which is a much better solution.  We're hopefully about 1 month away from converting to libpostal in production.  Here's how libpostal analyzes `510 NW Windflower Ter Jensen Beach Fl 34957`:

```
> 510 NW Windflower Ter Jensen Beach Fl 34957

Result:

{
  "house_number": "510",
  "road": "nw windflower ter",
  "city": "jensen beach",
  "state": "fl",
  "postcode": "34957"
}
```

AddressIt considers `510 NW Windflower Ter Jensen Beach` to be the region.

**Comment by dianashk** [comment]
Looks like this hasn't been looked at in a loooooong time. :) We're back and things are better!
We have since integrated libpostal and now have even upgraded it to the next version. Things are much better with libpostal and the address is parsed correctly. Commas are no longer a big deal. 

There is ooooone little thing though. We still can't find the address in the original issue because of `postal cities`. We are all familiar with this issue at this point and it's unfortunately very relevant in Florida. So you can see below that without the city, we do find the address.

[text=510 NW Windflower Ter Fl 34957](http://pelias.github.io/compare/#/v1/search%3Ftext=510%20NW%20Windflower%20Ter%20Fl%2034957)

![screen shot 2017-04-20 at 4 33 18 pm](https://cloud.githubusercontent.com/assets/5446511/25251348/162723a4-25e7-11e7-820a-f05fc140b9bc.png)

**Comment by dianashk** [comment]
With the city, we at least parse it correctly:

```
"query": {
      "text": "510 NW Windflower Ter Jensen Beach Fl 34957",
      "parsed_text": {
        "number": "510",
        "street": "nw windflower ter",
        "city": "jensen beach",
        "state": "fl",
        "postalcode": "34957"
      },
```

**Comment by orangejulius** [comment]
This particular query now returns correct results after enabling the US postal cities support added in https://github.com/pelias/wof-admin-lookup/pull/232. I've added it as an example case in https://github.com/pelias/pelias/issues/396#issuecomment-477736197, so we can now close this issue as a duplicate.
