### ISSUE TITLE
Places in Copenhagen having Sweden as country

### ISSUE THREAD

**Issue by mleginus** [pelias/pelias#368]
Hello,

when doing reverse geocoding for places in Copenhagen, the country is incorrectly recognized as Sweden. 

![image](https://cloud.githubusercontent.com/assets/11982401/16555079/0c21707e-41d3-11e6-8a65-dce034e301d8.png)

![image](https://cloud.githubusercontent.com/assets/11982401/16555118/425bb3ca-41d3-11e6-8435-092bb6f1ce50.png)

Fortunately, I can see that some places got resolved on these endpoints already http://pelias.dev.mapzen.com/v1/ and http://pelias.prodbuild.mapzen.com/. 

I would like to ask:

1, How this issue can be resolved? Do we need to rerun the import of data with latest version of whosonfirst data to get results as returned from http://pelias.dev.mapzen.com/v1/?
2, If in the future, we will spot the similar issue - how and where can we edit this data (I assume the error comes from whosonfirst data)?

thanks in advance for your help

**Comment by orangejulius** [comment]
Hey @mleginus,
This is probably lingering from data issues in Who's on First that we fixed a while back. We [wrote a blog post about it actually](https://mapzen.com/blog/assult-on-copenhagen). The build on production is a couple weeks old at this point unfortunately, because we're working on a [big internal upgrade](https://github.com/pelias/pelias/issues/325). We'll be rolling that out this week though, and then the results you see on prodbuild will be what you see on prod :)

In the future any data issues that you see in Pelias can be reported here, or you can go use the [Who's on First Spelunker](https://whosonfirst.mapzen.com/spelunker/) to look at their data and report a bug if you see something amiss. But really don't worry about where you report the issue, we forward on plenty of data issues to our friends on the Who's on First team, and we'd much rather you report a bug than not because you didn't know where to put it.

Thanks for letting us know this is happening and we'll check back in when we've fixed it hopefully later this week.

**Comment by orangejulius** [comment]
Also, compare link for future reference: http://pelias.github.io/compare/#/v1/reverse%3Fpoint.lat=55.674316&point.lon=12.5715651

**Comment by orangejulius** [comment]
Hey @mleginus,
As expected we did a new release today, and it looks like this is now resolved (check the link in my previous comment)! If you find any other records that have Sweden instead of Denmark please let us know, and of course feel free to open another issue for any other problems! :camel:

**Comment by mleginus** [comment]
@orangejulius thanks for your prompt responses and for quick fix. The upgrade of ES is also great news!

if we will encounter any other issues, we will certainly report them :)
