### ISSUE TITLE
Investigate using ES for interpolation service

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#376]
TBD: @missinglink, fill in the details

**Comment by missinglink** [comment]
I had a look at this and it is possible to do it in elasticsearch by indexing the bbox as a `shape` field and using a query such as:

```javascript
function query( name, lon, lat ){
  return {
    "query": {
      "bool": {
         "must": {
            "match": {
               "address_parts.street": name
            }
         },
         "filter": {
            "geo_shape": {
               "shape": {
                  "relation": "contains",
                  "shape": {
                     "type": "point",
                     "coordinates": [ lon, lat ]
                  }
               }
            }
         }
      }
    },
    "size": 10
  }
}
```

For an extract of New Zealand I found a hit rate of ~75%

This system is actually really slow compared to other potential architectures, due to the overhead of the request/response and network latency I wouldn't suggest using this method for planet-scale imports.
