### ISSUE TITLE
Wrong country returned for all things in Faroe Islands

### ISSUE THREAD

**Issue by Fossdal** [pelias/pelias#384]
Search for Tórshavn
the search result returns 
Tórshavn. Denmark
Expected result
Tórshavn, Faroe Islands
or
Tórshavn, Føroyar

**Comment by orangejulius** [comment]
Hey @Fossdal,
Thanks for reporting this. It looks like we do get this wrong: http://pelias.github.io/compare/#/v1/search%3Ftext=T%C3%B3rshavn
![screenshot from 2016-07-29 10-27-43](https://cloud.githubusercontent.com/assets/111716/17251510/206e50f8-5577-11e6-86a8-eee73d765758.png)

However, the good news is that our underlying datasource, Who's on First, gets things right! The hierarchy for [Tórshavn](https://whosonfirst.mapzen.com/spelunker/id/101749171/#12/62.0147/-6.7816) shows the Faroe Islands as a dependency,and then Denmark above that, which I think is right. This means we can probably fix this pretty quickly in just the pelias code. We'll talk it over and let you know when we have a fix, which I hope to be in no more than a week.

**Comment by dianashk** [comment]
Based on team discussion earlier today, sounds like we'll need to address this issue at both index and query times.
- [ ] add `dependency` data type to wof-admin-lookup module
- [ ] store `dependency` data where applicable as part of the parent hierarchy in the `pelias-model`
- [ ] in API update label generation to prefer `dependency` over `country` when building result labels

**Comment by Fossdal** [comment]
where do you get your data from ? 
where do you get denmark from (from the data)
why is it not the same problem for Greenland ?

**Comment by trescube** [comment]
Here are all the dependencies in WOF:

https://whosonfirst.mapzen.com/spelunker/placetypes/dependency/#2/32.8/-149.4

The big issue here is when do we treat dependency as country for querying and label generation.  For example, queries for cities and addresses in [Puerto Rico](https://whosonfirst.mapzen.com/spelunker/id/85633729/#9/18.2231/-66.5912) should treat Puerto Rico (the dependency) as a country for querying (because libpostal says Puerto Rico is a country) and label generation as the least granular piece of info, eg - "[San Juan](https://whosonfirst.mapzen.com/spelunker/id/101919427/#11/18.4050/-66.0604), PR" instead of "San Juan, USA" or "San Juan, PR, USA".  

On the other hand there are a number of countries with ISO `XY`, eg - [Clipperton Island](https://whosonfirst.mapzen.com/spelunker/id/85632689/#14/10.2972/-109.2193) which technically belongs to France.  It wouldn't make sense to return the label `City Name, XY`.

**Comment by orangejulius** [comment]
@Fossdal: all our administrative hierarchy data comes from [Who's on First](http://whosonfirst.mapzen.com/), another Mapzen project, which itself gets its data from many places, such as Quattroshapes (the records themselves in WOF list more info on where the data is from), but we also edit it ourselves as we find errors.

It is interesting that [Greenland](https://whosonfirst.mapzen.com/spelunker/id/85633217/#2/76.0/-42.2) is shown as a `country` in WOF belonging to the `empire` Denmark, while the Faroe Islands are listed as a `depencency`. I'd be interested to hear from @nvkelso or @thisisaaronland whether this is intentional or something that would eventually be handled more consistently. In any case as @trescube mentioned we should be able to handle either case a little better on our own without too much work.

**Comment by nvkelso** [comment]
Both are already included correctly in the [Denmark empire](https://whosonfirst.mapzen.com/spelunker/id/136253045/descendants/?exclude=nullisland#3/66.80/-7.06) in WOF. As is Clipperton Island as part of the [France empire](https://whosonfirst.mapzen.com/spelunker/id/136253037/descendants/?exclude=nullisland#3/19.13/-149.44). The relations between **Greenland** and **Faroe Islands** are different with respect to Denmark and the EU, I'd prefer not to update them in WOF.

Agree _country_ and _dependency_ should be treated as equivalent by Pelias (they are both "admin_0").

**Comment by Fossdal** [comment]
I see other errors in boundaries and locations. 
Historically geo location for items in Faroe islands have been extremely unprecice and even wrong in various sources. like geonames and others. and i see that WOF uses data from many many sources. so it is going to be difficult or impossible to correct the source data.

one of these errors is that some places have country code to FR. this comes from the fact that Faroe Islands used to use FR but this was changed to FO sometime in 80's or or early 90's

another frequent boundary error is that places are placed in Eysturoyar sýsla. this is just wrong

I wish the data source just came from  OpenStreetMap, or at least it was the primary one, because there is 100% coverage of addresses,streets and cities, and it gets updated when there are changes in the official data

**Comment by nvkelso** [comment]
Thanks for the specific errors, we will work to correct the CC and the shape upstream in https://github.com/whosonfirst-data/whosonfirst-data/issues/383.

OpenStreet map sources continue to come in for places like address and streets.

**Comment by orangejulius** [comment]
@nvkelso: thanks! Sounds like you have things right in WOF which is what I figured, we'll update our API to use them both.

@Fossdal: We hear you :) There are lots of data errors all over. Geometry data is, like you said, harder to fix, but we are happy to help track down better data. And of course correcting source data is [more complicated](http://abcnews.go.com/International/sandy-island-undiscovered-appearing-maps/story?id=17791097), but we'll get there.

It feels like changing country codes, at least in WOF, might be quick. I'm sure @nvkelso would be happy to replace any instances of the `FR` ISO code with `FO` if that's the correct fix.

We are having a [discussion](https://github.com/pelias/pelias/issues/389) about how to handle admin data from OSM. It is sometimes valuable, but there are many, many cases where it's necessary to augment that data, and WOF works quite well for that. Over time we'll figure out the right balance, and like @dianashk mentioned in that discusssion, perhaps we can eventually support both in a way that presents a reasonable default but gives people the option of choosing what admin data they see, if they want to.

**Comment by Fossdal** [comment]
@nvkelso 
The relations between Greenland and Faroe Islands are different with respect to Denmark and the EU

Why is this. they should not be different

**Comment by trescube** [comment]
https://github.com/pelias/api/issues/662

**Comment by orangejulius** [comment]
It looks like we've fixed the issue with our label generation, but there's still an issue with Geonames data causing the first two results to be incorrect. The [query from earlier](http://pelias.github.io/compare/#/v1/search%3Ftext=T%C3%B3rshavn) shows the correct label, but only for the 3rd result.
![screenshot_2016-11-16_12-12-49](https://cloud.githubusercontent.com/assets/111716/20357449/0a54c178-abf6-11e6-863c-40472fb1f026.png)

**Comment by dianashk** [comment]
Fixed by the placeholder integration work.

![screen shot 2017-07-27 at 12 04 47 pm](https://user-images.githubusercontent.com/5446511/28680274-d40634ae-72c3-11e7-8c9f-7e04b07525b3.png)
