### ISSUE TITLE
Not possible to find certain addresses

### ISSUE THREAD

**Issue by farao** [pelias/pelias#410]
Hey, I was just trying out the pelias demo on your web page and couldn't find some of the example addresses I typed in even though they definitely exist in your database. Here's one example:

1) I was looking for Thomas-Müntzer-Platz 2 in Rostock, Germany. If you type in "Thomas-Müntzer-Pla" you correctly get "Thomas-Müntzer-Platz 22, Rockstock, Germany" as one of the autocompleted results. But when you continue typing, it disappears so that nothing between "Thomas-Müntzer-Plat" and the complete "Thomas-Müntzer-Platz 22, Rockstock, Germany" returns the correct result.

Side note: Appart from the address problem, it seems that the user is obligated to follow the order <Street Name>, <City>, <Country> somehow. It would be very helpful if you could also type addresses in different orders, e.g. "New york 22 Union Hall St." which is the way that I would type it into OSM or Google Maps.

Anyways, very neat project. I'd love to see something like this on https://openstreetmap.org sometime when it's mature enough! :-)

**Comment by orangejulius** [comment]
Hey @farao,
Thanks for reporting in! We do have trouble right now with autocomplete for [hyphenated names](https://github.com/pelias/schema/issues/65). For what it's worth, without the hyphens things will work fine. As mentioned in the linked issue, we should have a final fix for this some time near the end of the year, as it requires us to a bit of work to support multiple alternative names for each record. Right now we really only support one name per place, and do some tricks to make that as flexible as possible, but alt names will open up lots of possibilities as well as better support for multiple languages!

For the ordering, we do currently support the order you mentioned in our [search endpoint](http://pelias.io/compare/#/v1/search%3Ftext=New%20york%2022%20Union%20Hall%20St.) (accessed in [our demo](https://mapzen.com/products/search/) by hitting enter), and we should only get more flexible in the coming weeks as we integrate [libpostal](https://github.com/pelias/pelias/issues/152) for address parsing. For autocomplete however, that may be a bit of an unusual case that we might not end up supporting. But we'll see, it might be possible.

Please let us know if you have any more questions or if you find any more queries that don't work as you suspect. Some major issues of course will take a while to resolve, but there are also lots of things we can fix pretty quickly :)

**Comment by farao** [comment]
Thanks, sounds awesome. Why do you think multiple orderings is an unusual case for autocomplete? From my user perspektive, I would expect autocomplete and final search to work exactly the same. I guess every application that's not english only would need this for good user experience.

**Comment by orangejulius** [comment]
So I just realized that we get that query correct for search only accidentally due to a quirk in our current address parser[1]. If you try searches in that format for valid addresses like [Reichenberger Str. 28, Berlin Germany](http://pelias.io/compare/#/v1/search%3Ftext=berlin%20reichenberger%20str%2028) or [1709 Broderick, San Francisco, CA, USA](http://pelias.io/compare/#/v1/search%3Ftext=san%20francisco%201709%20Broderick), they don't return the correct result first either.

I actually think the ordering `[city], [housenumber and street name in whatever order is locally appropriate]` is an unusual case in general. 

Google has a [database of worldwide address formats](https://i18napis.appspot.com/address) (you can view a more [human readable list by country](https://github.com/commerceguys/addressing/tree/master/resources/address_format) as well), and I don't know of any places where the city/locality comes before the housenumber/streetname.

_However_, with all that said, our information about what sort of input formats are common is at best incomplete, and at worst based on a lot of biases. If you think `[city], [housenumber] [streetname]` is common we really want to know, so please tell us more!

---

[1] it has a hardcoded list of US states, and because New York (city) and New York (state) have the same name, and we currently search against most admin fields, it happens to work. But we are moving away from this address parser towards libpostal, which is much better overall but without a hardcoded list of anything really.

**Comment by farao** [comment]
Well, "City Street houseno" isn't a common address format in germany either but it's definitely something that i would put in a search field (which i guess is a huge difference since the way you think about it is totally different).

**Comment by farao** [comment]
And also [country>]city>street>houseno makes totally sense since it's downwards in importance. If you think about what to type in a search field in Google maps, you would first say which country and then city to look into to have faster autocompletion results.

**Comment by farao** [comment]
I'd even leave out the commas, but I guess that makes it a lot harder to get right when parsing/looking up

**Comment by slvlirnoff** [comment]
For auto-completion I think that it make a lot of sense to be able to write things in the most to least important order (Country, State, City, Street number) because you don't know if you'll find that street or that number in the dataset and you might not know the exact spelling and want to potentially fix it, which is hard to do if it's at the beginning of the input field.

But usually you know that you want results from a specific city and want to start by filtering this out.

For instance if I look for a "Main Street" it's much easier if I specify the city first then try various spelling until it works or fallback to the city center (this even more if I have a map feedback next to the field).

For an application that is focused on one specific country, the format "City, Street" (or "State, City, Street" "City (State), Street", "City ST, Street" if the country is too large and there are duplicate cities) makes a lot of sense as well. It allows quick classification of the addresses using a common prefix at a glance (vs. looking at the end of various sized string).

I usually think of it as Country, State, City, Street with a common prefix that has been removed for simplification.

For the following address:
"Grünwalder Straße 101, München, Germany"

This works as expected:
https://search.mapzen.com/v1/search?api_key=&text=Germany, Mûnchen, Grünwalder Straße 101
=> "Grünwalder Straße 101, München, Germany"

This doesn't work as I would expect and the query "feel similar" to me.
https://search.mapzen.com/v1/search?api_key=&text=Mûnchen, Grünwalder Straße 101&boundary.country=DE
 => "bremen, flughafen, etc..., results not found in the list"


Could the parsed_text "query" element be searches on 'city' as well? this would help these cases.

Best,
Cyprien

**Comment by orangejulius** [comment]
Hey @slvlirnoff and @farao,
I definitely see the rationale behind searching down the hierarchy like you're proposing, but we don't really have any plans to support such queries in the near future. We won't intentionally break them, but all the queries you two have posted that do work do so only by chance, and in fact changes we have in the pipeline to improve regular queries may very well break them.

You both clearly know a lot about how geocoders work and how computers search through hierarchical information, but most users don't. They know to type things into an autocomplete box they would format an address. All our teams subjective experience tells us that the searches you've described aren't very common. We have strict privacy respecting rules at Mapzen, but I looked through several thousand recent autocomplete queries that are available, and I didn't see any that weren't similar to this query format. Everyone seems to type addresses into search boxes the same way they would address a letter.

If this analysis seems wrong, please let us know, but we'll need data supporting it, beyond simply a few of the most knowledgeable users chiming in saying they do it that way :) Hopefully in the long term we can build a flexible enough parser that it handles any ordering. Google seems to support the queries you listed, so maybe we just need to hire a few thousand more engineers :P

**Comment by orangejulius** [comment]
The original issue (hyphenated names) is covered in https://github.com/pelias/schema/issues/65, so I'm closing this issue as a duplicate.

**Comment by slvlirnoff** [comment]
@orangejulius thanks for your answer. I clearly see your point and I guess that you are right. I'm probably bias towards writing it that way.

However, not everyone enter address the same way you have at least two people here that don't. Would be interesting to get more data, as well potentially split by country/culture/language. Even if we are only 5%. For some business 5% frustrated user might well be 5% less sales. I'd not put it on the last priority. 

As well if implementation hint into one way to use it (with placeholder or example) then the data might not be representative of preference but likelyness to follow instructions. 

For instance https://www.cff.ch/ (public transport journey planner for all switzerland) display results as city, street. As an heavy user of this website I know it does influence me strongly and my bias comes probably from this. 

On a side note in Hungary it seems that's it's the official format (city then street) even on paper, that's already potentially 10Mio people that do it that way. For chinese or japanese addresses written in chinese or japanese characters it's the same (not sure how it's handled in pelias?)

Best,
Cyprien
