### ISSUE TITLE
Update data everyday using Pelias

### ISSUE THREAD

**Issue by Muneer94** [pelias/pelias#412]
I couldn't find any docs to update `openaddresses`, `openstreetmap` data everyday. Any help?

**Comment by orangejulius** [comment]
Hey @Muneer94,
Have you seen our [install docs](https://github.com/pelias/pelias-doc/blob/master/installing.md)? OA and OSM are quite big, so you'll need a lot of hardware to import them in under 24 hours, but it can be done. Please let us know if you have questions about the install docs.

**Comment by gopi-ar** [comment]
@orangejulius clarifying @Muneer94 's question; how do you import the daily diffs from OSM without reimporting the whole DB? We have a 64 GB server with 1 TB SSDs in a RAID..

Or do we have to reimport each source completely each time? Now this will be infeasible..

**Comment by gopi-ar** [comment]
@orangejulius It would also be super helpful if requirements for importing the whole OSM, any benchmarks are specified on the install docs' page.. Apologies if it's mentioned somewhere and we missed that!

**Comment by orangejulius** [comment]
Hey @gopi-ar,
There is actually no way to import daily diffs currently. It's definitely something we want to do, and you can track https://github.com/pelias/openstreetmap/issues/26 to see when we make progress. However, because getting all the details right for doing the diffs is a bit of work, we've taken the "throw hardware at the problem" approach for now, and we don't plan on implementing daily diff support in the near future.

We build once a week for production, and right now it takes about 39 hours (that's including the time to download all the data and insert it into a fresh Elasticsearch index). This is on a `m4.2xlarge` AWS machine, running two importers in parallel. The bottleneck currently is CPU running the Node.js worker processes, and for OSM, running pbf2json to parse out the parts of the PBF file that Pelias cares about. So to make it fast, get the best CPU you can :) If you only care about OSM I suspect you could get it down to under 1 day with just nice hardware and no code changes.
 
Another thing to note is that we have two clusters in production: one for handling queries and one for creating new builds (this could  be scaled up to multiple build clusters to reduce the interval between new builds to under 39 hours). Then we create a snapshot, load it into the production query cluster, and using an Elasticsearch index alias, we can switch between the new and old build with no downtime or interruptions of any kind. If you want to know more about this let me know and I can share some of the scripts we use (we are working on making them completely public anyway).

Definitely let us know as you have more questions, and you might find our [Gitter](https://gitter.im/pelias/pelias) chat helpful, there are quite a few people, not just on the Pelias team, that are running Pelias in production in that channel and setup issues should generally get some sort of answer. Cheers!

**Comment by gopi-ar** [comment]
@orangejulius thanks for that info. We're trying to make our service [LocationIQ.org](https://locationiq.org) faster, more reliable (and free-er :D ). I guess we'll also just throw more hardware at it for now.

You guys are doing fabulous work and we'd love to help in any way we can. 

Catch you on Gitter soon..

**Comment by Muneer94** [comment]
@orangejulius you have commented on @gopi-ar query and said  `running two importers in parallel`, could you please elaborate it.

**Comment by eyal33** [comment]
> Hey @gopi-ar,
> There is actually no way to import daily diffs currently. It's definitely something we want to do, and you can track [pelias/openstreetmap#26](https://github.com/pelias/openstreetmap/issues/26) to see when we make progress. However, because getting all the details right for doing the diffs is a bit of work, we've taken the "throw hardware at the problem" approach for now, and we don't plan on implementing daily diff support in the near future.
> 
> For Mapzen Search, we build once a week for production, and right now it takes about 39 hours (that's including the time to download all the data and insert it into a fresh Elasticsearch index). This is on a `m4.2xlarge` AWS machine, running two importers in parallel. The bottleneck currently is CPU running the Node.js worker processes, and for OSM, running pbf2json to parse out the parts of the PBF file that Pelias cares about. So to make it fast, get the best CPU you can :) If you only care about OSM I suspect you could get it down to under 1 day with just nice hardware and no code changes.
> 
> Another thing to note is that we have two clusters in production: one for handling queries and one for creating new builds (this could be scaled up to multiple build clusters to reduce the interval between new builds to under 39 hours). Then we create a snapshot, load it into the production query cluster, and using an Elasticsearch index alias, we can switch between the new and old build with no downtime or interruptions of any kind. If you want to know more about this let me know and I can share some of the scripts we use (we are working on making them completely public anyway).
> 
> Definitely let us know as you have more questions, and you might find our [Gitter](https://gitter.im/pelias/pelias) chat helpful, there are quite a few people, not just on the Pelias team, that are running Pelias in production in that channel and setup issues should generally get some sort of answer. Cheers!

Hi,

I will be happy to get the scripts which support build of the new index. As I saw the index name cannot be configured since it comes in pelias-config.

Thanks,
Eyal

**Comment by msschl** [comment]
@orangejulius I would be happy to get the scripts as well.

Thanks,
Markus

**Comment by stefanocudini** [comment]
hi!

about ES index update how to do the swap? using if I have seen correctly the index name is simply specified in the same pelias.json file, shared with all services, so I don't understand how the services can use two different indexes.

where can i find documentation for this task?

many thanks

**Comment by missinglink** [comment]
There is an elasticsearch concept called "index aliases" which allow you to create a virtual index called "pelias" which points to a versioned index.

The advantage of this method is that you can have two versions in the cluster and execute a single command to switch between them without any downtime.

https://medium.com/@andre.luiz1987/index-alias-elasticsearch-fd0b39b25efa
