### ISSUE TITLE
Unable to import openaddress data with addressLookup and deduplicate enabled

### ISSUE THREAD

**Issue by arungowtham** [pelias/pelias#443]
Hey team! 
                I tried importing openaddress data using https://github.com/pelias/openaddresses and it indexed and worked fine. But when i change the config to import along with addressLookup( using this data https://github.com/whosonfirst-data/whosonfirst-data) and deduplication, it throws this exception :

![screenshot from 2016-10-18 14 08 34](https://cloud.githubusercontent.com/assets/19775829/19470277/6dbe8ada-953c-11e6-827f-916152aea2b1.png)

The exception above is thrown 11 times, then the following verbose (refer snap below) is only infinitely printed. Neither info regarding indexing is shown nor any content is indexed.

![screenshot from 2016-10-18 14 12 33](https://cloud.githubusercontent.com/assets/19775829/19470397/01987fd6-953d-11e6-9f0e-9248bdf002f6.png)

It would be great if you guys would guide me through this discrepancy.

Regards,
AG

P.S : 
node --version = v6.7.0
npm --version = 3.10.3

imports config(defaults.json) looks like this : 
![screenshot from 2016-10-18 14 20 02](https://cloud.githubusercontent.com/assets/19775829/19470651/f248376e-953d-11e6-985a-73e9388fd9ed.png)

**Comment by orangejulius** [comment]
Hey @arungowtham,
Thanks for reporting this. I have a couple ideas of what this could be.

First, can you tell me which branch the openaddresses importer is on (should be master or production), and can you tell me the exact SHA1 of the commit you're using. I assume you're up to date but I want to make sure.

Second, make sure all the node modules are out of date. NPM doesn't help much here, but `npm install; npm prune` should be enough, or the more drastic `rm -rf node_modules; npm install` will definitely do the right thing.

Finally, it might be that the Who's on First data wasn't downloaded correctly. In the past we've suggested downloading directly from the git repository at https://github.com/whosonfirst-data/whosonfirst-data, as it appears you've done. This _should_ work correctly, but we recently added a downloader script to the [pelias whosonfirst importer](https://github.com/pelias/whosonfirst). I'd suggest replacing `/home/sas/pelias/whosonfirst-data` with an empty directory, then running `mkdir -p /home/sas/pelis/whosonfirst-data/meta` to work around https://github.com/pelias/whosonfirst/issues/146 (sorry for the annoyance, we'll fix this soon). Then you can use the whosonfirst importer download script:

```
git clone git@github.com:pelias/whosonfirst.git
cd whosonfirst
npm install
npm run download
```

This will look at your pelias.json config file and put all the files in the right place.

Finally, try turning off the address deduplicator. We haven't touched it in a while and don't use it anymore.

That's a lot of things to try, so if you'd rather chat with us directly, we do have a [Gitter channel](https://gitter.im/pelias/pelias), or of course you can reply here. Hope one of these suggestions is helpful, and if not we'll gladly dig further into things with you.

Cheers!

**Comment by arungowtham** [comment]
Hey @orangejulius 
First of all, thnx for getting back in such short notice.

- I am using production branch. In order to simplify what you said, i cloned the latest production branch and here are the details 
![screenshot from 2016-10-19 11 48 27](https://cloud.githubusercontent.com/assets/19775829/19507764/a6795d4e-95f2-11e6-930f-484589ad17dd.png)

- SHA1 of production : `cat .git/refs/heads/production` 
> 496ef7c1ba2ff780a5b82d4fd1b60bc4a9aaafc7

- I've removed address deduplication config and stopped the process.

At this stage i tried to import the openaddress data with adminLookup, yet it failed again with the same exception's i stated in the first post.

- The whosonfirst-data i have is around **28GB**, is this the correct size or am i missing anything here because i dint find any issues while downloading. I'd use the downloader script, but it would take ample amount of time and data, so if there are any sample whosonfirst-data to test, it'd be great. If that ain't the case i'd give the dowloader script a shot :+1: 

Finally, I'd prefer continuing the thread here itself !!

**Comment by orangejulius** [comment]
Hey @arungowtham,
Okay, good, you're up to date with production. Also thanks for teaching me about the `show-branch` command, I had never used it before.

Next, definitely make sure everything is ok with Node.js modules. It's notoriously easy to have out of date dependencies, so just make sure you've run `rm -rf node_modules; npm install` and try again.

If it still doesn't work, can you run `tree -L2 /home/sas/pelias/whosonfirst-data/` and post the results? This will show the general structure of your whosonfirst-data directory just to make sure things are ok.

**Comment by arungowtham** [comment]
Hi @orangejulius 

- When i said, i cloned the latest production branch, i meant, installing openaddress importer from scratch again, so i guess it would have up to date Node.js modules. Yet again i tried removing and installing node modules, it throws the same exception.

-  Directory Structure : 
![screenshot from 2016-10-20 13 19 40](https://cloud.githubusercontent.com/assets/19775829/19550725/6f0035a0-96c8-11e6-8d00-f69d41bc1eb8.png)


Thanks !!

**Comment by orangejulius** [comment]
Hey @arungowtham,
I think I know what this is. I suspect that if you look at all of the `wof-*-latest.csv` files in the meta directory (and shown in your last screenshot), you'll find many of them are not actually CSVs. The whosonfirst-data repo requires [git-lfs](https://git-lfs.github.com/), but there aren't very good error messages when git-lfs isn't installed.

If you'd like, run install git-lfs, make sure it has run in that repository, and things should work. Alternatively the downloader script in the pelias/whosonfirst repo can download the data for you without git-lfs. It's generally not necessary to have the whosonfirst-data git repo (which as you mentioned is extremely large) unless you are deubgging issues in the whosonfirst data itself, so I'd recommend using the downloader. Let me know if that solves things for you.

**Comment by arungowtham** [comment]
Hi @orangejulius ,

Thanks, once i ran git-lfs things have sorted out fine. :+1: 
I have certain queries(pardon me, 2nd & 3rd Q are off topic from this thread)  :

1.  In the whosonfirst importer you suggested it is mentioned, the data to be downloaded might go upto 100GB, but i find this repo data to be 1/3'rd of it, so is it fine to proceed with the whosonfirst-data repo itself? How about those changes made to the whosonfirst data, which case would suit better to update them?


2. I need to know about openaddress updating process, i.e when openaddress data is updated, how to index them, should i rerun the entire global data set or what is the procedure to update only the changes(like how nominatim does with osm data).

3.  What will happen if i try to import a same csv file twice, will the index be duplicated or will they be overridden.

**Comment by orangejulius** [comment]
Ok great, glad we got things working! :)

1.) The 100GB includes venue data, which we aren't using yet in production, and isn't needed if you only want to import OpenAddresses.

2.) Due to the way Elasticsearch works and the way OpenAddresses data is updated, the only option is to rerun the entire import when you want to update the data. For our hosted instance of Pelias (Mapzebn Search), we re-run a full import of all our data once a week. You can use with [Elasticsearch aliases](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html) to perform these re-indexes without needing any downtime, if that's something you need.

3.) If you import the same CSV twice, it all works out fine, and you won't get double the data.

We are of course happy to answer more questions, and definitely let us know how things go as you continue to get Pelias set up!

**Comment by arungowtham** [comment]
Hey @orangejulius,

Thanks a lot !!

- While trying to import the entire global dataset(openaddresses) the importer stopped indexing abruptly without any exception(~300MB was indexed at that moment), i guess it could be due the low config of _max file descriptors_ , am trying to solve this, if this doesn't resolve, will keep you posted.

BTW when i tried to import with address-deduper enabled, neither it threw any exception nor it indexed.(Hope this helps you in your road-map to improvise duplicates removal process).

**Comment by arungowtham** [comment]
Hi, 
I did a full planet setup with openaddress data and it took 12 days to complete.
I have few questions :

- Is there any High performance-oriented machine configuration that you would suggest to run pelias(osm+openaddress+geonames).

- At present am testing using this specs (32 core-2.3GHz-16Gb Ram), one individual request(`text=65th st texas`) takes around **3.5 to 4 Seconds** , and 100 concurrent requests takes ~35Sec. This seems way off to me, is this the standard or am i missing something here, because i would like to have better response time and concurrency.

- Regarding updating Openstreetmap data : should i reindex for this also ? or is there a workaround.

**Comment by orangejulius** [comment]
Hey @arungowtham,
If you are running Elasticsearch on only 1 machine with 16GB RAM, then yes, that's what's causing things to be slow. You'll need a lot more RAM for good performance.

I'll tell you about our setups for Mapzen Search so you can decide what sort of servers to use. Our dev environments, which are sized to be about as small as possible while still having reasonable performance for a small number of concurrent requests, have 4x [r3.xlarge](https://aws.amazon.com/ec2/instance-types/) (30.5GB RAM). Elasticsearch is using 48GB for JVM heap, so I can't imagine you could squeeze a full planet build into a cluster with less than 60GB RAM. This setup can handle up to about 30 requests/second for search, and 50/sec for autocomplete and reverse.

Our production environment is even bigger: 8x c4.4xlarge. There's a bit more RAM to enable us to have 1 set of replica shards to guard against a node failing, but the main difference is there's a lot more CPU available. We can easily handle over 300 requests/sec for any endpoint.

We also use a separate machine to run the importer processes. Each importer needs around 5GB of RAM but is otherwise CPU bound for performance. Faster CPUs help the most here.

Fortunately the API itself is light on resources. We use t2.larges just because we need 4GB of RAM for libpostal data. Even when the elasticsearch cluster is fully loaded handling hundreds of requests/sec, the API box CPU is nearly idle.

Finally, to your third question. When you want to update Openstreetmap data, you have only one option: delete the index completely (perhaps take a snapshot first if you want to save it), recreate the index, and reload all the data.

**Comment by arungowtham** [comment]
hi @orangejulius ,
Thnx for the info, will ponder over it, it's definitely a lot useful !!

**Comment by arungowtham** [comment]
Hi @orangejulius ,
1) Regarding osm data updates, is this possible : the diffs(daily) are in osc format, which i have converted to pbf format, now if i index using this file does it imply that i have updated the diff successfully to the previously indexed data? 
2) Upon your leisure, can you pls give info regarding the time it takes to index(OA/OSM/GN with wof-lookup) planet data in your mapzen architecture for indexing(can you mention this spec), also the spaces those individually occupy !!(Any pro-tip to boost this indexing process :) )
Sorry if my queries seem childish and dull-witted...
TIA.

**Comment by orangejulius** [comment]
Hey @arungowtham,
Sorry for the delay, your question got lost in my inbox :p

1.) Importing daily diffs won't quite work. Sometimes things are deleted from OSM, and there's currently no way to delete individual items from Pelias as part of the import process, so you'll end up with duplicates.
2.) Please see the "Considerations for full-planet builds" section of our [install docs])http://pelias.io/install.html) for lots of information about build times and server configuration settings. Let us know if you have any questions, as that's how we improve the docs over time. Thanks!
