### ISSUE TITLE
7030 broomshedge trl, winter garden, FL 34787

### ISSUE THREAD

**Issue by b-may** [pelias/pelias#456]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---

#### Here's what I did :innocent:

[/v1/search?text=7030 broomshedge trl, winter garden FL 34787](http://pelias.github.io/compare/#/v1/search%3Ftext=7030%20broomshedge%20trl,%20winter%20garden%20FL%2034787)

---

#### Here's what I got :scream_cat:

Only the city of Winter Garden was returned.

---

#### Here's what I was expecting :sparkles:

The address to be found.

---

**Comment by orangejulius** [comment]
Hey @b-may,
Thanks for the report. it looks like this record _is_ in openaddresses, so we should be able to find it. It looks like yet another case of the admin area we derive from Who's on First not matching up with the postal city. Here's a query that finds it: http://pelias.github.io/compare/#/v1/search%3Ftext=7030%20broomshedge%20trl
![screenshot from 2016-11-15 17-39-52](https://cloud.githubusercontent.com/assets/111716/20327316/888071a6-ab5a-11e6-9099-dbd1e06e81d5.png)

We do want to support [postal cities](https://github.com/pelias/pelias/issues/396) in the future, but that will have to be done in a way that supports other admin lookup methods as well, since postal cities aren't always present.

**Comment by b-may** [comment]
Here's a thought for helping with the city geography problem until you get postal geometry with multiple cities assigned to each postal code (primary and alternates). Use county area (geometry) as a boundary limiter for cities. Create a list of cities, states, the counties they are within and the geometry for each record is the county geometry (bounding box). So when you lookup `winter garden, fl` you get the county geometry and look for `7030 broomshedge trl` within that area. There shouldn't be a need to be looking in south carolina for an address in winter garden, fl.

**Comment by orangejulius** [comment]
This is fixed with our recent postal cities work!
![Screenshot_2020-03-05_09-53-00](https://user-images.githubusercontent.com/111716/76010116-3641b480-5ec7-11ea-8b35-9c06655303b3.png)

**Comment by b-may** [comment]
Works! Thanks!
