### ISSUE TITLE
Upgrade to Elasticsearch 5

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#461]
ES 5 has been released. 🎊 

Let's see what migration might look like and what the benefits/drawbacks might be.

Looking for input from the community here. ✨

**Comment by jacobbaskin** [comment]
I'm going to be hacking stuff in to try and do a performance comparison. But here's what I've found so far:
- Everything would need to depend on the elasticsearch 12.0.1 client library (this should be a noop -- afaict most of the master branches already do but they'd need to get released)
- Schema would have to change slightly. 5.0 doesn't support the "index_concurrency" parameter and geo indexing changed so a lot of the options on "geo_point" need to be removed
- Some deprecated query clauses need to be rewritten

Maybe that's it? I'll let you know if I find anything else.

**Comment by missinglink** [comment]
happy to assist, I'm not the best at checking my github notifications but you have our email if you need anything :)

each repo contains at least one testing framework; some include two or three. The `pelias/schema` repo includes integration tests along with unit tests, so you should be able to confirm that the refactor works as expected by simply running those tests and ensuring they pass.

having a feature flag for 'ES 5 mode' has the potential to get pretty messy; particularly if the `pelias/query` code also need to be varied accordingly, so let's try and keep that as tidy as we can, an ideal scenario would be using APIs that are backwards compatible with ES2, although that's probably wishful thinking ;)

**Comment by jacobbaskin** [comment]
@missinglink the query code should be 100% backward-compatible as far as I can tell. The schema code could be but I'd worry about hurting performance in ES 2. Is there an easy way to remove some fields and check indexing + querying performance? Will the integration tests work for that?

**Comment by missinglink** [comment]
hey @jacobbaskin, you can remove fields from the schema but it might cause code depending on those fields to break.

what exactly are you proposing to change?

**Comment by missinglink** [comment]
related: https://github.com/pelias/schema/issues/194

cc/ @jacobbaskin

**Comment by cag** [comment]
Okay, in order to do this, I have 3 pull requests that must be simultaneously resolved, and afterwards, version numbers for these repos must be propagated throughout all the repos.

See:
https://github.com/pelias/dbclient/pull/35
https://github.com/pelias/config/pull/45
https://github.com/pelias/schema/pull/195

It would probably be best to resolve them in that order.

**Comment by orangejulius** [comment]
Hi everyone,

It looks like there are only a few things to do to support ES5:

- [ ] Change all our [filtered](https://github.com/pelias/query/search?utf8=%E2%9C%93&q=filtered) queries to [bool queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-filtered-query.html). This is a lot of tedious work, since many of our queries use this format, but shouldn't be hard. Elasticsearch 2 already supports bool queries, so this can be done any time.
- [ ] Remove unsupported [geo_point parameters](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_mapping_changes.html#_literal_geo_point_literal_fields). These are [currently used](https://github.com/pelias/schema/blob/master/mappings/partial/centroid.js#L9-L11) for all our centroid fields, but aren't supported anymore. @cag has a [pull request](https://github.com/pelias/schema/pull/195) that detects whether or not to put these fields in the schema depending on which version of Elasticsearch is in use, but it adds some complexity. I'm inclined to say we simply remove those fields and live with any performance consequences for ES 2.x. I don't think we intend to support two major versions of Elasticsearch anyways, so once we have ES5 support, we will drop support for ES2.

**Comment by orangejulius** [comment]
Hi everyone,
It's been a while since we've worked on anything here. When looking at another task @trescube and I figured out what was blocking our PR to use Elasticsearch 5 compatible queries, and with https://github.com/pelias/query/issues/65 all our acceptance-tests are now passing, so we should soon be able to have full functionality with ES5!

**Comment by orangejulius** [comment]
Hello again everyone,
Time for another ES5 update. This is something we want to take care of soon. We need to add support for ES5 with backwards compatibility for ES2, at least for long enough to transition over.


I recently rebased @cag's old [es5-compat](https://github.com/pelias/schema/tree/es5-compat-new) branch in pelias/schema, and it still works.

Things we have to do (in addition to the ones above):
- [ ] Ensure the ES5 docker image works in the [dockerfiles](https://github.com/pelias/dockerfiles/tree/master/elasticsearch/5.2.1) setup and updated it to the latest ES5 (it's currently at 5.2.1)
- [ ] Run some testing, ideally with the new [city acceptance tests](https://github.com/pelias/pelias/issues/718) first, and then a full planet build, to see how queries look with ES5. Then fix any issues that arise

**Comment by Murmand** [comment]
Hello. Thank you for all the great job. It looks `es5-compat` branch has not been updated for a while. Will you plan any update soon?

**Comment by LEDfan** [comment]
We are looking into using Pelias in our production environment, unfortunately the lack of ES5/6 support is holding us back. Is there any update on this?

From the TODO list above it seems that it can already be tested, if this is the case I can definitely test this is on our setup and report back if it works.

Thanks!

**Comment by andrewkcarter** [comment]
We are also considering using Pelias, but the lack of ES 5 or ^ is a deal breaker for us as well.

**Comment by orangejulius** [comment]
@ashleyholt the acceptance-tests are perfect for testing any full planet build. we'll definitely use them to verify any Elasticsearch upgrades.

**Comment by bboure** [comment]
Hi all, 
Any news on this? I just discovered Pelias and it looks just great and exactly what I need. I am considering using it for a new project. However if I could use ES 5 or 6 it would be great.
I am not familiar yet neither with Pelias nor with Elastic search (still learning) so I cannot really offer my help here but if I can help in any way (even if just by testing), just let me know.

**Comment by missinglink** [comment]
This is happening imminently (firstly an ES5 upgrade and then later an ES6 upgrade).
Hard to give an estimate but I would hope we could have something working in ES5 within the next 30-60 days.

@bboure is there a deal-breaker reason why you can't run the existing ES@2.4 setup, possibly something ops related?
If you haven't seen https://github.com/pelias/docker then check that out, it makes getting everything setup much easier :)

**Comment by bboure** [comment]
@missinglink Thank you for your feedback.
No deal breaker. I am still at the very early stage of my project and I am still playing with Pelias to try to see if it would fits my requirements; and everything indicates that it does! 🙂 
Right now I am using ES 2.3 (because AWS does not offer 2.4) but of course I would prefer to use a much more recent release whenever possible.
I can wait 30-60 more days.

**Comment by orangejulius** [comment]
Hi everyone,
Just to give a bit more context on this, we are beginning work on the upgrade process in earnest.

We plan to begin some initial work to allow development with Elasticsearch 5, and then determine how feasible it is to support both ES 2 and ES 5 for a little while to make transitioning easier. Worst case, we will publish a "final" Pelias release that supports ES2 and require ES5 for all subsequent versions.

Milestones for initial development work:
- [ ] Update/refresh the Elasticsearch 5 docker image (we've learned a lot about Docker since it was first made)
- [ ] Make initial changes to [pelias/schema](https://github.com/pelias/schema/) to allow for ES5 support

After that initial work, we'll iron out any issues bringing ES5 support to Pelias mainline. This will involve a progression of testing on smaller to larger builds. Ultimately, we will require a full planet Pelias build run under known conditions to show good results before we consider Elasticsearch 5 production ready.

We'll likely test on a progression of builds something like this:
- [ ] The standard Portland metro area project from http://github.com/pelias/docker/
- [ ] A single large city like Berlin, New York, Paris, etc
- [ ] A medium sized country like South Africa, France, or Australia (all also projects in http://github.com/pelias/docker/)
- [ ] A continent-level build like Europe or North America
- [ ] A full planet build, tested with our [global acceptance tests](https://github.com/pelias/acceptance-tests/)

While continent sized and full planet builds require serious resources to run, all the prior builds can be run on most personal laptops with around 8GB or more of RAM and a good amount of free disk space. We'll post many updates here, but definitely when we are ready to test at those stages, as we'd love feedback from as wide an audience as possible.

At this time, it appears the easiest way to move forward is to focus on Elasticsearch 5 support only for now. Once we've settled into supporting ES5, it appears adding support for [ES6](https://github.com/pelias/pelias/issues/719) is something that can coexist with ES5 support quite well.

**Comment by missinglink** [comment]
FYI, the schema changes are ready for testing/review in https://github.com/pelias/schema/pull/323

**Comment by missinglink** [comment]
Today I merged https://github.com/pelias/docker/pull/25 which means we support `5.6`, please see the notes in https://github.com/pelias/schema/pull/323 regarding configuration for non-docker setups.

**Comment by orangejulius** [comment]
At this point, we have tested ES5 up to and including full planet builds. As long as the full planet build is also done with ES5, performance has increased a small amount across the board.

I believe we're ready to make ES5 the default configuration option and then look at removing support for ES2 to allow ES6 support to be gradually added.

**Comment by NickStallman** [comment]
I'll add a +1 that ES 5 is working well in production for us with a full planet build (5.6.14 to be exact).

Migration was really trivial using ElasticSearch in docker, I ran ES5 on a different port and imported a prebuilt dataset, then disabled ES2 and swapped ES5's port back and updated the pelias config file.

**Comment by orangejulius** [comment]
Hi everyone,
We just officially flipped the switch, and ES5 is now the default version of Elasticsearch supported by Pelias. Unofficially, ES2 will continue to work for a while, but we can now begin adding support for ES6, which will require making changes that no longer work in ES 2.4.

Please report any issues with the migration to us! 🎉 🎤
