### ISSUE TITLE
Categorize POIs to facilitate result filtering [PL-PG06]

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#49]
Categories will make reverse place geocoding a useful service.

This could be done in conjunction with adding popularity scores/tags.

**Comment by stevevance** [comment]
ESRI's geocoder has a broad [selection of categories](https://developers.arcgis.com/rest/geocode/api-reference/geocoding-category-filtering.htm).

**Comment by missinglink** [comment]
Hey @stevevance, I've done some [research in to place taxonomies](https://github.com/pelias/pelias/wiki/Taxonomy-v1), I'm looking to implement a first version of it this week. If you have any comments or suggestions please let me know ;)

**Comment by dianashk** [comment]
Still need to add category mapping to all import pipelines.

**Comment by stevevance** [comment]
@missinglink Your research is excellent and I support your proposed categories in a Pelias-specific taxonomy, but I think that you would be reinventing the wheel to create a new taxonomy.

**Comment by missinglink** [comment]
hey @stevevance thanks for the feedback, so in the end I decided to flip-flop on my "start small and learn from it" idea, I think it's going to be really hard to learn anything profound from a small taxonomy so it's [grown a bit bigger](https://github.com/pelias/openstreetmap/blob/master/config/category_map.js) than the original proposal.

The above linked code is live now in production and we are categorising the whole planet using that mapping.

We will have to keep it as a private API for now until the dust settles on this feature, I expect to have the query logic exposed in the RESTful API in the next week or so and I'll share the API parameters with you along with the disclaimer that it's an undocumented feature and the categories will no doubt change or go away without warning until we finalize them.

The really good news is that since we are foodies I've added cuisine categorisation so you can use the `/reverse` API to find the 10 nearest Korean BBQ places :)

**Comment by dianashk** [comment]
TBD:
- return categories in geojson? all endpoints?
- implement on /search for all endpoints
- [wait till es@2.0] implement for /suggest

**Comment by missinglink** [comment]
FYI @stevevance this feature is now live for `/reverse` if you would like to have a play, it's undocumented but pretty self explanatory, you can use a query such as:

```
http://pelias.mapzen.com/reverse?lat=52.516701&lon=13.400000&size=40&categories=food:cuisine:chinese
```

The `?categories` param takes a comma-separated list of [categories](https://github.com/pelias/openstreetmap/blob/master/config/category_map.js) which are treated as `OR` conditions, any POIs which do not match *any* of the conditions will be excluded.

Oh, also we rolled out a performance fix for bbox queries recently which should have resulted in a 3x speed up for your pelias queries.

Enjoy!

**Comment by dianashk** [comment]
We will be getting categories taxonomy from our data team in the near future.
