### ISSUE TITLE
No "size" parameter for /autocomplete API

### ISSUE THREAD

**Issue by barbeau** [pelias/pelias#496]
We're in the process of switching from the `/search` to `/autocomplete` endpoint and structuring a [client library](https://github.com/CUTR-at-USF/pelias-client-library) around the Pelias API, and noticed that the `size` parameter isn't currently supported in the `autocomplete` endpoint.

Is this intentional?

---
#### Here's what I did :innocent:

Look at the docs and source code

---
#### Here's what I got :scream_cat:

`size` parameter is not included in `/autocomplete`:
https://mapzen.com/documentation/search/autocomplete/#available-autocomplete-parameters

---
#### Here's what I was expecting :sparkles:

I expected the `size` parameter to be included, as it is included in `/search`:
https://mapzen.com/documentation/search/search/#available-search-parameters

**Comment by orangejulius** [comment]
Hey @barbeau,
Thanks for asking. It is intentional. The autocomplete endpoint is built to be as fast as possible, since it's meant to be giving feedback as a user types and thus really needs to return in under 50ms or so to be at it's most usable. As mentioned in https://github.com/pelias/pelias/issues/249, removing the size parameter increases the odds of the result being cached, and it makes a big difference.

We've talked about this in the past as mobile devices could sometimes benefit from shaving off every byte possible, and in many cases 10 results is too many. Some ideas like different response formats with less data have been thrown around, but so far nothing beats the simplicity of returning and caching a constant number of results.

**Comment by barbeau** [comment]
Thanks @orangejulius for the quick response!  Looks like this is a duplicate of https://github.com/pelias/pelias/issues/249 then, and this could be closed?

**Comment by dianashk** [comment]
Looks like it is a dupe. Closing in favor of #249 

Thanks @barbeau!
