### ISSUE TITLE
Better de-duplication for results with postal codes

### ISSUE THREAD

**Issue by rmglennon** [pelias/pelias#541]
This example came in from support.

https://search.mapzen.com/v1/search?boundary.country=aus&text=1%20goodwin%20st%20glen%20iris

This is a search for 1 goodwin street in Australia. If you search for another address on this street, such as 10 goodwin, you get postal codes.

“10 goodwin street” is coming from openaddresses au/countrywide which contains a postal code whereas “1 goodwin street” is coming from openaddresses au/victoria which doesn’t have a postal code

So, we should de-duplicate smarter when postcodes are available or sort them to prefer those with more info.

**Comment by dianashk** [comment]
Connected to https://github.com/pelias/api/issues/872

**Comment by orangejulius** [comment]
Looks like this example isn't a problem any more, most likely because with Australia's [G-NAF](https://data.gov.au/dataset/geocoded-national-address-file-g-naf) dataset we have addresses and postalcodes for _all_ of Australia. (hooray!)

Finding test cases for records without postalcodes, as mentioned in https://github.com/pelias/acceptance-tests/issues/242, is getting increasingly difficult. Good problem to have.

**Comment by orangejulius** [comment]
We do now explicitly prefer records with postal codes, ever since https://github.com/pelias/api/pull/890. So most OpenAddresses results in Australia will use the `au/countrywide` version, which includes a postcode!
