### ISSUE TITLE
investigate possible PIP issue

### ISSUE THREAD

**Issue by missinglink** [pelias/pelias#572]
the results of the following query should be marked with the dependency `New Caledonia`.

- http://pelias.github.io/compare/#/v1/search%3Ftext=rue%20lamartine,%20Sud

Judging by the polygon https://whosonfirst.mapzen.com/spelunker/id/85632473/#6/-20.399/163.586 I don't see any reason why they would not intersect?

**Comment by missinglink** [comment]
first result of query:

```javascript
      "properties": {
        "id": "polyline:21960102",
        "gid": "openstreetmap:street:polyline:21960102",
        "layer": "street",
        "source": "openstreetmap",
        "source_id": "polyline:21960102",
        "name": "Rue Lamartine",
        "street": "Rue Lamartine",
        "confidence": 0.979,
        "accuracy": "centroid",
        "country": "France",
        "country_gid": "whosonfirst:country:85633147",
        "country_a": "FRA",
        "region": "Sud",
        "region_gid": "whosonfirst:region:85675259",
        "label": "Rue Lamartine, France"
      },
```

**Comment by trescube** [comment]
Well, it looks like wof-admin-lookup doesn't support dependencies after all:

https://github.com/pelias/wof-admin-lookup/blob/master/src/lookupStream.js#L89-L101

**Comment by binshe** [comment]
**Thank you** @missinglink for having raised the question.
**Thanks for your help** @trescube.

I am trying to sort out why the queries in the `region` / `dependency` of `New Caledonia` do not return a result properly sorted in the order "`street`, `locality `, `region`" or "`street`, `locality `, `dependency`".
Instead, the results are either limited to
A) "`street`, `country`" , or to
B) "`locality`, `country`"
which is of course of poor value.

A) For instance, still no `locality`, `region` nor `dependency` appears in the result of the aforementioned query:
- http://pelias.github.io/compare/#/v1/search%3Ftext=rue%20lamartine,%20Sud

It simply returns the not-so-precise result:
> "Rue Lamartine, France"

First result of query :
![rue lamartine_france](https://user-images.githubusercontent.com/28983379/26953365-26d95020-4caa-11e7-9890-3882e9e38288.png)


How can we enrich the results so that their content is more like :
> "Rue Lamartine, Nouméa, New Caledonia"

or

> "Rue Lamartine, Nouméa, Nouvelle Calédonie"

?

B) Broadly speaking, the queries "`street`, `Nouméa`" such as

- http://pelias.github.io/compare/#/v1/search%3Ftext=rue%20lamartine%20noumea

Just return the `locality` and `country` (B.1 below), or `locality` and `dependency`(B.2 below).

B.1 - First result of query :
![noumea_france](https://user-images.githubusercontent.com/28983379/26953381-424b5e5c-4caa-11e7-9846-111a53e14c3d.png)

B.2 - Second result of query :
![noumea_new caledonia](https://user-images.githubusercontent.com/28983379/26953388-4a9e87f0-4caa-11e7-8c1d-77d200c274e5.png)

How can we solve this?
Is it an issue with dependencies in general? I noticed the issues seem the same with another `dependency` of `France` : `French Polynesia`.

Many thanks.
**Apologies if I am not very clear. This is my first contribution, I am trying to improve the results for my home region :)**

**Comment by missinglink** [comment]
hi @binshe I believe this issue you mentioned is being tracked in https://github.com/pelias/pelias/issues/571

we are happy to help :) in order to be able to track these issues it would be best if you opened a new issue or comment on a currently open issue. this one is marked as `closed` and so will not get any more attention.
