### ISSUE TITLE
Output real street addresses in a different property

### ISSUE THREAD

**Issue by stevevance** [pelias/pelias#60]
Currently real street addresses ("121 N LaSalle Street") are output as part of a full address (with city, region, post code) in the "name" property. 

If you can reasonably determine that the "name" property actually represents an address, output it (even duplicate it) as an "address" property. 

Many objects are found by Pelias from the OpenStreetMap and Geonames datasets, but not all of them have addresses. However, they're all placed into the "name" property. 

My workflow looks to see if the "name" field contains a number. If it does, "name" is assumed to represent an address and copied to an "address" property. This would merely be a convenience feature and your tests would probably have to be more stringent than mine.

**Comment by sevko** [comment]
We currently index all addresses as points-of-interest, which means we should probably introduce an `address` type in [pelias/schema](https://github.com/pelias/schema). @missinglink 's the domain expert on OSM.

**Comment by missinglink** [comment]
hi @stevevance this work has already been done and the PR is hopefully going to get merged today.

The result is that we will be exposing a `.address` property with all records which contains more granular information about the location, eg:

```javascript
{
  "_index": "pelias",
  "_type": "osmaddress",
  "_id": "poi-address-osmnode-26489964",
  "_score": 1,
  "_source": {
    "name": {
      "default": "22 Moor Park Lane"
    },
    "address": {
      "city": "Farnham",
      "number": "22",
      "zip": "GU9 9JB",
      "street": "Moor Park Lane"
    },
    "center_point": {
      "lon": -0.779389,
      "lat": 51.219671
    },
    "alpha3": "GBR",
    "admin0": "United Kingdom",
    "admin1": "Surrey",
    "local_admin": "Farnham CP",
    "locality": "Farnham",
    "suggest": {
      "input": [
        "22 moor park lane"
      ],
      "output": "osmaddress:poi-address-osmnode-26489964"
    }
  }
}
```

I hope that we will be exposing this data via the RESTful API layer following a re-index (live in 1-2 weeks), so it should also be available as a geoJSON property to consumers of that API.

The records are duplicated for technical reasons (easier to index and retrieve from elasticsearch), so in the case of the above address record, a POI record is also created:

```javascript
{
  "_index": "pelias",
  "_type": "osmnode",
  "_id": "26489964",
  "_version": 5,
  "found": true,
  "_source": {
    "name": {
      "default": "Shepherd and Flock"
    },
    "address": {
      "city": "Farnham",
      "number": "22",
      "zip": "GU9 9JB",
      "street": "Moor Park Lane"
    },
    "center_point": {
      "lon": -0.779389,
      "lat": 51.219671
    },
    "alpha3": "GBR",
    "admin0": "United Kingdom",
    "admin1": "Surrey",
    "local_admin": "Farnham CP",
    "locality": "Farnham",
    "suggest": {
      "input": [
        "shepherd and flock"
      ],
      "output": "osmnode:26489964",
      "weight": 6
    }
  }
}
```

When retrieving the document from the RESTful API you will be able to distinguish between the address and poi records by the `layer` param; which will also allow you to filter out the specific layers you require at query time.

The information above is specific to the openstreetmap import (where we can distinguish between addresses and poi records), in regards to the geonames import I assumed that all record names were for POIs and didn't realise that there were street addresses in that dataset.

**Comment by stevevance** [comment]
@missinglink I think Pelias is the best geocoder out there right now, and it mimics the geocoder "chain" I created for myself using the geocoder-php class. 

I was using the ````layer```` property to test for addresses but it seemed that it wasn't labeling all addresses. For example, I believe ````osmnode```` and ````osmway```` can represent place features that have addresses, but it doesn't mean they actually have the address property (it depends on OSM editors). 

Do you have docs that list all the possible ````layer```` values?

**Comment by missinglink** [comment]
hey @stevevance that is really kind of you to say, thanks!

We actually have some API documentation here: https://github.com/pelias/api/wiki/API-Endpoints which explains the `layers` param options and aliases, it also lists the different layers available.

You're absolutely correct in saying that the `osmnode` and `osmway` layers used to contain both address and POI records however we did some dev work a while back to put the addresses in to a new layer called `osmaddress`, for all the reasons you mentioned.

We rebuild the full planet index roughly once per week and so I assumed this had gone live some time ago, judging by my comment here https://github.com/pelias/openstreetmap/issues/29 it probably hit production some time in February.

So, for the large part this should be solved; however looking deeper in to the issue I found some outliers which are incorrectly indexed such as: https://pelias.mapzen.com/doc?id=osmway:232045378 so I will open a new ticket to track down and fix these.

They are unfortunately due to data errors, eg: http://www.openstreetmap.org/way/232045378 you can see that the openstreetmap contributor has set the 'name' property to '102 Gloucester Place' when it should have been tagged as `addr:housenumber` and `add:street`.

**Comment by stevevance** [comment]
"You're absolutely correct in saying that the osmnode and osmway layers used to contain both address and POI records however we did some dev work a while back to put the addresses in to a new layer called osmaddress, for all the reasons you mentioned."

Can you clarify: Will POI records with addresses appear in the ````address```` layer (in addition to the ````poi```` layer)?

**Comment by missinglink** [comment]
Sorry for the late reply.

re: "Will POI records with addresses appear in the address layer (in addition to the poi layer)?"

Yes.

OSM records which are named POIs && also contain address info will be cloned, one record will be stored in the `osmaddress` layer and one with the POI name will be stored in either the `osmnode` or `osmway` layer.

When a document is 'cloned' everything remains the same except: `layer`, `id` and `name`, these 3 properties are always changed, the address `name` will be `number+street` instead of the POI name.

An example of this is the record I mentioned above `22 Moor Park Lane/Shepherd and Flock` where 2 records were created from a single OSM entry, one ends up in `osmaddress` and one in `osmnode`.

There is some duplication of the data but it serves a good purpose in that only the `suggest.input` and `name` properties are actually searchable, so you'll never get back both records for the same input.

**Comment by stevevance** [comment]
Okay, great, @missinglink! Was the PR merged that day like you said? If so, close the comment :)

**Comment by missinglink** [comment]
Yep, all merged, we are moving fast and not breaking things, sometimes hard to keep up ;)
