### ISSUE TITLE
English names for German cities 

### ISSUE THREAD

**Issue by mleginus** [pelias/pelias#605]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:
[http://pelias.github.io/compare/#/v1/search%3Ftext=hanover,%20germany](http://pelias.github.io/compare/#/v1/search%3Ftext=hanover,%20germany)

---
#### Here's what I got :scream_cat:

![image](https://user-images.githubusercontent.com/11982401/27831350-99120dba-60ca-11e7-9aa5-258ed25445c9.png)

---
#### Here's what I was expecting :sparkles:
So due to different spelling versions of Hannover city(Hanover in English), the tool is returning proper object only for German spelling version i.e., Hannover. We would like to get back the same location object also for English version Hanover. 

We can see the similar behaviour also for the following cases:
Cologne, Germany
Nuremberg, Germany

---
#### Questions:
Following some of your development and milestones - it seems that you guys are working on this issue [Alt names milestone](http://pelias.io/milestones/alt_names/index.html). 

Will the first version of alt-names miltestone resolve the mentioned case?
If yes, do you have guys estimate when the alt-names will be released?
Are there any temporary resolutions we could do on our side to resolve this one until alt-names is in place?

##### References:
[Whosonfirst record for Hannover](https://whosonfirst.mapzen.com/spelunker/id/101748819/#18/52.31709/9.63513)
[Alternative names for Hannover on Geonames](http://www.geonames.org/2910831/hannover.html)

**Comment by missinglink** [comment]
thanks for the bug report. the whosonfirst record for Hannover was missing the `name:eng_x_preferred` property, these properties are required for each alternative language so that [placeholder](https://github.com/pelias/placeholder) can find them.

I've gone and [added the English variation for Hanover, Cologne & Nuremberg](https://github.com/whosonfirst-data/whosonfirst-data/commit/9d560966dc6dafd2b74bdf87ecbd878dd63bb42c) but I'm sure there are loads more that need to be updated, either I can add them for you or you can open an issue on the whosonfirst repo so that that data is available to everyone.

regarding your link to geonames, I see that the concordance to geonames is present but the language data has not been copied across, I opened https://github.com/whosonfirst-data/whosonfirst-data/issues/849 to see what we can do about that, maybe this will save a bunch of time manually entering them.

now the data has been updated you'll just need to wait for a new build before seeing it on the production servers.

see https://github.com/pelias/api/pull/832 for more info on returning the labels in your preferred language

**Comment by mleginus** [comment]
thanks @missinglink for your quick response! We will try to feed missing data directly to whosonfirst repo in the future.
