### ISSUE TITLE
Failing geonames import

### ISSUE THREAD

**Issue by mleginus** [pelias/pelias#611]
Hey team! 

we are reimporting the latest Pelias data into our ES cluster. However, the geonames import is failing (running with 4.8.3). See the following: 

![image](https://user-images.githubusercontent.com/11982401/28012672-dd7b6000-6566-11e7-9172-530bd0fa307a.png)

When running the import with Node 6.11 - the geonames import fails on this kind of error:

![image](https://user-images.githubusercontent.com/11982401/28012822-51553f32-6567-11e7-9de9-9c01abd4155a.png)

Any ideas what could be wrong? Am I missing something?

Running on ubuntu 14.04 and this is my pelias.json config:

![image](https://user-images.githubusercontent.com/11982401/28012951-bc38f686-6567-11e7-9849-4df18318d098.png)

**Comment by missinglink** [comment]
hi @mleginus we just made some changes to `pelias/model`, could you please let me know which version of that dependency you are installing (from your `package.json`)?

In the first screenshot you can see it's trying to assign `latitude: ''` and so the model validator is throwing an error saying it's not a number. The log level is only `warn`, so you can ignore those, in the case where the source data is messed up our policy is to `warn` and skip rather than throw a `fatal`.

Everything else in that screenshot looks fine to me.

In the second screenshot, I've not seen the `Z_BUF_ERROR` before, I'm running node `v4.8.3` on my local machine. @orangejulius might have some more info on which node versions are officially supported when New York get's online later.

**Comment by missinglink** [comment]
Could you please post a screenshot of the failure message you get for node `4.8.3`?

**Comment by missinglink** [comment]
regarding node 6, I suspect (from the error message) the issue lies with the dependency called [unzipper](https://github.com/ZJONSSON/node-unzipper).

it's possible that the issue is related to https://github.com/ZJONSSON/node-unzipper/issues/17, I'll mention it in our team meeting today.

**Comment by mleginus** [comment]
@missinglink thanks for your quick response! I was running all pelias repos from production branches - so guess it was with this version of pelias model https://github.com/pelias/geonames/blob/production/package.json#L53 Trying now import with the master branches.

Regarding the failure message for node _4.8.3_, I see only a warn message and then message "shutting down admin lookup service" see the first attached screenshot.

**Comment by mleginus** [comment]
@missinglink and it fails also with the master branch code (still on _node 4.8.3_). This is my package.json file:
![image](https://user-images.githubusercontent.com/11982401/28016678-c643d30e-6575-11e7-8116-81ad2a9193c2.png)

and the same error message as in the first screenshot: 

![image](https://user-images.githubusercontent.com/11982401/28016725-01253c88-6576-11e7-8e66-f7680073bfe4.png)

**Comment by orangejulius** [comment]
Hey @mleginus,
Another possible cause is that the Geonames zip file is subtly broken, or at least made in a a way where the nodejs unzipper module has problems with it. This has happened to us frequently and seemingly randomly. We will download the geonames zip file, and it works fine with `unzip` on the command line but not in Node.js.

We don't know what the cause is but the way we've worked around it is to write a [nodejs script that reads the zip file in but does nothing with it](https://github.com/pelias/geonames/pull/171). Then we run that script every few hours and only use downloads that passed that check. Its definitely not ideal but since the zipfile is only sometimes corrupt in the eyes of `unzipper` it has worked well enough.

Try redownloading the geonames data, and if it still fails, try again a few hours later, and if that fixes it then you know you're running into the same issue.

**Comment by mleginus** [comment]
@orangejulius and @missinglink thanks for your help! It seems that the latter one was the case - I redownloaded the file and it works.
