### ISSUE TITLE
Batch geocoding

### ISSUE THREAD

**Issue by hkrishna** [pelias/pelias#69]
Pelias API should be able to batch process/geocode large datasets. 

Convert addresses or locations into latitude-longitude coordinate pairs:
1. One address per line, up to a few hundred addresses maybe?
2. Output should contain lat/lon and maybe even include the input address (per line)
3. Include failed geocodes in the bulk output?
4. Ability to specify Field Delimiter - `,` `|` `;` etc

**Comment by aplannersguide** [comment]
It would be great if pelias allowed the user to specify the cap on the batch geocoding so that it could be adjusted on an as needed basis. For example, I have 100k+ addresses in my 311 dataset that is geocoded to the street intersection that I would love to have at the actual address. 

Besides all that, the features listed above great!

**Comment by orangejulius** [comment]
This is still an important feature that we want to add in the coming months. Over time we've learned more about batch and there's one important consideration.

Right now at least, the vast majority of the response time for search queries (less so reverse after pelias/api#549) is spent in Elasticsearch doing the actual work for the query. Elasticsearch also has the unfortunate property (at least how we've configured it, perhaps we can do better) that throwing too many requests at it causes _all_ requests to slow down, rather than a backlog to develop that only penalizes queries that come in later. These two factors mean that a simple endpoint that takes in many normal queries and sends them all off to Elasticsearch will probably be _slower_ than simply running a bunch of individual queries a few at a time. :(

So, an important additional requirement of a batch endpoint is that it provides some sort of ability to handle queuing of queries, and spreads out the load over time. Ideally it would also be able to throttle up/down based on how the Elasticsearch cluster is doing.

It would be awesome if we had the ability to allow for bulk requests of millions of queries, and we would send them off to Elasticsearch as there was headroom, but individual queries would go right through and if we had lots of individual queries, the bulk requests would slow down. This would ensure the Elasticsearch cluster was never overloaded, but always doing bulk work if possible.

**Comment by aggied** [comment]
bump!

**Comment by orangejulius** [comment]
Just to leave an update here, we have some internal projects happening to help with batch requests. No ETA yet but there is progress being made.

**Comment by easherma** [comment]
[relevant?](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/search-multi-search.html)

**Comment by orangejulius** [comment]
@easherma oh wow, I never knew that existed, but hoped it did. It will definitely be helpful for a bulk endpoint and possibly for general use, since we may start running multiple Elastisearch queries as part of a single Pelias request someday (no firm plans, but we've discussed reasons it may be helpful many times).

**Comment by aggied** [comment]
@orangejulius and @easherma thanks for the posts. @orangejulius would look forward to any updates/ETA you can share

**Comment by orangejulius** [comment]
Over the years we've determined that batch geocoding is not really an API problem, it's a software infrastructure and queueing problem.

For a while now we have had the [scripts-batch-search](https://github.com/pelias/scripts-batch-search) package which handles the queuing side, using existing API endpoints and respecting Pelias HTTP responses like 500, 502, 429, etc. I think that's all we need for now. Anything else is up to whoever is running a given Pelias instance.
