### ISSUE TITLE
libpostal service disabled

### ISSUE THREAD

**Issue by gibranparvez** [pelias/pelias#709]
I've been using Pelias and ES just fine for  weeks until today.

I did a standard download and import (from scratch, i cleared all volumes/containers/images from my desktop Docker instance) and ran a search on `:4000/v1/search?text=washington`
and now I get 

`    "errors": [
      "libpostal service disabled"
    ]`

for all queries, with no results. I've rebuilt the images repeatedly and re-downloaded but with no luck.

---------------

Does anyone have any suggestions? I'm currently going through and running services non-daemonized to find the actual stack trace. Haven't been successful yet. Thanks!

**Comment by sweco-semhul** [comment]
It is a bit confusing, libpostal have moved into a micro service. Now called through http requests from Pelias API.
So in a docker setup its moved into its own container, found in the libpostal-service branch in https://github.com/pelias/dockerfiles

Seen in the compose file in that branch. https://github.com/pelias/dockerfiles/blob/libpostal-service/docker-compose.yml#L34

And you also need to configure it in pelias.json like this, https://github.com/pelias/dockerfiles/blob/libpostal-service/pelias.json#L26

**Comment by orangejulius** [comment]
Hey @gibranparvez,
@sweco-semhul is correct. We're moving libpostal into its own service which helps keep the API itself lean. It starts up faster and is easier to scale.

However, those changes shouldn't yet have made it into the production branches, which is what the default Docker images are based on. Once it's merged, we will indeed update the documentation everywhere so its a bit easier to follow.

Since you're using it, please let me know how it works out. It's already live on geocode.earth and looks good, but of course more data points are welcome :)

**Comment by orangejulius** [comment]
Also, there is now a PR for the libpostal service change in the dockerfiles repo: https://github.com/pelias/dockerfiles/pull/42

**Comment by orangejulius** [comment]
I'm marking this closed since we have better docs now, and the change will soon be going to production. Feel free to comment or re-open if there are any questions!

**Comment by MiesSuomesta** [comment]
I get this error now. I've tried to google but no luck. How do I resolve this ?

**Comment by MiesSuomesta** [comment]
![image](https://github.com/pelias/pelias/assets/32951624/71a1fb6e-b874-4012-a951-ec3edd2c70c6)
