### ISSUE TITLE
Confounding Frankfurt (Main) and Frankfurt (Oder)

### ISSUE THREAD

**Issue by SebAlbert** [pelias/pelias#743]
Hey team! 

I was (indirectly) using your awesome geocoding engine (via OpenRouteService) when I noticed something interesting.
Let me tell you more about it.
As I cannot afford to read through all the existing issues, I hope this is not a duplicate.

---
#### Here's what I did :innocent:
I used OpenRouteService (maps.openrouteservice.org) to find a way to a particular address in Frankfurt (Main). My example: Pfarrer-Perabo-Platz

---
#### Here's what I got :scream_cat:
In the autocomplete search results, there were entries with the postal code of that address in Frankfurt (Main) (60326), but naming Frankfurt (Oder) somewhere in the hierarchy (which is a completely different city several hundreds of kilometers away)

---
#### Here's what I was expecting :sparkles:
seeing Frankfurt (Main) only, since this particular address does not exist in Frankfurt (Oder), especially not with that postal code

---
#### Here's what I think could be improved :trophy:
What I further did was fling the issue with OpenRouteService, but they pointed me "upstream" to this library/service (https://github.com/GIScience/openrouteservice-app/issues/244)

**Comment by missinglink** [comment]
Thanks for the report @SebAlbert, please see the ticket above I've opened with our data provider.

On that ticket you can click the links to the `spelunker` in order to view the geometry data and it's attributes.

If you have any further information, please add a comment there.

Once the data issue is resolved it will be absorbed into future builds without any additional action required on our end.
