### ISSUE TITLE
Custom data support

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#747]
A frequent user request is loading custom data into Pelias. This data wouldn't be used by Pelias for geocoding but would help users by bringing data specific to their domain into Pelias responses for easy access.

There are great examples of uses cases in issues like https://github.com/pelias/pelias/issues/516 and https://github.com/pelias/model/issues/73.

## Requirements
We would want to build this in such a way that it would not impact Pelias in general and would avoid any significant impact on Pelias performance or resource usage when enabled.

* The field we store custom data in should *NOT* be indexed by Elasticsearch, but only stored. (see [here](http://elasticsearch-users.115913.n3.nabble.com/What-does-it-mean-to-quot-store-quot-a-field-td3514176.html) for the difference).
* Realistically, there may have to be a limit on the amount of custom data stored. A good best practice might to be to store only an ID or other reference number in Pelias, and keep the full data somewhere else

## Possible design

[pelias/schema](https://github.com/pelias/schema/) could include a new `dynamic_template` that allows for fields of any name to be added in a `custom_data` object, and configuring them properly. I think the code would look like this:
``` 
customData: {
    path_match: 'custom_data.*',
    match_mapping_type: 'string',
    mapping: {
      type: 'string',
      index: 'no'
    }
}
```

We can then add support in [pelias/api](https://github.com/pelias/api) for reading from those fields and returning them in responses.

An open question is whether we'll want to add support for custom data on all endpoints, or only on the `/v1/place` endpoint. Support on all endpoints would be more convenient, but could lead to large response bodies. The `/v1/place` endpoint was also originally envisioned as an endpoint for getting more detailed information about a given record, so it could be a good fit here.

**Note:** This implementation _won't_ support custom administrative data or administrative records.

**Comment by jgmarce** [comment]
@orangejulius I suggest that custom data should be an object so a complex JSON structure may be inserted.

**Comment by jgmarce** [comment]
@orangejulius I wonder why you think that this custom data field should not be indexed?

**Comment by 11sma** [comment]
@jgmarce seems that the reason is about performance, more fields to index with a possible complex data (as JSON you propose) may increase the times of search/response

**Comment by 11sma** [comment]
Hi, I arrived here because I'm working in attach custom-data at the document pelias returns. The way I'm searching is adding a custom field inside.

I see at least 3-4 issues talking about this but all of them redirects here. I try to understand, with no success results, how to modify the schema to return something like this:

	"type": "FeatureCollection",
	"features": [{
		"type": "Feature",
		"geometry": {
			"type": "Point",
			"coordinates": [-5.91554, 37.160491]
		},
		"properties": {
			"id": "0000000001",
			"gid": "custom-data:venue:0000000001",
			"layer": "venue",
			"source": "custom-data",
			"source_id": "0000000001",
			"name": "Name of Custom Venue",
			"confidence": 0.979,
			"distance": 839.116,
			"accuracy": "point",
			"label": Custom Data",
			**"custom-field": "custom-data"**
		}
	}, {
		"type": "Feature",
		"geometry": {
			"type": "Point",
			"coordinates": [2.089117, 41.561086]
		},
		"properties": {
.......

In this case for some values I need to show the custom-field and the custom-data associated (I don't need to index, only to show the field) if data not exists, the "custom-field" can be showed without problem.

Some idea about this problem?

Thanks to @orangejulius and @missinglink (helps me some days ago) and everyone who can give me some clue :)

**Comment by orangejulius** [comment]
Hi everyone!

We just finished merging all the PRs required for custom data support. It's now possible to add custom records that have fields that don't correspond to the default Pelias schema using the [csv-importer](). In particular, see the [custom data section](https://github.com/pelias/csv-importer#custom-data) of the CSV importer readme for how it works.

We'd love feedback from anyone who tries it out.

**Comment by bboure** [comment]
@orangejulius I have a question regarding this feature. 
As I understand, this features allows importing custom **records** into pelias from a CSV?
My use case is the following: I want to extend existing pelias records (from OSM) and **add** custom addendum data.

Common examples for my use case would be: 
- add an image url (in order to show it later in autocomplete for example).
- store external references (ids) to other resources related to a venue
- etc

I could imagine having an custom sqlite database and add a custom stream in the importers (even at the cost of import time).

Is that something that can currently be done?

thanks

**Comment by missinglink** [comment]
Hi @bboure what you described is already possible using the `addendum` feature.

An example is [this PR which landed today](https://github.com/pelias/openstreetmap/pull/528), this exposes `operator` and `brand` information from OSM in the addendum.

However you can put whatever information you like in the addendum :rocket:

**Comment by missinglink** [comment]
Here's an example of a query which returns addendum information in the response:
https://pelias.github.io/compare/#/v1/search?size=1&text=TXL&debug=0

**Comment by bboure** [comment]
Thanks @missinglink 
Does that mean that if I want to customize the addendum I must extend/override the `tream/addendum_mapper.js` file ?

**Comment by orangejulius** [comment]
That's right. We support adding completely new custom records through the [csv-importer](https://github.com/pelias/csv-importer), and bringing in existing data from OSM through the OSM importer, but without making changes to the OSM importer, you can not bring in arbitrary data of your own through existing OSM records.
