### ISSUE TITLE
Falling back to suburb when the unit number isn't matched

### ISSUE THREAD

**Issue by NickStallman** [pelias/pelias#753]
Hey team! 

I've been evaluating Pelias for work (real estate industry) and it looks absolutely fantastic.

We already have a pre-existing database of geocoded addresses so after building my database I did a sanity check by re-geocoding part of the database and comparing the distance between old and new points to ensure accuracy.

One pattern emerged which caused accuracy to be far lower than expected, unit numbers could not be found and the fallback was to go to the street or worse the suburb. If I manually remove the unit number then an exact match is returned.

The following queries are real (i.e. someone at some point entered them in) so they aren't guaranteed to be clean, but should be able to still return good results.

---
#### Here's what I got :scream_cat:
https://pelias.github.io/compare/#/v1/search%3Ftext=11/1015%20Nudgee%20Road,%20Banyo,%204014,%20QLD,%20Australia
https://pelias.github.io/compare/#/v1/search%3Ftext=2+3/32%20Dixon%20Street,%20Strathpine,%204500,%20QLD,%20Australia
https://pelias.github.io/compare/#/v1/search%3Ftext=(Unit%203)/30%20Dan%20Rees%20Street,%20Wallsend,%202287,%20NSW,%20Australia

---
#### Here's what I was expecting :sparkles:
https://pelias.github.io/compare/#/v1/search%3Ftext=1015%20Nudgee%20Road,%20Banyo,%204014,%20QLD,%20Australia
https://pelias.github.io/compare/#/v1/search%3Ftext=32%20Dixon%20Street,%20Strathpine,%204500,%20QLD,%20Australia
https://pelias.github.io/compare/#/v1/search%3Ftext=30%20Dan%20Rees%20Street,%20Wallsend,%202287,%20NSW,%20Australia

---
#### Here's what I think could be improved :trophy:
Since properties with unit numbers are typically all in very close proximity of each other, and data quality may be lower (or missing) for each individual unit, it makes sense to fall back to the street number first to see if it can be matched.
This would result in much closer geocodes for these cases.

**Comment by missinglink** [comment]
ref: https://auspost.com.au/content/dam/auspost_corp/media/documents/Appendix-01.pdf

sections:
- Form of address for flats, units or apartments 
- Use of the solidus (/)

**Comment by missinglink** [comment]
hi @NickStallman, the issue lies with our parsing library `libpostal` which is unfortunately not very actively maintained.

I've put in a patch which works around this issue (linked above) which will need to be reviewed and tested before release.

Feel free to pull that code and testing it out, if you are using our docker setup then you can pull a testing image from https://hub.docker.com/r/pelias/api/tags/

**Comment by missinglink** [comment]
@NickStallman we have merged the code and are rolling a fix out to production now, it should be available in the next hour or so.

Please let us know if it fixes your issues!

**Comment by NickStallman** [comment]
Awesome! That looks like it's done the trick. It's raised the exact matches for my sample database from 52% to 66% which is fantastic.

I think a lot of the remaining fallbacks are garbage user provided data but I'll continue doing some checks and verify there aren't any further low hanging fruit.

Thanks @missinglink for the incredibly fast fix!

**Comment by b-may** [comment]
@missinglink So is libpostal a casualty of MapZen shutting down? I thought libpostal was an independent project, but see its under MapZen. Any idea what the future holds for it? Seems like a critical piece of software.

**Comment by missinglink** [comment]
@b-may you are correct on saying that libpostal is a separate project.

Libpostal is maintained by Al Barrentine, the initial funding for the project and his OpenVenues work came from Mapzen.

We worked with Al after its release to try and improve libpostal parsing results based on Pelias bug reports, this resulted in an improved model.

That was some time ago, and Al has probably moved on to new things to pay the bills.

It's an open source project and so I hope someone else will pick it up and continue to develop it.

One tricky thing about libpostal is the machine learning model, which none of our team are particularly familiar with, and the documentation is a bit thin on, so it really requires someone with a machine learning background.

It's a hot topic for us internally because we depend on it for our work, we have a few options we're discussing and fallback options just in case.

My ideal solution would be that an individual or organization continues to maintain and develop it.

If someone steps up to do that, we can probably find funding to pay for some of that work.
