### ISSUE TITLE
Pelias + Oracle

### ISSUE THREAD

**Issue by OverlordSargon** [pelias/pelias#771]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

I wonder to know if exists some way for Pelias to work with **Oracle DB.** :innocent:
I need execute geocoding with data very different from **OSM**. All needed data about geoobjects now placed in ordinary Oracle DB table. 
May be exists some way to use **Pelias + Oracle Golden Gate** or **Pelias + Oracle Spaital**

Thank you in advance.

**Comment by orangejulius** [comment]
Hi @OverlordSargon,
It's extremely unlikely Pelias will ever support Oracle directly. What you most likely want to do is export data from Oracle into a CSV file compatible with the [csv-importer](https://github.com/pelias/csv-importer).

I'm going to close this issue, since there's nothing to be done for the Pelias project here. If you have further specific needs, particularly around importing custom data, feel free to shoot us an email at hello@geocode.earth, and we'll see how we can help.
