### ISSUE TITLE
Village Rumbak (Pakistan) not found

### ISSUE THREAD

**Issue by pathmapper** [pelias/pelias#782]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:
http://pelias.github.io/compare/#/v1/search%3Ftext=Rumbak

---
#### Here's what I got :scream_cat:
No feature
{
  "geocoding": {
    "version": "0.2",
    "attribution": "https://geocode.earth/guidelines",
    "query": {
      "text": "Rumbak",
      "size": 10,
      "private": false,
      "lang": {
        "name": "English",
        "iso6391": "en",
        "iso6393": "eng",
        "defaulted": false
      },
      "querySize": 20,
      "parser": "libpostal",
      "parsed_text": {
        "city": "rumbak"
      }
    },
    "engine": {
      "name": "Pelias",
      "author": "Mapzen",
      "version": "1.0"
    },
    "timestamp": 1550310052120
  },
  "type": "FeatureCollection",
  "features": []
}

---
#### Here's what I was expecting :sparkles:
https://spelunker.whosonfirst.org/id/1193265185/

https://www.openstreetmap.org/node/4415325512

---
#### Here's what I think could be improved :trophy:
Make the village Rumbak (Pakistan) available in Pelias.

**Comment by orangejulius** [comment]
Hi @pathmapper,
It seems the ever growing amount of open data has now solved this problem for us. Our latest builds now do show  Rumbak, Pakistan. Two of them actually, so I'm curious if they are both correct.

<img width="372" alt="Screen Shot 2019-04-16 at 4 35 21 PM" src="https://user-images.githubusercontent.com/111716/56250808-c08de980-6065-11e9-8c8a-07f244a5ac4d.png">

Since I hope at least one of them is right, I think we can close this issue, but let me know if you have further information.
