### ISSUE TITLE
Retrieve list of addresses from Pelias DB

### ISSUE THREAD

**Issue by williamflynt** [pelias/pelias#795]
_Apologies if this isn't the place for questions - I found no other place._

**Question:**

Is there a way to extract the full list of known addresses from across the data sets that Pelias has by default?

We are trying to create some "fabric" for stitching together several applications we have going or under development and these lists are not cheap from vendors.

**Comment by missinglink** [comment]
Hi William,

We use `openaddresses` and `openstreetmap` as sources for address data.

It's fairly simple to download and process `openaddresses` since they are CSV format, for ,`openstreetmap` I wrote a tool called `pbf2json` which you can use to extract just the addresses from an osm.pbf file.

AFAIK It's not really possible to 'dump' addresses out of elasticsearch like you would with a relational database, although I'm sure it could be done using some sort of findall query and an iterator, we've never tried it.

There are a bunch of tools we've developed for importing these datasets which you could quite easily modify to export the data to disk instead of inserting in to elasticsearch.

I'd also suggest having a look at the `pelias/interpolation` repo because it ingests all the known addresses.

Lastly, if you'd like something built for you, you can contact the core team via [geocode.earth](http://geocode.earth)

**Comment by williamflynt** [comment]
Thanks for this answer!

I think what we'll do is pull from ES -- I'm looking into using `scroll` and iterating.
