### ISSUE TITLE
Internal Server Error for autocomplete: invalid value, value must be valid js Variable

### ISSUE THREAD

**Issue by Joxit** [pelias/pelias#829]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:

I just had this error on our servers for a autocomplete of [Eindhoven ̈](https://pelias.github.io/compare/#/v1/autocomplete%3Ftext=Eindhoven%20%CC%88). I don't know what is the last character and if it's a typo or not... But it seems to break the API.

---
#### Here's what I got :scream_cat:

The response from the API:
```json
{
    "error": "invalid value, value must be valid js Variable"
}
```

The stacktrace: 
```
2019-10-15T14:04:40.899Z - info: [api] pelias_parser response_time=7, text=Eindhoven ̈, parser=pelias, solutions=1, text_length=11
2019-10-15T14:04:40.903Z - debug: [api] [lang] 'nl' via 'querystring'
2019-10-15T14:04:40.908Z - error: [api] Error: `Error: invalid value, value must be valid js Variable`. Stack trace: `Error: invalid value, value must be valid js Variable
    at Variable.set (/pelias/api/node_modules/pelias-query/lib/Variable.js:25:11)
    at adminFields.forEach.field (/pelias/api/query/view/admin_multi_match_first.js:41:36)
    at Array.forEach (<anonymous>)
    at /pelias/api/query/view/admin_multi_match_first.js:39:17
    at /pelias/api/node_modules/pelias-query/layout/FilteredBooleanQuery.js:30:22
    at Array.forEach (<anonymous>)
    at Layout.render (/pelias/api/node_modules/pelias-query/layout/FilteredBooleanQuery.js:28:17)
    at generateQuery (/pelias/api/query/autocomplete.js:189:17)
    at controller (/pelias/api/controller/search.js:29:27)
    at Layer.handle [as handle_request] (/pelias/api/node_modules/express/lib/router/layer.js:95:5)`.
```

---
#### Here's what I was expecting :sparkles:

A GeoJSON ?

---
#### Here's what I think could be improved :trophy:

This is a reminder, to not forget it.

**Comment by missinglink** [comment]
very weird!
https://en.wikipedia.org/wiki/Diaeresis_(diacritic)

**Comment by missinglink** [comment]
oh interesting, it's a 'combining' unicode character, so it 'joins' with the previous character... except when its a space...

```
➜  trimet-docker git:(pelias_parser) ✗ echo -e 'm\u0308'
m̈

➜  trimet-docker git:(pelias_parser) ✗ echo -e 'm \u0308'
m ̈
```

**Comment by missinglink** [comment]
the error message is coming from here https://github.com/pelias/query/blob/9a852334aec1170900c3db6f5662f0db66a148f7/lib/Variable.js#L25

**Comment by missinglink** [comment]
@Joxit I think the fix for this is to change https://github.com/pelias/api/blob/master/query/view/admin_multi_match_first.js#L41

From `tokens.slice(0, -1)` to `tokens.slice(-1)`

**Comment by Joxit** [comment]
What we can do is change the code here https://github.com/pelias/api/blob/d0cf44f36f68472185d4d20c7b545ac214e4f160/query/view/admin_multi_match_first.js#L23 to 
```js
    var tokens = vs.var('input:' + valid_admin_properties[0]).get().split(/\s+/g).filter(s => s.length > 0);
```

**Comment by missinglink** [comment]
okay so this is a bit complex but I'll have a crack at explaining it.

Unicode marks can have a 'normalized' form and a 'denormalized' form.

```javascript
String.fromCharCode(239)
"ï"

String.fromCharCode(105) + String.fromCharCode(776)
"ï"
```

here you can see that the code point `239` (latin small letter i with diaeresis) is equivalent to `105` (latin small letter i) *plus* `776` (combining diaeresis).

now I saw 'equivalent' because they are not equal:

```javascript
String.fromCharCode(239) == (String.fromCharCode(105) + String.fromCharCode(776))
false
```

but! even though [Javascript has a Unicode problem](https://mathiasbynens.be/notes/javascript-unicode) there is a light at the end of the tunnel, namely `String.normalize`!

so we can do this:

```javascript
(String.fromCharCode(105) + String.fromCharCode(776)).normalize('NFC').charCodeAt(0)
239

String.fromCharCode(239) == (String.fromCharCode(105) + String.fromCharCode(776)).normalize('NFC')
true
```

the issue we're having above is due to a 'misuse' of combining mark 776, it only really makes sense for some character combinations.

so if I try to combine an `m` with a `combining diaeresis` I can....
BUT! (and this is the important part) I cannot decompose it, because that form doesn't exist as a single code point:

```javascript
(String.fromCharCode(109) + String.fromCharCode(776)).split('').map(c => c.charCodeAt(0))
[109, 776]

(String.fromCharCode(109) + String.fromCharCode(776)).normalize('NFC').split('').map(c => c.charCodeAt(0))
[109, 776]
```

and this is the issue we are suffering from here, although it's not immediately obvious the input text contains a decomposed form of a `space` combined with `combining diaeresis`:

```javascript
' ̈'.split('').map(c => c.charCodeAt(0))
(2) [32, 776]
```

and normalizing it doesn't do anything because there is no "space with combining diaeresis" Unicode codepoint to decompose to, so javascript just leaves the codepoints as they were and the combining mark remains in the string:

```javascript
' ̈'.normalize('NFC').split('').map(c => c.charCodeAt(0))
(2) [32, 776]
```

so! I think the best solution is to:
- convert all inputs to `NFC` (Normalization Form Canonical Composition) form
- strip all remaining 'combining marks'

the nett effect of this is that denormalized forms with no normalized equivalent will be converted to their 'base' form and any incorrectly used combining marks will be stripped from the test:

```javascript
(String.fromCharCode(109) + String.fromCharCode(776)).normalize('NFC').replace(/([\u0300-\u036F])/g,'').split('')
["m"]

(String.fromCharCode(105) + String.fromCharCode(776)).normalize('NFC').replace(/([\u0300-\u036F])/g,'').split('')
["ï"]

(String.fromCharCode(32) + String.fromCharCode(776)).normalize('NFC').replace(/([\u0300-\u036F])/g,'').split('')
[" "]
```

we should probably do this as early as possible in the middleware (most likely in the text sanitizer), the added benefit of this is that any other calculations which depend on properties like `.length` or functions like `.slice()` will perform correctly without any modification:

```javascript
(String.fromCharCode(105) + String.fromCharCode(776)).length
2

(String.fromCharCode(105) + String.fromCharCode(776)).normalize('NFC').length
1
```

```javascript
(String.fromCharCode(32) + String.fromCharCode(776)).length
2

(String.fromCharCode(32) + String.fromCharCode(776)).normalize('NFC').length
2

(String.fromCharCode(32) + String.fromCharCode(776)).normalize('NFC').replace(/([\u0300-\u036F])/g,'').length
1
```

**Comment by missinglink** [comment]
@orangejulius sounds like a blog post?

**Comment by missinglink** [comment]
https://xkcd.com/1857/

**Comment by Joxit** [comment]
Wouah, that's a awesome analyse and should be definitely a blog post.

```js
> 'm͈̼̐͋͂ͫi̞̺͖̣ͪͭͤs̠̹͑̊ͧ͑̓͐̚͟ş͉̠̱̒̈͑ͬ̚̚i̡̩̥̭̓̊́ͦͯńg͇̞̈́̓l̙ͫ͊ͨͯͨ̑ͧ͞i͉͉̰n̡͚͔̂̍̀̇ͫͦ̚kͭͬ͌̈'.length
93
```

Hum... It's like the TARDIS! It's bigger on the inside!

**Comment by missinglink** [comment]
here's a PR to address the unicode stuff mentioned in the comment above
https://github.com/pelias/api/pull/1373

I'm yet to test it actually resolves this specific issue...

**Comment by missinglink** [comment]
agh yep, that PR fixes this issue 🍾

**Comment by arne-cl** [comment]
> Wouah, that's a awesome analyse and should be definitely a blog post.
> 
> ```js
> > 'm͈̼̐͋͂ͫi̞̺͖̣ͪͭͤs̠̹͑̊ͧ͑̓͐̚͟ş͉̠̱̒̈͑ͬ̚̚i̡̩̥̭̓̊́ͦͯńg͇̞̈́̓l̙ͫ͊ͨͯͨ̑ͧ͞i͉͉̰n̡͚͔̂̍̀̇ͫͦ̚kͭͬ͌̈'.length
> 93
> ```
> 
> Hum... It's like the TARDIS! It's bigger on the inside!

@Joxit How do you get to a result of 93? Chromium, Firefox and Node all tell me the length is 84.

**Comment by Joxit** [comment]
```js
> 'm͈̼̐͋͂ͫi̞̺͖̣ͪͭͤs̠̹͓͇͔̞̳͑̊ͧ͑̓͐̚͟ş͉̠̱͖͎̒̈͑ͬ̚̚i̡̩̥̭̓̊́ͦͯńg͇̞̈́̓l̙ͫ͊ͨͯͨ̑ͧ͞i͉͉̰n̡͚͔̬̂̍̀̇ͫͦ̚ͅkͭͬ͌̈' === 'm͈̼̐͋͂ͫi̞̺͖̣ͪͭͤs̠̹͑̊ͧ͑̓͐̚͟ş͉̠̱̒̈͑ͬ̚̚i̡̩̥̭̓̊́ͦͯńg͇̞̈́̓l̙ͫ͊ͨͯͨ̑ͧ͞i͉͉̰n̡͚͔̂̍̀̇ͫͦ̚kͭͬ͌̈'
false
```
Copy paste this anywhere, the result will be `false`... Copy from your terminal/console and paste it again... The result will be `true` :sweat_smile:.
