### ISSUE TITLE
[Documentation] Writing an importer for a custom dataset

### ISSUE THREAD

**Issue by hkrishna** [pelias/pelias#83]
It would be nice to have documentation around writing a new importer or how to re-use some of our existing importers to import custom dataset. 

It would be worthy to note the required changes to other repos including schema and API to get the custom dataset/type flow through pelias. For example, if we add a new custom dataset called 'test_xyz' we need to add 'test_xyz' to [api/helper/layers.js](https://github.com/pelias/api/blob/master/helper/layers.js) and [api/queries/indeces.js](https://github.com/pelias/api/blob/master/query/indeces.js) to get the API to pick up the new layer. We need to add it to schema mapping as well. 

Lets put this in a document `write_a_new_importer.md` perhaps? 

@flotpk was trying to extend the open-addresses importer to work with a custom dataset and ran into issues. This proposed document might be helpful. does this sound reasonable?

**Comment by flotpk** [comment]
yes, certainly nice to have this guide for anyone who wish to upload custom dataset.  it's painful trying to search through documentation from different pelias modules and found there isn't any...   what I did is trial and error using the exsting openaddresses importer and managed to upload some test data. 

Quick summary of what I did:

1) Step 1 : using scripts from pelias-schema module:
* drop the index
* edit schema.js with new test doc
* recreate index 
(Note: still unclear if I need to follow exactly the same schema in order to get /suggest api works)

2) Step 2 : download and edit openaddresses module
* add the new data file path to the config
* edit lib/import_pipelines.js with right csv file header and setting the correct record.<column name> to the doc
* run import to load data into elasticsearch
Note: would be nice if there are some mapping guideline of what type of data should be loadded to which field of the doc

Step 3 : add in the new custom type to api/helper/layer.js and api/queries/indeces.js to get /search api works

Note: there may be some other setting which I need to fine tune as when perform /suggest and /suggest/nearby, I only get one result returned (lot's more when I do full text search) and doesn't get results from within 50km !?!?

**Comment by hkrishna** [comment]
Thanks @flotpk for your summary. What do you mean by following the same schema in order to get /suggest api to work?

Mapping guideline - I think the field types in [pelias/schema](https://github.com/pelias/schema/tree/master/mappings/partial) partial mappings is self explanatory however maybe we could add something to the README. @sevko thoughts?

Currently, there is no other setting which would let ```/suggest``` get results outside of 50km radius. There is an [open issue](https://github.com/pelias/api/issues/110) to let suggest take a bbox param and get results from within that bounding box.

**Comment by sevko** [comment]
@flotpk , are you referring to what type of data belongs in the fields of [pelias-model](https://github.com/pelias/model) `Document`s? The object methods need to be a bit better documented, but the current README seems fairly comprehensive.

**Comment by flotpk** [comment]
@hkrishna, apologise for the confusion - with more read up on elasticsearch suggest - I would think previously my /suggest doesn't work for the custom layer is due to the type being created doesn't have 'suggest'  field at all.  

@sevko, yes, I am referring to what type of data belongs in the fields of pelias-model Document's column.  When first started with the importer, I am pretty confused with admin0, admin1, admin2 (as the importer I use - openaddresses - doesn't have any admin info).  And why do I need name.default and name.alt -> I tried to have only name and get some validation error where it looks for name.default.  

I am still pretty confused with whether /search or /suggest only do search based on name.default ??

**Comment by sevko** [comment]
Right, those aren't intuitive at all. We'll start improving our documentation project-wide soon, and thoroughly explaining things like that is on the roadmap.

**Comment by missinglink** [comment]
@flotpk currently `/search` only [targets name.default](https://github.com/pelias/api/blob/master/query/search.js#L28) but `/suggest` targets any of the values in the `.name` object.

**Comment by dianashk** [comment]
Closing in favor of pelias/pelias#525
