### ISSUE TITLE
Cities not showing on reverse geocoding

### ISSUE THREAD

**Issue by timersys** [pelias/pelias#846]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

I did my own install of Pelias full planet and when I tried reverse geocoding I see that the city is not returned. Even the neighborhood, but no mention to the city on any layer. I thought it was something that failed on my install but I can't see the city neither on the demo page

---
#### Here's what I did :innocent:
https://pelias.github.io/compare/#/v1/reverse%3Fpoint.lat=-38.0045&point.lon=-57.5439

It should mention the city Mar del Plata somewhere , I can find it on providers https://spelunker.whosonfirst.org/id/421169051/

**Comment by missinglink** [comment]
Hi @timersys,

The reason the WOF record you linked isn't showing up is because it's a point.

The spelunker is a bit confusing as it's showing a blue polygon of the parent, the actual record is a point, which you can confirm from the area being 0.

We currently don't support 'buffering' point polygons into circle but we're planning to add that soon.
https://geocode.earth/blog/2020/advanced-spatial

In the meantime it might be worth opening an issue at the whosonfirst-data repo to highlight the issues of poor coverage in Argentina

**Comment by missinglink** [comment]
The polygon coverage doesn't seem to be very good in OSM either:
https://spatial.synergy.io/explore/pip#10/-37.987373/-57.565677

OSM does have this: https://www.openstreetmap.org/relation/3402727

**Comment by missinglink** [comment]
This is a good place to start: https://github.com/whosonfirst-data/whosonfirst-data/search?q=argentina&type=Issues

**Comment by timersys** [comment]
Thanks for the fast reply. I'm not sure what you mean by point, I searched by coordinates and the right locality showed to me.
<img width="699" alt="Screen Shot 2020-02-26 at 14 22 46" src="https://user-images.githubusercontent.com/1206915/75370285-9fac3c80-58a3-11ea-954c-669ee67bb492.png">

But I guess that if this is a data issue, pelias is not for me as I need something reliable at city label which seems the most basic for gps coordinates.

**Comment by missinglink** [comment]
Here's a link to that feature on GitHub https://github.com/whosonfirst-data/whosonfirst-data-admin-ar/blob/master/data/421/169/051/421169051.geojson

What I meant was that geometry is of type 'point' and so it's difficult to accurately associate it with nearby addresses/venues etc.

Usually we have polygons and if the address/venue is inside the polygon then we are sure it is from that city.

![Screenshot_20200226-205837__01](https://user-images.githubusercontent.com/738069/75382490-dea9b480-58da-11ea-9cd9-d18624248fa8.jpg)

**Comment by missinglink** [comment]
Regarding your defeated comment, if you look in other countries you'll find that the coverage is better.

The current coverage in whosonfirst is based on which governments publish their data openly, many don't, and some areas are mapped better than others.

The Pelias project is about using the best open data available and publishing all the code open-source, as such it's the best choice for a Gratis and Libre geocoder.

If you're looking for a solution which has near perfect coverage then Google Maps is probably right for you, they offer a very different product, it's closed-source, propriety and expensive, but they've spend hundreds of millions of dollars collecting data, which they don't share with anyone else.

Our philosophy is that if there is an issue then we figure out a way to fix the problem so that everyone who comes after us can benefit from our work.

https://geocode.earth/blog/2020/virtuous-cycle

**Comment by timersys** [comment]
Thanks for all your feedback and prompt responses.
