### ISSUE TITLE
bbox parameter isn't working properly

### ISSUE THREAD

**Issue by stevevance** [pelias/pelias#85]
http://pelias.mapzen.com/search?input=half%20acre&lat=41.809148&lon=-87.618538&bbox=41.430,-88.30,42.198,-87.47&layers=poi,address

This is a typical search I would be using on my app. If I remove the bounding box parameter then I get the results I expected. 

I haven't changed my code, but the results I expected are not returning.

**Comment by mtmail** [comment]
The `bbox` parameter needs `southwest_lng,southwest_lat,northeast_lng,northeast_lat`. Based on your `lat` and `lng` values it looks like you mixed up the coordinates.

https://github.com/pelias/api/blob/master/DOCS.md

**Comment by stevevance** [comment]
@mtmail that worked thank you. 

Do you know when the last time OSM address imports were done? I added [a new POI in OSM](http://www.openstreetmap.org/node/3463649049) and it hasn't shown up in Pelias since.

**Comment by mtmail** [comment]
Not sure, I'm not part of the mapzen team and don't have access to the servers/data. Adding @missinglink who did the last change to the pelias/openstreetmap repository.

Your code was probably working fine until a couple of days ago. I see the API code for the bbox changed recently. https://github.com/pelias/api/pull/117

**Comment by missinglink** [comment]
@stevevance your pub isn't in the live db... yet... it's a combination of the `planet.pbf` file being cut (roughly) [weekly](http://planet.osm.org/pbf/) and our build cycle (generally) coinciding with feature releases.

I did some investigation and the last full osm build we did was from `planet-150413.osm.pbf.md5 2015-04-15` [your pub](http://pelias.mapzen.com/doc?id=osmnode:3463649049) didn't land in the planet file until `2015-04-22 11:24`.

Currently our release strategy is to do full rebuilds rather than incremental updates, while we're still changing the code and the schema frequently, it's easier to work like this than to worry about migrating data between versions and dealing with duplicates/deletions/etc.

In order to provide zero downtime we spin up a second environment, build it up with fresh code and fresh data, run regression tests and then 'promote' that env live while decommissioning the old env.

Building the second env is all automated but there is a cost associated with spinning up 10x large elasticsearch instances and around 10x 'other' boxes required to import data and serve the API layers, plus it's someone's job to ensure it worked as expected and someone else's job to ensure that there were no unacceptable regressions introduced.

I personally feel it's not really 'worth it' for us to be super up-to-date at this stage of the project, having said that there is no technical reason that we can't do minutely/hourly/daily incremental updates, just it's not made it to the top of our internal dev backlog yet.

For this specific POI you might have to wait until I next tagged release of `github.com/pelias/openstreetmap` before it makes it in to live env that will replace the current one.

**Comment by stevevance** [comment]
thanks for the explanation @missinglink. I think you can see how antsy I am, but I agree that it's not very important to have this OSM edit in the live env. Could you make a status page that lists the last time planet was updated? Or, what about this: announce when you're going to update planet so that I can have all my edits done by that time? (I leave myself a lot of notes on OSM and then I fix them in a multi-hour sprint.)
