### ISSUE TITLE
[discuss] potential for builds to get 'stale'

### ISSUE THREAD

**Issue by missinglink** [pelias/pelias#86]
opening up a team discussion following my closing comment here: https://github.com/pelias/pelias/issues/85

as our live build cycle is based around new features being developed in the importers, as those import scripts become more mature and less feature development takes place in those repos, we will see larger and larger gaps between builds.

steven mentioned in [this comment](https://github.com/pelias/pelias/issues/85#issuecomment-98881468) how he added a POI to OSM and 17 days later it was still not present in Pelias.

I think the easiest solution to this issue is to define a maximum gap between builds, so for example, we would say "if osm hasn't been refreshed in 14 days and a new planet file exists, then we should start a new build even if the code is the same"

thoughts?

**Comment by dianashk** [comment]
:+1: for building on a regular basis, even if no changes have been made to our code. @heffergm, any reason this can't or shouldn't be done?

**Comment by heffergm** [comment]
Cost.

**Comment by heffergm** [comment]
It's also worth mentioning that there's nothing that says we have to wait for update OSM planet builds... we can simply apply the latest diff set to the most recent planet before building.

**Comment by dianashk** [comment]
Schedule bi-weekly builds on stage/prod

**Comment by heffergm** [comment]
For this to be feasible we need to adhere to certain things:
* staging should only ever be built off master for all repos and the api
* the acceptance tests need to pass
* failures don't get triaged, we just wait for the next run

That being said, the workflow to actually move that index into production isn't trivial in the sense that if we blow it up, it's essentially a guaranteed hour outage. The workflow, whether automated or otherwise, is along the lines of:
* verify the cluster is healthy
* check for a new snapshot
* if the latest snapshot is different that what's currently running:
  * drop any replicas on the current index (we could avoid this with more hardware, but I don't see much point in being over provisioned at the moment)
  * restore the snapshot
  * drop/create the alias to reference the new index
  * verify the cluster is green
  * drop the old index
  * add a replica

This workflow by necessity assumes certain things about all the process surrounding the build (i.e. staging) environment that we need to be careful with.

You can get a sense of what I'm talking about here perhaps: http://hastebin.com/xesinizapi

I'm not entirely comfortable automating that, but I'll give it some more thought.

**Comment by orangejulius** [comment]
Now that we have builds running once a week, we can close this, right?
