### ISSUE TITLE
local focus

### ISSUE THREAD

**Issue by gevarpm** [pelias/pelias#888]
Hi,

Firstly thanks to all who have worked on this project.

We have a requirement to expand the focus.point feature of autocomplete to boost results from a whole country, not just hyper local as it currently works.  So essentially expanding the geographic radius of the boost significantly.

Please can someone advise us on the most efficient way to achieve this? 

Many Thanks,
Robert

**Comment by missinglink** [comment]
Hi Robert,

There are a few different tunables which would can be tweaked to control the boost radius.

These settings control the boost distance and the algorithm used to influence the scoring for both the `/v1/autocomplete` and `/v1/search` endpoints:
- https://github.com/pelias/api/blob/master/query/autocomplete_defaults.js#L31-L35
- https://github.com/pelias/api/blob/master/query/search_defaults.js#L30-L34

They control how the [function_score](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html) subquery is generated in elasticsearch, it's a little complicated but also very powerful.

The tl;dr is you can define the maximum distance from the input point which will be affected and also the decay function used to control how distant places are scored lower than close places.
- https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#_supported_decay_functions

One thing to be aware of is that the Pelias defaults are configured to be a good balance between performance and result quality, by increasing the radius you'll find that you're matching many more places per keypress.

These hits will need to be loaded from disk and scored, this will likely have a heavy performance penalty, depending on how widely the radius is configured.

For longer inputs (several words) and smaller builds (such as those with <10m places) it's probably not a big deal but searching for a 2-3 letter input (such as 'st') on a planet-wide index could easily take >=3s.

This is usually unacceptable for autocomplete, which is why the defaults are set to ensure that the latency is always low for autocomplete.

In addition to that there are some other files which aim to improve performance for very short inputs for autocomplete (queries which routinely show up in slow logs), such as this https://github.com/pelias/api/blob/master/query/view/focus_point_distance_filter.js#L21-L30 which applies spatial proximity restrictions to queries with less than 8 characters.

Hope that helps.

**Comment by gevarpm** [comment]
Hi Peter,

Thanks for that, it was very helpful.

All the best,
Robert
