### ISSUE TITLE
Question about exposing `focus:weight` and `focus:scale` as query params

### ISSUE THREAD

**Issue by ellenhp** [pelias/pelias#933]
### Use-cases

I'm building a [maps app](https://github.com/headwaymaps/headway) and need a way to bias queries based on viewport and zoom. I want the ability to take a user query at zoom 14 and give them mostly only local results, and a query at zoom 2 and bias it much less strongly, perhaps just giving them results biased to the continent they're looking at.

Pelias can handle viewport biasing but currently the strength of the viewport biasing seems fixed. I saw `focus:weight` and `focus:scale` but I don't think these are exposed. Would it be possible to expose them?

### Attempted Solutions

I haven't been able to figure out a way to solve this with config, but I'll probably try and build a little proof of concept soon.

### Proposal

I think we could just modify [this block](https://github.com/pelias/api/blob/fa7238391128d9e23cea4de5e1e0fbc00aba1558/query/autocomplete.js#L118-L125) (and similar in other queries) to read the focus weight and scale from the query, overriding the defaults? I'm not sure if that could potentially degrade performance and open the door to DoS attacks but that's the easiest thing for my purposes because I can do fine-tuning client-side.

### References

https://github.com/headwaymaps/headway/issues/111

**Comment by missinglink** [comment]
Hi @ellenhp, nice to e-meet you 👋 

Internally we're using a [function score query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#_supported_decay_functions) in elasticsearch to do provide the 'focus' weighting functionality (ie. `focus.point.*`)

<img width="404" alt="decay_2d" src="https://user-images.githubusercontent.com/738069/188721256-b6f2cdc5-0c1d-46f1-ac81-77566e57aa2b.png">

As you mentioned, the `scale` variable has a significant impact on performance, as the 'hits' increase there is more work to score and rank the results, so internally within elasticsearch it's doing a lot of trig, but more importantly it's doing a lot of slow disk paging work sucking bytes into memory.

So yeah, I don't think that it's a great idea to make this variable controllable at query-time, it would be difficult to find 'bookend' values to clamp to, as dense urban areas such as NYC would still potentially return many hits in a small geographic region.

That being said, you can totally do it yourself, but we would probably not want to merge that into master ☹️ 

The `weight` is much less problematic as it wouldn't affect performance at all, but my ideal situation is if this 'just works' and is a detail hidden from the user rather than available for tuning.

In either case I'd be happy to explore the idea of allowing these constants to be tuned *per-installation*, so that your version differed from the defaults but that the values were selected by the person responsible for maintaining the server rather than the end user.

Lastly I just wanted to add that the `boundary.rect`, `boundary.gid` family of request params are strict filters, in that no results outside the boundary are returned, this is implemented differently from the above. IIRC the `focus.point` also has an implicit `boundary.circle` for performance reasons which may be undesirable for your application.

**Comment by ellenhp** [comment]
Hi! Thank you for the explanation. I definitely want to avoid exposing params that could open the door to an easy DoS.

I bet I could put a service in front of Pelias to handle some of these issues. I think my ideal scenario for zoom 12+ searches is to show local matches unless there are no good local matches. That sounds like something best accomplished by a shim on top of Pelias. It gives me a lot of flexibility without adding client-server round trips or increasing my maintenance burden, which is already getting to be pretty high for one person.
